// Generated by scripts/generate-rudder-mcp-tool-descriptors.ts. Do not edit by hand.
export const GENERATED_RUDDER_MCP_TOOL_DESCRIPTORS_000 = [
  {
    "capabilityId": "issue.comment",
    "name": "rudder_issue_comment",
    "description": "Add a comment to an issue, optionally uploading images and appending Markdown image links.",
    "semanticDescription": "Add a comment to an issue, optionally uploading images and appending Markdown image links. Mutating: yes. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: not required by this tool. Agent context: runtime env when available. Run attribution: attached from runtime env when available.",
    "annotations": {
      "destructiveHint": false,
      "idempotentHint": false,
      "readOnlyHint": false,
      "title": "Add a comment to an issue, optionally uploading images and appending Markdown image links"
    },
    "mutating": true,
    "requiresOrgId": false,
    "requiresAgentId": false,
    "attachesRunIdWhenAvailable": true,
    "inputSchema": {
      "additionalProperties": false,
      "anyOf": [
        {
          "required": [
            "body"
          ]
        },
        {
          "required": [
            "comment"
          ]
        }
      ],
      "properties": {
        "body": {
          "description": "Direct Markdown body.",
          "maxLength": 500000,
          "minLength": 1,
          "type": "string"
        },
        "comment": {
          "description": "Direct Markdown body.",
          "maxLength": 500000,
          "minLength": 1,
          "type": "string"
        },
        "images": {
          "description": "Local image paths to attach.",
          "items": {
            "description": "Local image paths to attach.",
            "maxLength": 8192,
            "minLength": 1,
            "type": "string"
          },
          "maxItems": 20,
          "type": "array"
        },
        "issue": {
          "description": "Issue UUID, identifier, or short reference.",
          "maxLength": 200,
          "minLength": 1,
          "type": "string"
        },
        "reopen": {
          "description": "Reopen the issue while commenting.",
          "type": "boolean"
        }
      },
      "required": [
        "issue"
      ],
      "type": "object"
    }
  },
  {
    "capabilityId": "issue.comments.list",
    "name": "rudder_issue_comments_list",
    "description": "List issue comments, optionally only newer comments after a full comment id or cmt_<uuid-prefix> with --after.",
    "semanticDescription": "List issue comments, optionally only newer comments after a full comment id or cmt_<uuid-prefix> with --after. Mutating: no. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: not required by this tool. Agent context: runtime env when available. Run attribution: not attached.",
    "annotations": {
      "destructiveHint": false,
      "idempotentHint": true,
      "readOnlyHint": true,
      "title": "List issue comments, optionally only newer comments after a full comment id or cmt_<uuid-prefix> with --after"
    },
    "mutating": false,
    "requiresOrgId": false,
    "requiresAgentId": false,
    "attachesRunIdWhenAvailable": false,
    "inputSchema": {
      "additionalProperties": false,
      "properties": {
        "after": {
          "description": "Return comments after this comment id or short reference.",
          "maxLength": 200,
          "minLength": 1,
          "type": "string"
        },
        "issue": {
          "description": "Issue UUID, identifier, or short reference.",
          "maxLength": 200,
          "minLength": 1,
          "type": "string"
        },
        "order": {
          "description": "Comment order.",
          "enum": [
            "asc",
            "desc"
          ],
          "maxLength": 10,
          "minLength": 1,
          "type": "string"
        }
      },
      "required": [
        "issue"
      ],
      "type": "object"
    }
  },
  {
    "capabilityId": "issue.comments.get",
    "name": "rudder_issue_comments_get",
    "description": "Read one issue comment by full id or cmt_<uuid-prefix> scoped to the issue.",
    "semanticDescription": "Read one issue comment by full id or cmt_<uuid-prefix> scoped to the issue. Mutating: no. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: not required by this tool. Agent context: runtime env when available. Run attribution: not attached.",
    "annotations": {
      "destructiveHint": false,
      "idempotentHint": true,
      "readOnlyHint": true,
      "title": "Read one issue comment by full id or cmt_<uuid-prefix> scoped to the issue"
    },
    "mutating": false,
    "requiresOrgId": false,
    "requiresAgentId": false,
    "attachesRunIdWhenAvailable": false,
    "inputSchema": {
      "additionalProperties": false,
      "properties": {
        "comment": {
          "description": "Comment id or short reference.",
          "maxLength": 200,
          "minLength": 1,
          "type": "string"
        },
        "issue": {
          "description": "Issue UUID, identifier, or short reference.",
          "maxLength": 200,
          "minLength": 1,
          "type": "string"
        }
      },
      "required": [
        "issue",
        "comment"
      ],
      "type": "object"
    }
  },
  {
    "capabilityId": "issue.update",
    "name": "rudder_issue_update",
    "description": "Apply generic issue updates when workflow commands are not enough, optionally uploading images for the update comment.",
    "semanticDescription": "Apply generic issue updates when workflow commands are not enough, optionally uploading images for the update comment. Mutating: yes. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: not required by this tool. Agent context: runtime env when available. Run attribution: attached from runtime env when available.",
    "annotations": {
      "destructiveHint": false,
      "idempotentHint": false,
      "readOnlyHint": false,
      "title": "Apply generic issue updates when workflow commands are not enough, optionally uploading images for the update comment"
    },
    "mutating": true,
    "requiresOrgId": false,
    "requiresAgentId": false,
    "attachesRunIdWhenAvailable": true,
    "inputSchema": {
      "additionalProperties": false,
      "properties": {
        "assigneeAgentId": {
          "description": "Assignee agent id or reference.",
          "maxLength": 200,
          "minLength": 1,
          "type": "string"
        },
        "billingCode": {
          "description": "Billing code.",
          "maxLength": 200,
          "minLength": 1,
          "type": "string"
        },
        "body": {
          "description": "Direct Markdown body.",
          "maxLength": 500000,
          "minLength": 1,
          "type": "string"
        },
        "comment": {
          "description": "Direct Markdown body.",
          "maxLength": 500000,
          "minLength": 1,
          "type": "string"
        },
        "description": {
          "description": "Issue description.",
          "maxLength": 500000,
          "minLength": 1,
          "type": "string"
        },
        "goalId": {
          "description": "Goal id or reference.",
          "maxLength": 200,
          "minLength": 1,
          "type": "string"
        },
        "hiddenAt": {
          "description": "Hidden timestamp.",
          "maxLength": 100,
          "minLength": 1,
          "type": "string"
        },
        "images": {
          "description": "Local image paths to attach.",
          "items": {
            "description": "Local image paths to attach.",
            "maxLength": 8192,
            "minLength": 1,
            "type": "string"
          },
          "maxItems": 20,
          "type": "array"
        },
        "issue": {
          "description": "Issue UUID, identifier, or short reference.",
          "maxLength": 200,
          "minLength": 1,
          "type": "string"
        },
        "parentId": {
          "description": "Parent issue id or reference.",
          "maxLength": 200,
          "minLength": 1,
          "type": "string"
        },
        "priority": {
          "description": "New issue priority.",
          "maxLength": 100,
          "minLength": 1,
          "type": "string"
        },
        "projectId": {
          "description": "Project id or reference.",
          "maxLength": 200,
          "minLength": 1,
          "type": "string"
        },
        "requestDepth": {
          "description": "Requested issue depth.",
          "maxLength": 30,
          "minLength": 1,
          "type": "string"
        },
        "status": {
          "description": "New issue status.",
          "maxLength": 100,
          "minLength": 1,
          "type": "string"
        },
        "title": {
          "description": "Issue title.",
          "maxLength": 500,
          "minLength": 1,
          "type": "string"
        }
      },
      "required": [
        "issue"
      ],
      "type": "object"
    }
  },
  {
    "capabilityId": "issue.review",
    "name": "rudder_issue_review",
    "description": "Record a structured reviewer decision with a required comment.",
    "semanticDescription": "Record a structured reviewer decision with a required comment. Mutating: yes. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: not required by this tool. Agent context: runtime env when available. Run attribution: attached from runtime env when available.",
    "annotations": {
      "destructiveHint": false,
      "idempotentHint": false,
      "readOnlyHint": false,
      "title": "Record a structured reviewer decision with a required comment"
    },
    "mutating": true,
    "requiresOrgId": false,
    "requiresAgentId": false,
    "attachesRunIdWhenAvailable": true,
    "inputSchema": {
      "additionalProperties": false,
      "anyOf": [
        {
          "required": [
            "comment"
          ]
        },
        {
          "required": [
            "body"
          ]
        }
      ],
      "properties": {
        "body": {
          "description": "Direct Markdown body.",
          "maxLength": 500000,
          "minLength": 1,
          "type": "string"
        },
        "comment": {
          "description": "Direct Markdown body.",
          "maxLength": 500000,
          "minLength": 1,
          "type": "string"
        },
        "decision": {
          "description": "Structured review decision.",
          "enum": [
            "approve",
            "request_changes",
            "needs_followup",
            "blocked"
          ],
          "maxLength": 30,
          "minLength": 1,
          "type": "string"
        },
        "issue": {
          "description": "Issue UUID, identifier, or short reference.",
          "maxLength": 200,
          "minLength": 1,
          "type": "string"
        }
      },
      "required": [
        "issue",
        "decision"
      ],
      "type": "object"
    }
  },
  {
    "capabilityId": "issue.commit",
    "name": "rudder_issue_commit",
    "description": "Report a code commit created during issue work as structured issue activity.",
    "semanticDescription": "Report a code commit created during issue work as structured issue activity. Mutating: yes. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: not required by this tool. Agent context: runtime env when available. Run attribution: attached from runtime env when available.",
    "annotations": {
      "destructiveHint": false,
      "idempotentHint": false,
      "readOnlyHint": false,
      "title": "Report a code commit created during issue work as structured issue activity"
    },
    "mutating": true,
    "requiresOrgId": false,
    "requiresAgentId": false,
    "attachesRunIdWhenAvailable": true,
    "inputSchema": {
      "additionalProperties": false,
      "properties": {
        "branch": {
          "description": "Git branch name.",
          "maxLength": 500,
          "minLength": 1,
          "type": "string"
        },
        "count": {
          "description": "Number of commits represented.",
          "maximum": 10000,
          "minimum": 1,
          "type": "number"
        },
        "issue": {
          "description": "Issue UUID, identifier, or short reference.",
          "maxLength": 200,
          "minLength": 1,
          "type": "string"
        },
        "message": {
          "description": "Commit subject or status message.",
          "maxLength": 2000,
          "minLength": 1,
          "type": "string"
        },
        "repoPath": {
          "description": "Repository path.",
          "maxLength": 8192,
          "minLength": 1,
          "type": "string"
        },
        "sha": {
          "description": "Git commit SHA.",
          "maxLength": 100,
          "minLength": 1,
          "type": "string"
        },
        "workspacePath": {
          "description": "Workspace path.",
          "maxLength": 8192,
          "minLength": 1,
          "type": "string"
        }
      },
      "required": [
        "issue",
        "sha",
        "message"
      ],
      "type": "object"
    }
  },
  {
    "capabilityId": "issue.done",
    "name": "rudder_issue_done",
    "description": "Mark an issue done with a required completion comment, optionally uploading images.",
    "semanticDescription": "Mark an issue done with a required completion comment, optionally uploading images. Mutating: yes. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: not required by this tool. Agent context: runtime env when available. Run attribution: attached from runtime env when available.",
    "annotations": {
      "destructiveHint": true,
      "idempotentHint": false,
      "readOnlyHint": false,
      "title": "Mark an issue done with a required completion comment, optionally uploading images"
    },
    "mutating": true,
    "requiresOrgId": false,
    "requiresAgentId": false,
    "attachesRunIdWhenAvailable": true,
    "inputSchema": {
      "additionalProperties": false,
      "anyOf": [
        {
          "required": [
            "comment"
          ]
        },
        {
          "required": [
            "body"
          ]
        }
      ],
      "properties": {
        "body": {
          "description": "Direct Markdown body.",
          "maxLength": 500000,
          "minLength": 1,
          "type": "string"
        },
        "comment": {
          "description": "Direct Markdown body.",
          "maxLength": 500000,
          "minLength": 1,
          "type": "string"
        },
        "images": {
          "description": "Local image paths to attach.",
          "items": {
            "description": "Local image paths to attach.",
            "maxLength": 8192,
            "minLength": 1,
            "type": "string"
          },
          "maxItems": 20,
          "type": "array"
        },
        "issue": {
          "description": "Issue UUID, identifier, or short reference.",
          "maxLength": 200,
          "minLength": 1,
          "type": "string"
        }
      },
      "required": [
        "issue"
      ],
      "type": "object"
    }
  },
  {
    "capabilityId": "issue.block",
    "name": "rudder_issue_block",
    "description": "Request human assistance after bounded recovery attempts; repeated matching claims are audited before the Issue becomes blocked.",
    "semanticDescription": "Request human assistance after bounded recovery attempts; repeated matching claims are audited before the Issue becomes blocked. Mutating: yes. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: not required by this tool. Agent context: runtime env when available. Run attribution: attached from runtime env when available.",
    "annotations": {
      "destructiveHint": true,
      "idempotentHint": false,
      "readOnlyHint": false,
      "title": "Request human assistance after bounded recovery attempts"
    },
    "mutating": true,
    "requiresOrgId": false,
    "requiresAgentId": false,
    "attachesRunIdWhenAvailable": true,
    "inputSchema": {
      "additionalProperties": false,
      "anyOf": [
        {
          "required": [
            "comment"
          ]
        },
        {
          "required": [
            "body"
          ]
        }
      ],
      "properties": {
        "body": {
          "description": "Direct Markdown body.",
          "maxLength": 500000,
          "minLength": 1,
          "type": "string"
        },
        "comment": {
          "description": "Direct Markdown body.",
          "maxLength": 500000,
          "minLength": 1,
          "type": "string"
        },
        "images": {
          "description": "Local image paths to attach.",
          "items": {
            "description": "Local image paths to attach.",
            "maxLength": 8192,
            "minLength": 1,
            "type": "string"
          },
          "maxItems": 20,
          "type": "array"
        },
        "issue": {
          "description": "Issue UUID, identifier, or short reference.",
          "maxLength": 200,
          "minLength": 1,
          "type": "string"
        }
      },
      "required": [
        "issue"
      ],
      "type": "object"
    }
  },
  {
    "capabilityId": "project.list",
    "name": "rudder_project_list",
    "description": "List projects in an organization.",
    "semanticDescription": "List projects in an organization. Mutating: no. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: required from runtime env. Agent context: runtime env when available. Run attribution: not attached.",
    "annotations": {
      "destructiveHint": false,
      "idempotentHint": true,
      "readOnlyHint": true,
      "title": "List projects in an organization"
    },
    "mutating": false,
    "requiresOrgId": true,
    "requiresAgentId": false,
    "attachesRunIdWhenAvailable": false,
    "inputSchema": {
      "additionalProperties": false,
      "properties": {},
      "type": "object"
    }
  },
  {
    "capabilityId": "project.get",
    "name": "rudder_project_get",
    "description": "Read one project by ID or shortname.",
    "semanticDescription": "Read one project by ID or shortname. Mutating: no. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: not required by this tool. Agent context: runtime env when available. Run attribution: not attached.",
    "annotations": {
      "destructiveHint": false,
      "idempotentHint": true,
      "readOnlyHint": true,
      "title": "Read one project by ID or shortname"
    },
    "mutating": false,
    "requiresOrgId": false,
    "requiresAgentId": false,
    "attachesRunIdWhenAvailable": false,
    "inputSchema": {
      "additionalProperties": false,
      "properties": {
        "project": {
          "description": "Project UUID or shortname.",
          "maxLength": 200,
          "minLength": 1,
          "type": "string"
        }
      },
      "required": [
        "project"
      ],
      "type": "object"
    }
  },
  {
    "capabilityId": "project.create",
    "name": "rudder_project_create",
    "description": "Create a project in the organization.",
    "semanticDescription": "Create a project in the organization. Mutating: yes. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: required from runtime env. Agent context: runtime env when available. Run attribution: attached from runtime env when available.",
    "annotations": {
      "destructiveHint": false,
      "idempotentHint": false,
      "readOnlyHint": false,
      "title": "Create a project in the organization"
    },
    "mutating": true,
    "requiresOrgId": true,
    "requiresAgentId": false,
    "attachesRunIdWhenAvailable": true,
    "inputSchema": {
      "additionalProperties": false,
      "properties": {
        "color": {
          "description": "Display color.",
          "maxLength": 100,
          "minLength": 1,
          "type": "string"
        },
        "description": {
          "description": "Project description.",
          "maxLength": 500000,
          "minLength": 1,
          "type": "string"
        },
        "goalId": {
          "description": "Goal id or reference.",
          "maxLength": 200,
          "minLength": 1,
          "type": "string"
        },
        "goalIds": {
          "description": "Goal ids.",
          "items": {
            "description": "Goal ids.",
            "maxLength": 8192,
            "minLength": 1,
            "type": "string"
          },
          "maxItems": 100,
          "type": "array"
        },
        "leadAgentId": {
          "description": "Lead agent id or reference.",
          "maxLength": 200,
          "minLength": 1,
          "type": "string"
        },
        "name": {
          "description": "Project name.",
          "maxLength": 300,
          "minLength": 1,
          "type": "string"
        },
        "status": {
          "description": "Project status.",
          "maxLength": 100,
          "minLength": 1,
          "type": "string"
        },
        "targetDate": {
          "description": "Target date.",
          "maxLength": 100,
          "minLength": 1,
          "type": "string"
        }
      },
      "required": [
        "name"
      ],
      "type": "object"
    }
  },
  {
    "capabilityId": "project.update",
    "name": "rudder_project_update",
    "description": "Update mutable project fields such as name, description, status, goals, lead agent, target date, color, or archivedAt.",
    "semanticDescription": "Update mutable project fields such as name, description, status, goals, lead agent, target date, color, or archivedAt. Mutating: yes. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: not required by this tool. Agent context: runtime env when available. Run attribution: attached from runtime env when available.",
    "annotations": {
      "destructiveHint": false,
      "idempotentHint": false,
      "readOnlyHint": false,
      "title": "Update mutable project fields such as name, description, status, goals, lead agent, target date, color, or archivedAt"
    },
    "mutating": true,
    "requiresOrgId": false,
    "requiresAgentId": false,
    "attachesRunIdWhenAvailable": true,
    "inputSchema": {
      "additionalProperties": false,
      "properties": {
        "archivedAt": {
          "description": "Archive timestamp.",
          "maxLength": 100,
          "minLength": 1,
          "type": "string"
        },
        "color": {
          "description": "Display color.",
          "maxLength": 100,
          "minLength": 1,
          "type": "string"
        },
        "description": {
          "description": "Project description.",
          "maxLength": 500000,
          "minLength": 1,
          "type": "string"
        },
        "goalId": {
          "description": "Goal id or reference.",
          "maxLength": 200,
          "minLength": 1,
          "type": "string"
        },
        "goalIds": {
          "description": "Goal ids.",
          "items": {
            "description": "Goal ids.",
            "maxLength": 8192,
            "minLength": 1,
            "type": "string"
          },
          "maxItems": 100,
          "type": "array"
        },
        "idempotencyKey": {
          "description": "Stable key for retrying project updates; required when changing Project-Goal links.",
          "maxLength": 256,
          "minLength": 1,
          "type": "string"
        },
        "leadAgentId": {
          "description": "Lead agent id or reference.",
          "maxLength": 200,
          "minLength": 1,
          "type": "string"
        },
        "name": {
          "description": "Project name.",
          "maxLength": 300,
          "minLength": 1,
          "type": "string"
        },
        "project": {
          "description": "Project UUID or shortname.",
          "maxLength": 200,
          "minLength": 1,
          "type": "string"
        },
        "status": {
          "description": "Project status.",
          "maxLength": 100,
          "minLength": 1,
          "type": "string"
        },
        "targetDate": {
          "description": "Target date.",
          "maxLength": 100,
          "minLength": 1,
          "type": "string"
        }
      },
      "required": [
        "project"
      ],
      "type": "object"
    }
  },
  {
    "capabilityId": "user.activity",
    "name": "rudder_user_activity",
    "description": "Read a user-centered activity ledger with safe excerpts and provenance across chats, issue comments, approval comments, and user actor activity.",
    "semanticDescription": "Read a user-centered activity ledger with safe excerpts and provenance across chats, issue comments, approval comments, and user actor activity. Mutating: no. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: required from runtime env. Agent context: runtime env when available. Run attribution: not attached.",
    "annotations": {
      "destructiveHint": false,
      "idempotentHint": true,
      "readOnlyHint": true,
      "title": "Read a user-centered activity ledger with safe excerpts and provenance across chats, issue comments, approval comments, and user actor activity"
    },
    "mutating": false,
    "requiresOrgId": true,
    "requiresAgentId": false,
    "attachesRunIdWhenAvailable": false,
    "inputSchema": {
      "additionalProperties": false,
      "properties": {
        "cursor": {
          "description": "Opaque pagination cursor.",
          "maxLength": 2000,
          "minLength": 1,
          "type": "string"
        },
        "include": {
          "description": "Comma-separated optional sections.",
          "maxLength": 500,
          "minLength": 1,
          "type": "string"
        },
        "issueId": {
          "description": "Issue id.",
          "maxLength": 200,
          "minLength": 1,
          "type": "string"
        },
        "limit": {
          "description": "Page size.",
          "maximum": 100,
          "minimum": 1,
          "type": "number"
        },
        "projectId": {
          "description": "Project id.",
          "maxLength": 200,
          "minLength": 1,
          "type": "string"
        },
        "relatedAgentId": {
          "description": "Related agent id.",
          "maxLength": 200,
          "minLength": 1,
          "type": "string"
        },
        "since": {
          "description": "Activity start timestamp.",
          "maxLength": 100,
          "minLength": 1,
          "type": "string"
        },
        "until": {
          "description": "Activity end timestamp.",
          "maxLength": 100,
          "minLength": 1,
          "type": "string"
        },
        "user": {
          "description": "User id, reference, or self.",
          "maxLength": 200,
          "minLength": 1,
          "type": "string"
        }
      },
      "type": "object"
    }
  },
  {
    "capabilityId": "library.file.list",
    "name": "rudder_library_file_list",
    "description": "List Library files and folders; file rows include `libraryEntryId` when a strong reference can be generated.",
    "semanticDescription": "List Library files and folders; file rows include `libraryEntryId` when a strong reference can be generated. Mutating: no. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: required from runtime env. Agent context: runtime env when available. Run attribution: not attached.",
    "annotations": {
      "destructiveHint": false,
      "idempotentHint": true,
      "readOnlyHint": true,
      "title": "List Library files and folders"
    },
    "mutating": false,
    "requiresOrgId": true,
    "requiresAgentId": false,
    "attachesRunIdWhenAvailable": false,
    "inputSchema": {
      "additionalProperties": false,
      "properties": {
        "directory": {
          "description": "Library-relative directory path.",
          "maxLength": 8192,
          "minLength": 1,
          "type": "string"
        },
        "path": {
          "description": "Compatibility alias for directory.",
          "maxLength": 8192,
          "minLength": 1,
          "type": "string"
        }
      },
      "type": "object"
    }
  },
  {
    "capabilityId": "library.file.get",
    "name": "rudder_library_file_get",
    "description": "Fallback read when local filesystem access is unavailable; JSON includes `mentionHref` and `markdownLink`.",
    "semanticDescription": "Fallback read when local filesystem access is unavailable; JSON includes `mentionHref` and `markdownLink`. Mutating: no. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: required from runtime env. Agent context: runtime env when available. Run attribution: not attached.",
    "annotations": {
      "destructiveHint": false,
      "idempotentHint": true,
      "readOnlyHint": true,
      "title": "Fallback read when local filesystem access is unavailable"
    },
    "mutating": false,
    "requiresOrgId": true,
    "requiresAgentId": false,
    "attachesRunIdWhenAvailable": false,
    "inputSchema": {
      "additionalProperties": false,
      "properties": {
        "path": {
          "description": "Library-relative file path.",
          "maxLength": 8192,
          "minLength": 1,
          "type": "string"
        }
      },
      "required": [
        "path"
      ],
      "type": "object"
    }
  },
  {
    "capabilityId": "library.file.ref",
    "name": "rudder_library_file_ref",
    "description": "Return the stable Markdown reference for one Library file without printing file content.",
    "semanticDescription": "Return the stable Markdown reference for one Library file without printing file content. Mutating: no. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: required from runtime env. Agent context: runtime env when available. Run attribution: not attached.",
    "annotations": {
      "destructiveHint": false,
      "idempotentHint": true,
      "readOnlyHint": true,
      "title": "Return the stable Markdown reference for one Library file without printing file content"
    },
    "mutating": false,
    "requiresOrgId": true,
    "requiresAgentId": false,
    "attachesRunIdWhenAvailable": false,
    "inputSchema": {
      "additionalProperties": false,
      "properties": {
        "path": {
          "description": "Library-relative file path.",
          "maxLength": 8192,
          "minLength": 1,
          "type": "string"
        }
      },
      "required": [
        "path"
      ],
      "type": "object"
    }
  },
  {
    "capabilityId": "library.file.link",
    "name": "rudder_library_file_link",
    "description": "Compatibility alias for `rudder library file ref <path>`.",
    "semanticDescription": "Compatibility alias for `rudder library file ref <path>`. Mutating: no. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: required from runtime env. Agent context: runtime env when available. Run attribution: not attached.",
    "annotations": {
      "destructiveHint": false,
      "idempotentHint": true,
      "readOnlyHint": true,
      "title": "Compatibility alias for `rudder library file ref <path>`"
    },
    "mutating": false,
    "requiresOrgId": true,
    "requiresAgentId": false,
    "attachesRunIdWhenAvailable": false,
    "inputSchema": {
      "additionalProperties": false,
      "properties": {
        "path": {
          "description": "Library-relative file path.",
          "maxLength": 8192,
          "minLength": 1,
          "type": "string"
        }
      },
      "required": [
        "path"
      ],
      "type": "object"
    }
  },
  {
    "capabilityId": "library.file.put",
    "name": "rudder_library_file_put",
    "description": "Fallback create/update when local filesystem access is unavailable; JSON includes `mentionHref` and `markdownLink`.",
    "semanticDescription": "Fallback create/update when local filesystem access is unavailable; JSON includes `mentionHref` and `markdownLink`. Mutating: yes. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: required from runtime env. Agent context: runtime env when available. Run attribution: attached from runtime env when available.",
    "annotations": {
      "destructiveHint": true,
      "idempotentHint": false,
      "readOnlyHint": false,
      "title": "Fallback create/update when local filesystem access is unavailable"
    },
    "mutating": true,
    "requiresOrgId": true,
    "requiresAgentId": false,
    "attachesRunIdWhenAvailable": true,
    "inputSchema": {
      "additionalProperties": false,
      "anyOf": [
        {
          "required": [
            "body"
          ]
        },
        {
          "required": [
            "content"
          ]
        }
      ],
      "properties": {
        "body": {
          "description": "Direct file content.",
          "maxLength": 1000000,
          "minLength": 1,
          "type": "string"
        },
        "content": {
          "description": "Compatibility alias for body.",
          "maxLength": 1000000,
          "minLength": 1,
          "type": "string"
        },
        "path": {
          "description": "Library-relative file path.",
          "maxLength": 8192,
          "minLength": 1,
          "type": "string"
        }
      },
      "required": [
        "path"
      ],
      "type": "object"
    }
  },
  {
    "capabilityId": "issue.create",
    "name": "rudder_issue_create",
    "description": "Create a new issue or subtask with the generic issue surface; agent-created issues default to the creating agent when no assignee is supplied.",
    "semanticDescription": "Create a new issue or subtask with the generic issue surface; agent-created issues default to the creating agent when no assignee is supplied. Mutating: yes. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: required from runtime env. Agent context: runtime env when available. Run attribution: attached from runtime env when available.",
    "annotations": {
      "destructiveHint": false,
      "idempotentHint": false,
      "readOnlyHint": false,
      "title": "Create a new issue or subtask with the generic issue surface"
    },
    "mutating": true,
    "requiresOrgId": true,
    "requiresAgentId": false,
    "attachesRunIdWhenAvailable": true,
    "inputSchema": {
      "additionalProperties": false,
      "properties": {
        "assigneeAgentId": {
          "description": "Assignee agent id or reference.",
          "maxLength": 200,
          "minLength": 1,
          "type": "string"
        },
        "billingCode": {
          "description": "Billing code.",
          "maxLength": 200,
          "minLength": 1,
          "type": "string"
        },
        "description": {
          "description": "Issue description.",
          "maxLength": 500000,
          "minLength": 1,
          "type": "string"
        },
        "goalId": {
          "description": "Goal id or reference.",
          "maxLength": 200,
          "minLength": 1,
          "type": "string"
        },
        "labelIds": {
          "description": "Issue label ids.",
          "items": {
            "description": "Issue label ids.",
            "maxLength": 8192,
            "minLength": 1,
            "type": "string"
          },
          "maxItems": 100,
          "type": "array"
        },
        "parentId": {
          "description": "Parent issue id or reference.",
          "maxLength": 200,
          "minLength": 1,
          "type": "string"
        },
        "priority": {
          "description": "Issue priority.",
          "maxLength": 100,
          "minLength": 1,
          "type": "string"
        },
        "projectId": {
          "description": "Project id or reference.",
          "maxLength": 200,
          "minLength": 1,
          "type": "string"
        },
        "requestDepth": {
          "description": "Requested issue depth.",
          "maximum": 10000,
          "minimum": 0,
          "type": "number"
        },
        "status": {
          "description": "Issue status.",
          "maxLength": 100,
          "minLength": 1,
          "type": "string"
        },
        "title": {
          "description": "Issue title.",
          "maxLength": 500,
          "minLength": 1,
          "type": "string"
        }
      },
      "required": [
        "title"
      ],
      "type": "object"
    }
  },
  {
    "capabilityId": "approval.get",
    "name": "rudder_approval_get",
    "description": "Read one approval request.",
    "semanticDescription": "Read one approval request. Mutating: no. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: not required by this tool. Agent context: runtime env when available. Run attribution: not attached.",
    "annotations": {
      "destructiveHint": false,
      "idempotentHint": true,
      "readOnlyHint": true,
      "title": "Read one approval request"
    },
    "mutating": false,
    "requiresOrgId": false,
    "requiresAgentId": false,
    "attachesRunIdWhenAvailable": false,
    "inputSchema": {
      "additionalProperties": false,
      "properties": {
        "approval": {
          "description": "Approval UUID or short reference.",
          "maxLength": 200,
          "minLength": 1,
          "type": "string"
        }
      },
      "required": [
        "approval"
      ],
      "type": "object"
    }
  },
  {
    "capabilityId": "approval.issues",
    "name": "rudder_approval_issues",
    "description": "List the issues linked to an approval.",
    "semanticDescription": "List the issues linked to an approval. Mutating: no. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: not required by this tool. Agent context: runtime env when available. Run attribution: not attached.",
    "annotations": {
      "destructiveHint": false,
      "idempotentHint": true,
      "readOnlyHint": true,
      "title": "List the issues linked to an approval"
    },
    "mutating": false,
    "requiresOrgId": false,
    "requiresAgentId": false,
    "attachesRunIdWhenAvailable": false,
    "inputSchema": {
      "additionalProperties": false,
      "properties": {
        "approval": {
          "description": "Approval UUID or short reference.",
          "maxLength": 200,
          "minLength": 1,
          "type": "string"
        }
      },
      "required": [
        "approval"
      ],
      "type": "object"
    }
  }
] as const;
