// Generated by scripts/generate-rudder-mcp-tool-descriptors.ts. Do not edit by hand.
export const GENERATED_RUDDER_AGENT_CONTRACT_CAPABILITIES_001 = [
  {
    "api": {
      "method": "POST",
      "pathTemplate": "/api/issues/{issue}/checkout",
      "transport": "direct"
    },
    "cli": {
      "attachesRunIdWhenAvailable": true,
      "category": "issue",
      "command": "rudder issue checkout <issue>",
      "contract": "agent-v1",
      "description": "Atomically checkout an issue for the current or specified agent.",
      "id": "issue.checkout",
      "mutating": true,
      "requiresAgentId": true,
      "requiresOrgId": false,
      "requiresRunId": false
    },
    "id": "issue.checkout",
    "mcp": {
      "annotations": {
        "destructiveHint": false,
        "idempotentHint": false,
        "readOnlyHint": false,
        "title": "Atomically checkout an issue for the current or specified agent"
      },
      "capabilityId": "issue.checkout",
      "description": "Atomically checkout an issue for the current or specified agent. Mutating: yes. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: not required by this tool. Agent context: required from runtime env. Run attribution: attached from runtime env when available.",
      "inputSchema": {
        "additionalProperties": false,
        "properties": {
          "expectedStatuses": {
            "description": "Comma-separated allowed prior statuses.",
            "maxLength": 500,
            "minLength": 1,
            "type": "string"
          },
          "issue": {
            "description": "Issue UUID, identifier, or short reference.",
            "maxLength": 200,
            "minLength": 1,
            "type": "string"
          }
        },
        "required": [
          "issue"
        ],
        "type": "object"
      },
      "name": "rudder_issue_checkout"
    }
  },
  {
    "api": {
      "method": "POST",
      "pathTemplate": "/api/issues/{issue}/comments",
      "transport": "direct"
    },
    "cli": {
      "attachesRunIdWhenAvailable": true,
      "category": "issue",
      "command": "rudder issue comment <issue> --body-file <path> [--image <path>]",
      "contract": "agent-v1",
      "description": "Add a comment to an issue, optionally uploading images and appending Markdown image links.",
      "id": "issue.comment",
      "mutating": true,
      "requiresAgentId": false,
      "requiresOrgId": false,
      "requiresRunId": false
    },
    "id": "issue.comment",
    "mcp": {
      "annotations": {
        "destructiveHint": false,
        "idempotentHint": false,
        "readOnlyHint": false,
        "title": "Add a comment to an issue, optionally uploading images and appending Markdown image links"
      },
      "capabilityId": "issue.comment",
      "description": "Add a comment to an issue, optionally uploading images and appending Markdown image links. Mutating: yes. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: not required by this tool. Agent context: runtime env when available. Run attribution: attached from runtime env when available.",
      "inputSchema": {
        "additionalProperties": false,
        "anyOf": [
          {
            "required": [
              "body"
            ]
          },
          {
            "required": [
              "comment"
            ]
          }
        ],
        "properties": {
          "body": {
            "description": "Direct Markdown body.",
            "maxLength": 500000,
            "minLength": 1,
            "type": "string"
          },
          "comment": {
            "description": "Direct Markdown body.",
            "maxLength": 500000,
            "minLength": 1,
            "type": "string"
          },
          "images": {
            "description": "Local image paths to attach.",
            "items": {
              "description": "Local image paths to attach.",
              "maxLength": 8192,
              "minLength": 1,
              "type": "string"
            },
            "maxItems": 20,
            "type": "array"
          },
          "issue": {
            "description": "Issue UUID, identifier, or short reference.",
            "maxLength": 200,
            "minLength": 1,
            "type": "string"
          },
          "reopen": {
            "description": "Reopen the issue while commenting.",
            "type": "boolean"
          }
        },
        "required": [
          "issue"
        ],
        "type": "object"
      },
      "name": "rudder_issue_comment"
    }
  },
  {
    "api": {
      "method": "GET",
      "pathTemplate": "/api/issues/{issue}/comments",
      "transport": "direct"
    },
    "cli": {
      "attachesRunIdWhenAvailable": false,
      "category": "issue",
      "command": "rudder issue comments list <issue> [--after <comment-id-or-cmt-ref>]",
      "contract": "agent-v1",
      "description": "List issue comments, optionally only newer comments after a full comment id or cmt_<uuid-prefix> with --after.",
      "id": "issue.comments.list",
      "mutating": false,
      "requiresAgentId": false,
      "requiresOrgId": false,
      "requiresRunId": false
    },
    "id": "issue.comments.list",
    "mcp": {
      "annotations": {
        "destructiveHint": false,
        "idempotentHint": true,
        "readOnlyHint": true,
        "title": "List issue comments, optionally only newer comments after a full comment id or cmt_<uuid-prefix> with --after"
      },
      "capabilityId": "issue.comments.list",
      "description": "List issue comments, optionally only newer comments after a full comment id or cmt_<uuid-prefix> with --after. Mutating: no. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: not required by this tool. Agent context: runtime env when available. Run attribution: not attached.",
      "inputSchema": {
        "additionalProperties": false,
        "properties": {
          "after": {
            "description": "Return comments after this comment id or short reference.",
            "maxLength": 200,
            "minLength": 1,
            "type": "string"
          },
          "issue": {
            "description": "Issue UUID, identifier, or short reference.",
            "maxLength": 200,
            "minLength": 1,
            "type": "string"
          },
          "order": {
            "description": "Comment order.",
            "enum": [
              "asc",
              "desc"
            ],
            "maxLength": 10,
            "minLength": 1,
            "type": "string"
          }
        },
        "required": [
          "issue"
        ],
        "type": "object"
      },
      "name": "rudder_issue_comments_list"
    }
  },
  {
    "api": {
      "method": "GET",
      "pathTemplate": "/api/issues/{issue}/comments/{comment}",
      "transport": "direct"
    },
    "cli": {
      "attachesRunIdWhenAvailable": false,
      "category": "issue",
      "command": "rudder issue comments get <issue> <comment-id-or-cmt-ref>",
      "contract": "agent-v1",
      "description": "Read one issue comment by full id or cmt_<uuid-prefix> scoped to the issue.",
      "id": "issue.comments.get",
      "mutating": false,
      "requiresAgentId": false,
      "requiresOrgId": false,
      "requiresRunId": false
    },
    "id": "issue.comments.get",
    "mcp": {
      "annotations": {
        "destructiveHint": false,
        "idempotentHint": true,
        "readOnlyHint": true,
        "title": "Read one issue comment by full id or cmt_<uuid-prefix> scoped to the issue"
      },
      "capabilityId": "issue.comments.get",
      "description": "Read one issue comment by full id or cmt_<uuid-prefix> scoped to the issue. Mutating: no. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: not required by this tool. Agent context: runtime env when available. Run attribution: not attached.",
      "inputSchema": {
        "additionalProperties": false,
        "properties": {
          "comment": {
            "description": "Comment id or short reference.",
            "maxLength": 200,
            "minLength": 1,
            "type": "string"
          },
          "issue": {
            "description": "Issue UUID, identifier, or short reference.",
            "maxLength": 200,
            "minLength": 1,
            "type": "string"
          }
        },
        "required": [
          "issue",
          "comment"
        ],
        "type": "object"
      },
      "name": "rudder_issue_comments_get"
    }
  },
  {
    "api": {
      "transport": "cli-fallback"
    },
    "cli": {
      "attachesRunIdWhenAvailable": true,
      "category": "issue",
      "command": "rudder issue update <issue> ... [--comment-file <path>] [--image <path>]",
      "contract": "agent-v1",
      "description": "Apply generic issue updates when workflow commands are not enough, optionally uploading images for the update comment.",
      "id": "issue.update",
      "mutating": true,
      "requiresAgentId": false,
      "requiresOrgId": false,
      "requiresRunId": false
    },
    "id": "issue.update",
    "mcp": {
      "annotations": {
        "destructiveHint": false,
        "idempotentHint": false,
        "readOnlyHint": false,
        "title": "Apply generic issue updates when workflow commands are not enough, optionally uploading images for the update comment"
      },
      "capabilityId": "issue.update",
      "description": "Apply generic issue updates when workflow commands are not enough, optionally uploading images for the update comment. Mutating: yes. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: not required by this tool. Agent context: runtime env when available. Run attribution: attached from runtime env when available.",
      "inputSchema": {
        "additionalProperties": false,
        "properties": {
          "assigneeAgentId": {
            "description": "Assignee agent id or reference.",
            "maxLength": 200,
            "minLength": 1,
            "type": "string"
          },
          "billingCode": {
            "description": "Billing code.",
            "maxLength": 200,
            "minLength": 1,
            "type": "string"
          },
          "body": {
            "description": "Direct Markdown body.",
            "maxLength": 500000,
            "minLength": 1,
            "type": "string"
          },
          "comment": {
            "description": "Direct Markdown body.",
            "maxLength": 500000,
            "minLength": 1,
            "type": "string"
          },
          "description": {
            "description": "Issue description.",
            "maxLength": 500000,
            "minLength": 1,
            "type": "string"
          },
          "goalId": {
            "description": "Goal id or reference.",
            "maxLength": 200,
            "minLength": 1,
            "type": "string"
          },
          "hiddenAt": {
            "description": "Hidden timestamp.",
            "maxLength": 100,
            "minLength": 1,
            "type": "string"
          },
          "images": {
            "description": "Local image paths to attach.",
            "items": {
              "description": "Local image paths to attach.",
              "maxLength": 8192,
              "minLength": 1,
              "type": "string"
            },
            "maxItems": 20,
            "type": "array"
          },
          "issue": {
            "description": "Issue UUID, identifier, or short reference.",
            "maxLength": 200,
            "minLength": 1,
            "type": "string"
          },
          "parentId": {
            "description": "Parent issue id or reference.",
            "maxLength": 200,
            "minLength": 1,
            "type": "string"
          },
          "priority": {
            "description": "New issue priority.",
            "maxLength": 100,
            "minLength": 1,
            "type": "string"
          },
          "projectId": {
            "description": "Project id or reference.",
            "maxLength": 200,
            "minLength": 1,
            "type": "string"
          },
          "requestDepth": {
            "description": "Requested issue depth.",
            "maxLength": 30,
            "minLength": 1,
            "type": "string"
          },
          "status": {
            "description": "New issue status.",
            "maxLength": 100,
            "minLength": 1,
            "type": "string"
          },
          "title": {
            "description": "Issue title.",
            "maxLength": 500,
            "minLength": 1,
            "type": "string"
          }
        },
        "required": [
          "issue"
        ],
        "type": "object"
      },
      "name": "rudder_issue_update"
    }
  },
  {
    "api": {
      "transport": "cli-fallback"
    },
    "cli": {
      "attachesRunIdWhenAvailable": true,
      "category": "issue",
      "command": "rudder issue review <issue> --decision <decision> --comment-file <path>",
      "contract": "agent-v1",
      "description": "Record a structured reviewer decision with a required comment.",
      "id": "issue.review",
      "mutating": true,
      "requiresAgentId": false,
      "requiresOrgId": false,
      "requiresRunId": false
    },
    "id": "issue.review",
    "mcp": {
      "annotations": {
        "destructiveHint": false,
        "idempotentHint": false,
        "readOnlyHint": false,
        "title": "Record a structured reviewer decision with a required comment"
      },
      "capabilityId": "issue.review",
      "description": "Record a structured reviewer decision with a required comment. Mutating: yes. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: not required by this tool. Agent context: runtime env when available. Run attribution: attached from runtime env when available.",
      "inputSchema": {
        "additionalProperties": false,
        "anyOf": [
          {
            "required": [
              "comment"
            ]
          },
          {
            "required": [
              "body"
            ]
          }
        ],
        "properties": {
          "body": {
            "description": "Direct Markdown body.",
            "maxLength": 500000,
            "minLength": 1,
            "type": "string"
          },
          "comment": {
            "description": "Direct Markdown body.",
            "maxLength": 500000,
            "minLength": 1,
            "type": "string"
          },
          "decision": {
            "description": "Structured review decision.",
            "enum": [
              "approve",
              "request_changes",
              "needs_followup",
              "blocked"
            ],
            "maxLength": 30,
            "minLength": 1,
            "type": "string"
          },
          "issue": {
            "description": "Issue UUID, identifier, or short reference.",
            "maxLength": 200,
            "minLength": 1,
            "type": "string"
          }
        },
        "required": [
          "issue",
          "decision"
        ],
        "type": "object"
      },
      "name": "rudder_issue_review"
    }
  },
  {
    "api": {
      "transport": "cli-fallback"
    },
    "cli": {
      "attachesRunIdWhenAvailable": true,
      "category": "issue",
      "command": "rudder issue commit <issue> --sha <sha> --message <subject>",
      "contract": "agent-v1",
      "description": "Report a code commit created during issue work as structured issue activity.",
      "id": "issue.commit",
      "mutating": true,
      "requiresAgentId": false,
      "requiresOrgId": false,
      "requiresRunId": false
    },
    "id": "issue.commit",
    "mcp": {
      "annotations": {
        "destructiveHint": false,
        "idempotentHint": false,
        "readOnlyHint": false,
        "title": "Report a code commit created during issue work as structured issue activity"
      },
      "capabilityId": "issue.commit",
      "description": "Report a code commit created during issue work as structured issue activity. Mutating: yes. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: not required by this tool. Agent context: runtime env when available. Run attribution: attached from runtime env when available.",
      "inputSchema": {
        "additionalProperties": false,
        "properties": {
          "branch": {
            "description": "Git branch name.",
            "maxLength": 500,
            "minLength": 1,
            "type": "string"
          },
          "count": {
            "description": "Number of commits represented.",
            "maximum": 10000,
            "minimum": 1,
            "type": "number"
          },
          "issue": {
            "description": "Issue UUID, identifier, or short reference.",
            "maxLength": 200,
            "minLength": 1,
            "type": "string"
          },
          "message": {
            "description": "Commit subject or status message.",
            "maxLength": 2000,
            "minLength": 1,
            "type": "string"
          },
          "repoPath": {
            "description": "Repository path.",
            "maxLength": 8192,
            "minLength": 1,
            "type": "string"
          },
          "sha": {
            "description": "Git commit SHA.",
            "maxLength": 100,
            "minLength": 1,
            "type": "string"
          },
          "workspacePath": {
            "description": "Workspace path.",
            "maxLength": 8192,
            "minLength": 1,
            "type": "string"
          }
        },
        "required": [
          "issue",
          "sha",
          "message"
        ],
        "type": "object"
      },
      "name": "rudder_issue_commit"
    }
  },
  {
    "api": {
      "method": "PATCH",
      "pathTemplate": "/api/issues/{issue}",
      "transport": "direct"
    },
    "cli": {
      "attachesRunIdWhenAvailable": true,
      "category": "issue",
      "command": "rudder issue done <issue> --comment-file <path> [--image <path>]",
      "contract": "agent-v1",
      "description": "Mark an issue done with a required completion comment, optionally uploading images.",
      "id": "issue.done",
      "mutating": true,
      "requiresAgentId": false,
      "requiresOrgId": false,
      "requiresRunId": false
    },
    "id": "issue.done",
    "mcp": {
      "annotations": {
        "destructiveHint": true,
        "idempotentHint": false,
        "readOnlyHint": false,
        "title": "Mark an issue done with a required completion comment, optionally uploading images"
      },
      "capabilityId": "issue.done",
      "description": "Mark an issue done with a required completion comment, optionally uploading images. Mutating: yes. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: not required by this tool. Agent context: runtime env when available. Run attribution: attached from runtime env when available.",
      "inputSchema": {
        "additionalProperties": false,
        "anyOf": [
          {
            "required": [
              "comment"
            ]
          },
          {
            "required": [
              "body"
            ]
          }
        ],
        "properties": {
          "body": {
            "description": "Direct Markdown body.",
            "maxLength": 500000,
            "minLength": 1,
            "type": "string"
          },
          "comment": {
            "description": "Direct Markdown body.",
            "maxLength": 500000,
            "minLength": 1,
            "type": "string"
          },
          "images": {
            "description": "Local image paths to attach.",
            "items": {
              "description": "Local image paths to attach.",
              "maxLength": 8192,
              "minLength": 1,
              "type": "string"
            },
            "maxItems": 20,
            "type": "array"
          },
          "issue": {
            "description": "Issue UUID, identifier, or short reference.",
            "maxLength": 200,
            "minLength": 1,
            "type": "string"
          }
        },
        "required": [
          "issue"
        ],
        "type": "object"
      },
      "name": "rudder_issue_done"
    }
  },
  {
    "api": {
      "transport": "cli-fallback"
    },
    "cli": {
      "attachesRunIdWhenAvailable": true,
      "category": "issue",
      "command": "rudder issue block <issue> --comment-file <path> [--image <path>]",
      "contract": "agent-v1",
      "description": "Request human assistance after bounded recovery attempts; repeated matching claims are audited before the Issue becomes blocked.",
      "id": "issue.block",
      "mutating": true,
      "requiresAgentId": false,
      "requiresOrgId": false,
      "requiresRunId": false
    },
    "id": "issue.block",
    "mcp": {
      "annotations": {
        "destructiveHint": true,
        "idempotentHint": false,
        "readOnlyHint": false,
        "title": "Request human assistance after bounded recovery attempts"
      },
      "capabilityId": "issue.block",
      "description": "Request human assistance after bounded recovery attempts; repeated matching claims are audited before the Issue becomes blocked. Mutating: yes. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: not required by this tool. Agent context: runtime env when available. Run attribution: attached from runtime env when available.",
      "inputSchema": {
        "additionalProperties": false,
        "anyOf": [
          {
            "required": [
              "comment"
            ]
          },
          {
            "required": [
              "body"
            ]
          }
        ],
        "properties": {
          "body": {
            "description": "Direct Markdown body.",
            "maxLength": 500000,
            "minLength": 1,
            "type": "string"
          },
          "comment": {
            "description": "Direct Markdown body.",
            "maxLength": 500000,
            "minLength": 1,
            "type": "string"
          },
          "images": {
            "description": "Local image paths to attach.",
            "items": {
              "description": "Local image paths to attach.",
              "maxLength": 8192,
              "minLength": 1,
              "type": "string"
            },
            "maxItems": 20,
            "type": "array"
          },
          "issue": {
            "description": "Issue UUID, identifier, or short reference.",
            "maxLength": 200,
            "minLength": 1,
            "type": "string"
          }
        },
        "required": [
          "issue"
        ],
        "type": "object"
      },
      "name": "rudder_issue_block"
    }
  },
  {
    "api": {
      "transport": "cli-fallback"
    },
    "cli": {
      "attachesRunIdWhenAvailable": false,
      "category": "project",
      "command": "rudder project list --org-id <id>",
      "contract": "agent-v1",
      "description": "List projects in an organization.",
      "id": "project.list",
      "mutating": false,
      "requiresAgentId": false,
      "requiresOrgId": true,
      "requiresRunId": false
    },
    "id": "project.list",
    "mcp": {
      "annotations": {
        "destructiveHint": false,
        "idempotentHint": true,
        "readOnlyHint": true,
        "title": "List projects in an organization"
      },
      "capabilityId": "project.list",
      "description": "List projects in an organization. Mutating: no. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: required from runtime env. Agent context: runtime env when available. Run attribution: not attached.",
      "inputSchema": {
        "additionalProperties": false,
        "properties": {},
        "type": "object"
      },
      "name": "rudder_project_list"
    }
  },
  {
    "api": {
      "transport": "cli-fallback"
    },
    "cli": {
      "attachesRunIdWhenAvailable": false,
      "category": "project",
      "command": "rudder project get <project-id-or-shortname> [--org-id <id>]",
      "contract": "agent-v1",
      "description": "Read one project by ID or shortname.",
      "id": "project.get",
      "mutating": false,
      "requiresAgentId": false,
      "requiresOrgId": false,
      "requiresRunId": false
    },
    "id": "project.get",
    "mcp": {
      "annotations": {
        "destructiveHint": false,
        "idempotentHint": true,
        "readOnlyHint": true,
        "title": "Read one project by ID or shortname"
      },
      "capabilityId": "project.get",
      "description": "Read one project by ID or shortname. Mutating: no. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: not required by this tool. Agent context: runtime env when available. Run attribution: not attached.",
      "inputSchema": {
        "additionalProperties": false,
        "properties": {
          "project": {
            "description": "Project UUID or shortname.",
            "maxLength": 200,
            "minLength": 1,
            "type": "string"
          }
        },
        "required": [
          "project"
        ],
        "type": "object"
      },
      "name": "rudder_project_get"
    }
  },
  {
    "api": {
      "transport": "cli-fallback"
    },
    "cli": {
      "attachesRunIdWhenAvailable": true,
      "category": "project",
      "command": "rudder project create --org-id <id> --name <name>",
      "contract": "agent-v1",
      "description": "Create a project in the organization.",
      "id": "project.create",
      "mutating": true,
      "requiresAgentId": false,
      "requiresOrgId": true,
      "requiresRunId": false
    },
    "id": "project.create",
    "mcp": {
      "annotations": {
        "destructiveHint": false,
        "idempotentHint": false,
        "readOnlyHint": false,
        "title": "Create a project in the organization"
      },
      "capabilityId": "project.create",
      "description": "Create a project in the organization. Mutating: yes. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: required from runtime env. Agent context: runtime env when available. Run attribution: attached from runtime env when available.",
      "inputSchema": {
        "additionalProperties": false,
        "properties": {
          "color": {
            "description": "Display color.",
            "maxLength": 100,
            "minLength": 1,
            "type": "string"
          },
          "description": {
            "description": "Project description.",
            "maxLength": 500000,
            "minLength": 1,
            "type": "string"
          },
          "goalId": {
            "description": "Goal id or reference.",
            "maxLength": 200,
            "minLength": 1,
            "type": "string"
          },
          "goalIds": {
            "description": "Goal ids.",
            "items": {
              "description": "Goal ids.",
              "maxLength": 8192,
              "minLength": 1,
              "type": "string"
            },
            "maxItems": 100,
            "type": "array"
          },
          "leadAgentId": {
            "description": "Lead agent id or reference.",
            "maxLength": 200,
            "minLength": 1,
            "type": "string"
          },
          "name": {
            "description": "Project name.",
            "maxLength": 300,
            "minLength": 1,
            "type": "string"
          },
          "status": {
            "description": "Project status.",
            "maxLength": 100,
            "minLength": 1,
            "type": "string"
          },
          "targetDate": {
            "description": "Target date.",
            "maxLength": 100,
            "minLength": 1,
            "type": "string"
          }
        },
        "required": [
          "name"
        ],
        "type": "object"
      },
      "name": "rudder_project_create"
    }
  },
  {
    "api": {
      "method": "PATCH",
      "pathTemplate": "/api/projects/{project}",
      "transport": "direct"
    },
    "cli": {
      "attachesRunIdWhenAvailable": true,
      "category": "project",
      "command": "rudder project update <project-id-or-shortname> [--org-id <id>] [--idempotency-key <key>]",
      "contract": "agent-v1",
      "description": "Update mutable project fields such as name, description, status, goals, lead agent, target date, color, or archivedAt.",
      "id": "project.update",
      "mutating": true,
      "requiresAgentId": false,
      "requiresOrgId": false,
      "requiresRunId": false
    },
    "id": "project.update",
    "mcp": {
      "annotations": {
        "destructiveHint": false,
        "idempotentHint": false,
        "readOnlyHint": false,
        "title": "Update mutable project fields such as name, description, status, goals, lead agent, target date, color, or archivedAt"
      },
      "capabilityId": "project.update",
      "description": "Update mutable project fields such as name, description, status, goals, lead agent, target date, color, or archivedAt. Mutating: yes. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: not required by this tool. Agent context: runtime env when available. Run attribution: attached from runtime env when available.",
      "inputSchema": {
        "additionalProperties": false,
        "properties": {
          "archivedAt": {
            "description": "Archive timestamp.",
            "maxLength": 100,
            "minLength": 1,
            "type": "string"
          },
          "color": {
            "description": "Display color.",
            "maxLength": 100,
            "minLength": 1,
            "type": "string"
          },
          "description": {
            "description": "Project description.",
            "maxLength": 500000,
            "minLength": 1,
            "type": "string"
          },
          "goalId": {
            "description": "Goal id or reference.",
            "maxLength": 200,
            "minLength": 1,
            "type": "string"
          },
          "goalIds": {
            "description": "Goal ids.",
            "items": {
              "description": "Goal ids.",
              "maxLength": 8192,
              "minLength": 1,
              "type": "string"
            },
            "maxItems": 100,
            "type": "array"
          },
          "idempotencyKey": {
            "description": "Stable key for retrying project updates; required when changing Project-Goal links.",
            "maxLength": 256,
            "minLength": 1,
            "type": "string"
          },
          "leadAgentId": {
            "description": "Lead agent id or reference.",
            "maxLength": 200,
            "minLength": 1,
            "type": "string"
          },
          "name": {
            "description": "Project name.",
            "maxLength": 300,
            "minLength": 1,
            "type": "string"
          },
          "project": {
            "description": "Project UUID or shortname.",
            "maxLength": 200,
            "minLength": 1,
            "type": "string"
          },
          "status": {
            "description": "Project status.",
            "maxLength": 100,
            "minLength": 1,
            "type": "string"
          },
          "targetDate": {
            "description": "Target date.",
            "maxLength": 100,
            "minLength": 1,
            "type": "string"
          }
        },
        "required": [
          "project"
        ],
        "type": "object"
      },
      "name": "rudder_project_update"
    }
  },
  {
    "api": {
      "transport": "cli-fallback"
    },
    "cli": {
      "attachesRunIdWhenAvailable": false,
      "category": "user",
      "command": "rudder user activity --user me --since today --json",
      "contract": "agent-v1",
      "description": "Read a user-centered activity ledger with safe excerpts and provenance across chats, issue comments, approval comments, and user actor activity.",
      "id": "user.activity",
      "mutating": false,
      "requiresAgentId": false,
      "requiresOrgId": true,
      "requiresRunId": false
    },
    "id": "user.activity",
    "mcp": {
      "annotations": {
        "destructiveHint": false,
        "idempotentHint": true,
        "readOnlyHint": true,
        "title": "Read a user-centered activity ledger with safe excerpts and provenance across chats, issue comments, approval comments, and user actor activity"
      },
      "capabilityId": "user.activity",
      "description": "Read a user-centered activity ledger with safe excerpts and provenance across chats, issue comments, approval comments, and user actor activity. Mutating: no. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: required from runtime env. Agent context: runtime env when available. Run attribution: not attached.",
      "inputSchema": {
        "additionalProperties": false,
        "properties": {
          "cursor": {
            "description": "Opaque pagination cursor.",
            "maxLength": 2000,
            "minLength": 1,
            "type": "string"
          },
          "include": {
            "description": "Comma-separated optional sections.",
            "maxLength": 500,
            "minLength": 1,
            "type": "string"
          },
          "issueId": {
            "description": "Issue id.",
            "maxLength": 200,
            "minLength": 1,
            "type": "string"
          },
          "limit": {
            "description": "Page size.",
            "maximum": 100,
            "minimum": 1,
            "type": "number"
          },
          "projectId": {
            "description": "Project id.",
            "maxLength": 200,
            "minLength": 1,
            "type": "string"
          },
          "relatedAgentId": {
            "description": "Related agent id.",
            "maxLength": 200,
            "minLength": 1,
            "type": "string"
          },
          "since": {
            "description": "Activity start timestamp.",
            "maxLength": 100,
            "minLength": 1,
            "type": "string"
          },
          "until": {
            "description": "Activity end timestamp.",
            "maxLength": 100,
            "minLength": 1,
            "type": "string"
          },
          "user": {
            "description": "User id, reference, or self.",
            "maxLength": 200,
            "minLength": 1,
            "type": "string"
          }
        },
        "type": "object"
      },
      "name": "rudder_user_activity"
    }
  },
  {
    "api": {
      "transport": "cli-fallback"
    },
    "cli": {
      "attachesRunIdWhenAvailable": false,
      "category": "library",
      "command": "rudder library file list [directory]",
      "contract": "agent-v1",
      "description": "List Library files and folders; file rows include `libraryEntryId` when a strong reference can be generated.",
      "id": "library.file.list",
      "mutating": false,
      "requiresAgentId": false,
      "requiresOrgId": true,
      "requiresRunId": false
    },
    "id": "library.file.list",
    "mcp": {
      "annotations": {
        "destructiveHint": false,
        "idempotentHint": true,
        "readOnlyHint": true,
        "title": "List Library files and folders"
      },
      "capabilityId": "library.file.list",
      "description": "List Library files and folders; file rows include `libraryEntryId` when a strong reference can be generated. Mutating: no. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: required from runtime env. Agent context: runtime env when available. Run attribution: not attached.",
      "inputSchema": {
        "additionalProperties": false,
        "properties": {
          "directory": {
            "description": "Library-relative directory path.",
            "maxLength": 8192,
            "minLength": 1,
            "type": "string"
          },
          "path": {
            "description": "Compatibility alias for directory.",
            "maxLength": 8192,
            "minLength": 1,
            "type": "string"
          }
        },
        "type": "object"
      },
      "name": "rudder_library_file_list"
    }
  },
  {
    "api": {
      "transport": "cli-fallback"
    },
    "cli": {
      "attachesRunIdWhenAvailable": false,
      "category": "library",
      "command": "rudder library file get <path>",
      "contract": "agent-v1",
      "description": "Fallback read when local filesystem access is unavailable; JSON includes `mentionHref` and `markdownLink`.",
      "id": "library.file.get",
      "mutating": false,
      "requiresAgentId": false,
      "requiresOrgId": true,
      "requiresRunId": false
    },
    "id": "library.file.get",
    "mcp": {
      "annotations": {
        "destructiveHint": false,
        "idempotentHint": true,
        "readOnlyHint": true,
        "title": "Fallback read when local filesystem access is unavailable"
      },
      "capabilityId": "library.file.get",
      "description": "Fallback read when local filesystem access is unavailable; JSON includes `mentionHref` and `markdownLink`. Mutating: no. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: required from runtime env. Agent context: runtime env when available. Run attribution: not attached.",
      "inputSchema": {
        "additionalProperties": false,
        "properties": {
          "path": {
            "description": "Library-relative file path.",
            "maxLength": 8192,
            "minLength": 1,
            "type": "string"
          }
        },
        "required": [
          "path"
        ],
        "type": "object"
      },
      "name": "rudder_library_file_get"
    }
  }
] as const;
