// Generated by scripts/generate-rudder-mcp-tool-descriptors.ts. Do not edit by hand.
export const GENERATED_RUDDER_MCP_TOOL_DESCRIPTORS_003 = [
  {
    "capabilityId": "browser.screenshot",
    "name": "rudder_browser_screenshot",
    "description": "Capture a screenshot of a run-owned Rudder Browser tab.",
    "semanticDescription": "Capture a screenshot of a run-owned Rudder Browser tab. Mutating: no. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: required from runtime env. Agent context: required from runtime env. Run attribution: not attached.",
    "annotations": {
      "destructiveHint": false,
      "idempotentHint": true,
      "readOnlyHint": true,
      "title": "Capture a screenshot of a run-owned Rudder Browser tab"
    },
    "mutating": false,
    "requiresOrgId": true,
    "requiresAgentId": true,
    "attachesRunIdWhenAvailable": false,
    "inputSchema": {
      "additionalProperties": false,
      "properties": {
        "clip": {
          "additionalProperties": false,
          "properties": {
            "height": {
              "description": "Clip height.",
              "minimum": 1,
              "type": "number"
            },
            "width": {
              "description": "Clip width.",
              "minimum": 1,
              "type": "number"
            },
            "x": {
              "description": "Clip X coordinate.",
              "type": "number"
            },
            "y": {
              "description": "Clip Y coordinate.",
              "type": "number"
            }
          },
          "required": [
            "x",
            "y",
            "width",
            "height"
          ],
          "type": "object"
        },
        "format": {
          "description": "Image format.",
          "enum": [
            "png",
            "jpeg"
          ],
          "type": "string"
        },
        "fullPage": {
          "description": "Capture the full scrollable page.",
          "type": "boolean"
        },
        "locator": {
          "additionalProperties": false,
          "properties": {
            "and": {
              "additionalProperties": false,
              "properties": {
                "exact": {
                  "description": "Require an exact text or attribute match.",
                  "type": "boolean"
                },
                "name": {
                  "description": "Accessible name used with the role strategy.",
                  "maxLength": 2000,
                  "type": "string"
                },
                "strategy": {
                  "description": "Locator strategy.",
                  "enum": [
                    "css",
                    "testId",
                    "href",
                    "role",
                    "label",
                    "placeholder",
                    "text"
                  ],
                  "type": "string"
                },
                "value": {
                  "description": "Selector, role, label, placeholder, href, test id, or text value.",
                  "maxLength": 2000,
                  "minLength": 1,
                  "type": "string"
                }
              },
              "required": [
                "strategy",
                "value"
              ],
              "type": "object"
            },
            "exact": {
              "description": "Require an exact text or attribute match.",
              "type": "boolean"
            },
            "filter": {
              "additionalProperties": false,
              "properties": {
                "has": {
                  "additionalProperties": false,
                  "properties": {
                    "exact": {
                      "description": "Require an exact text or attribute match.",
                      "type": "boolean"
                    },
                    "name": {
                      "description": "Accessible name used with the role strategy.",
                      "maxLength": 2000,
                      "type": "string"
                    },
                    "strategy": {
                      "description": "Locator strategy.",
                      "enum": [
                        "css",
                        "testId",
                        "href",
                        "role",
                        "label",
                        "placeholder",
                        "text"
                      ],
                      "type": "string"
                    },
                    "value": {
                      "description": "Selector, role, label, placeholder, href, test id, or text value.",
                      "maxLength": 2000,
                      "minLength": 1,
                      "type": "string"
                    }
                  },
                  "required": [
                    "strategy",
                    "value"
                  ],
                  "type": "object"
                },
                "hasNot": {
                  "additionalProperties": false,
                  "properties": {
                    "exact": {
                      "description": "Require an exact text or attribute match.",
                      "type": "boolean"
                    },
                    "name": {
                      "description": "Accessible name used with the role strategy.",
                      "maxLength": 2000,
                      "type": "string"
                    },
                    "strategy": {
                      "description": "Locator strategy.",
                      "enum": [
                        "css",
                        "testId",
                        "href",
                        "role",
                        "label",
                        "placeholder",
                        "text"
                      ],
                      "type": "string"
                    },
                    "value": {
                      "description": "Selector, role, label, placeholder, href, test id, or text value.",
                      "maxLength": 2000,
                      "minLength": 1,
                      "type": "string"
                    }
                  },
                  "required": [
                    "strategy",
                    "value"
                  ],
                  "type": "object"
                },
                "hasNotText": {
                  "description": "Excluded descendant text.",
                  "maxLength": 2000,
                  "type": "string"
                },
                "hasText": {
                  "description": "Required descendant text.",
                  "maxLength": 2000,
                  "type": "string"
                },
                "visible": {
                  "description": "Filter by current visibility.",
                  "type": "boolean"
                }
              },
              "type": "object"
            },
            "frame": {
              "items": {
                "description": "CSS iframe selector.",
                "maxLength": 1000,
                "minLength": 1,
                "type": "string"
              },
              "maxItems": 8,
              "type": "array"
            },
            "index": {
              "description": "Zero-based locator match index.",
              "maximum": 499,
              "minimum": 0,
              "type": "number"
            },
            "name": {
              "description": "Accessible name used with the role strategy.",
              "maxLength": 2000,
              "type": "string"
            },
            "or": {
              "additionalProperties": false,
              "properties": {
                "exact": {
                  "description": "Require an exact text or attribute match.",
                  "type": "boolean"
                },
                "name": {
                  "description": "Accessible name used with the role strategy.",
                  "maxLength": 2000,
                  "type": "string"
                },
                "strategy": {
                  "description": "Locator strategy.",
                  "enum": [
                    "css",
                    "testId",
                    "href",
                    "role",
                    "label",
                    "placeholder",
                    "text"
                  ],
                  "type": "string"
                },
                "value": {
                  "description": "Selector, role, label, placeholder, href, test id, or text value.",
                  "maxLength": 2000,
                  "minLength": 1,
                  "type": "string"
                }
              },
              "required": [
                "strategy",
                "value"
              ],
              "type": "object"
            },
            "position": {
              "description": "Locator endpoint after an explicit count.",
              "enum": [
                "first",
                "last"
              ],
              "type": "string"
            },
            "scope": {
              "additionalProperties": false,
              "properties": {
                "and": {
                  "additionalProperties": false,
                  "properties": {
                    "exact": {
                      "description": "Require an exact text or attribute match.",
                      "type": "boolean"
                    },
                    "name": {
                      "description": "Accessible name used with the role strategy.",
                      "maxLength": 2000,
                      "type": "string"
                    },
                    "strategy": {
                      "description": "Locator strategy.",
                      "enum": [
                        "css",
                        "testId",
                        "href",
                        "role",
                        "label",
                        "placeholder",
                        "text"
                      ],
                      "type": "string"
                    },
                    "value": {
                      "description": "Selector, role, label, placeholder, href, test id, or text value.",
                      "maxLength": 2000,
                      "minLength": 1,
                      "type": "string"
                    }
                  },
                  "required": [
                    "strategy",
                    "value"
                  ],
                  "type": "object"
                },
                "exact": {
                  "description": "Require an exact text or attribute match.",
                  "type": "boolean"
                },
                "filter": {
                  "additionalProperties": false,
                  "properties": {
                    "has": {
                      "additionalProperties": false,
                      "properties": {
                        "exact": {
                          "description": "Require an exact text or attribute match.",
                          "type": "boolean"
                        },
                        "name": {
                          "description": "Accessible name used with the role strategy.",
                          "maxLength": 2000,
                          "type": "string"
                        },
                        "strategy": {
                          "description": "Locator strategy.",
                          "enum": [
                            "css",
                            "testId",
                            "href",
                            "role",
                            "label",
                            "placeholder",
                            "text"
                          ],
                          "type": "string"
                        },
                        "value": {
                          "description": "Selector, role, label, placeholder, href, test id, or text value.",
                          "maxLength": 2000,
                          "minLength": 1,
                          "type": "string"
                        }
                      },
                      "required": [
                        "strategy",
                        "value"
                      ],
                      "type": "object"
                    },
                    "hasNot": {
                      "additionalProperties": false,
                      "properties": {
                        "exact": {
                          "description": "Require an exact text or attribute match.",
                          "type": "boolean"
                        },
                        "name": {
                          "description": "Accessible name used with the role strategy.",
                          "maxLength": 2000,
                          "type": "string"
                        },
                        "strategy": {
                          "description": "Locator strategy.",
                          "enum": [
                            "css",
                            "testId",
                            "href",
                            "role",
                            "label",
                            "placeholder",
                            "text"
                          ],
                          "type": "string"
                        },
                        "value": {
                          "description": "Selector, role, label, placeholder, href, test id, or text value.",
                          "maxLength": 2000,
                          "minLength": 1,
                          "type": "string"
                        }
                      },
                      "required": [
                        "strategy",
                        "value"
                      ],
                      "type": "object"
                    },
                    "hasNotText": {
                      "description": "Excluded descendant text.",
                      "maxLength": 2000,
                      "type": "string"
                    },
                    "hasText": {
                      "description": "Required descendant text.",
                      "maxLength": 2000,
                      "type": "string"
                    },
                    "visible": {
                      "description": "Filter by current visibility.",
                      "type": "boolean"
                    }
                  },
                  "type": "object"
                },
                "index": {
                  "description": "Zero-based locator match index.",
                  "maximum": 499,
                  "minimum": 0,
                  "type": "number"
                },
                "name": {
                  "description": "Accessible name used with the role strategy.",
                  "maxLength": 2000,
                  "type": "string"
                },
                "or": {
                  "additionalProperties": false,
                  "properties": {
                    "exact": {
                      "description": "Require an exact text or attribute match.",
                      "type": "boolean"
                    },
                    "name": {
                      "description": "Accessible name used with the role strategy.",
                      "maxLength": 2000,
                      "type": "string"
                    },
                    "strategy": {
                      "description": "Locator strategy.",
                      "enum": [
                        "css",
                        "testId",
                        "href",
                        "role",
                        "label",
                        "placeholder",
                        "text"
                      ],
                      "type": "string"
                    },
                    "value": {
                      "description": "Selector, role, label, placeholder, href, test id, or text value.",
                      "maxLength": 2000,
                      "minLength": 1,
                      "type": "string"
                    }
                  },
                  "required": [
                    "strategy",
                    "value"
                  ],
                  "type": "object"
                },
                "position": {
                  "description": "Locator endpoint after an explicit count.",
                  "enum": [
                    "first",
                    "last"
                  ],
                  "type": "string"
                },
                "strategy": {
                  "description": "Locator strategy.",
                  "enum": [
                    "css",
                    "testId",
                    "href",
                    "role",
                    "label",
                    "placeholder",
                    "text"
                  ],
                  "type": "string"
                },
                "value": {
                  "description": "Selector, role, label, placeholder, href, test id, or text value.",
                  "maxLength": 2000,
                  "minLength": 1,
                  "type": "string"
                }
              },
              "required": [
                "strategy",
                "value"
              ],
              "type": "object"
            },
            "strategy": {
              "description": "Locator strategy.",
              "enum": [
                "css",
                "testId",
                "href",
                "role",
                "label",
                "placeholder",
                "text"
              ],
              "type": "string"
            },
            "value": {
              "description": "Selector, role, label, placeholder, href, test id, or text value.",
              "maxLength": 2000,
              "minLength": 1,
              "type": "string"
            }
          },
          "required": [
            "strategy",
            "value"
          ],
          "type": "object"
        },
        "quality": {
          "description": "JPEG quality.",
          "maximum": 100,
          "minimum": 1,
          "type": "number"
        },
        "tabId": {
          "description": "Run-owned Rudder Browser tab id.",
          "maxLength": 160,
          "minLength": 1,
          "type": "string"
        }
      },
      "required": [
        "tabId"
      ],
      "type": "object"
    }
  },
  {
    "capabilityId": "browser.close",
    "name": "rudder_browser_close",
    "description": "Close a run-owned Rudder Browser tab.",
    "semanticDescription": "Close a run-owned Rudder Browser tab. Mutating: yes. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: required from runtime env. Agent context: required from runtime env. Run attribution: attached from runtime env when available.",
    "annotations": {
      "destructiveHint": false,
      "idempotentHint": true,
      "readOnlyHint": false,
      "title": "Close a run-owned Rudder Browser tab"
    },
    "mutating": true,
    "requiresOrgId": true,
    "requiresAgentId": true,
    "attachesRunIdWhenAvailable": true,
    "inputSchema": {
      "additionalProperties": false,
      "properties": {
        "tabId": {
          "description": "Run-owned Rudder Browser tab id.",
          "maxLength": 160,
          "minLength": 1,
          "type": "string"
        }
      },
      "required": [
        "tabId"
      ],
      "type": "object"
    }
  },
  {
    "capabilityId": "automation.list",
    "name": "rudder_automation_list",
    "description": "List automations for an organization with compact local filters.",
    "semanticDescription": "List automations for an organization with compact local filters. Mutating: no. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: required from runtime env. Agent context: runtime env when available. Run attribution: not attached.",
    "annotations": {
      "destructiveHint": false,
      "idempotentHint": true,
      "readOnlyHint": true,
      "title": "List automations for an organization with compact local filters"
    },
    "mutating": false,
    "requiresOrgId": true,
    "requiresAgentId": false,
    "attachesRunIdWhenAvailable": false,
    "inputSchema": {
      "additionalProperties": false,
      "properties": {
        "assigneeAgentId": {
          "description": "Assignee agent id.",
          "maxLength": 200,
          "minLength": 1,
          "type": "string"
        },
        "outputMode": {
          "description": "Output mode filter.",
          "maxLength": 100,
          "minLength": 1,
          "type": "string"
        },
        "projectId": {
          "description": "Project id.",
          "maxLength": 200,
          "minLength": 1,
          "type": "string"
        },
        "status": {
          "description": "Automation status filter.",
          "maxLength": 100,
          "minLength": 1,
          "type": "string"
        }
      },
      "type": "object"
    }
  },
  {
    "capabilityId": "automation.get",
    "name": "rudder_automation_get",
    "description": "Read one automation detail including triggers and recent runs.",
    "semanticDescription": "Read one automation detail including triggers and recent runs. Mutating: no. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: not required by this tool. Agent context: runtime env when available. Run attribution: not attached.",
    "annotations": {
      "destructiveHint": false,
      "idempotentHint": true,
      "readOnlyHint": true,
      "title": "Read one automation detail including triggers and recent runs"
    },
    "mutating": false,
    "requiresOrgId": false,
    "requiresAgentId": false,
    "attachesRunIdWhenAvailable": false,
    "inputSchema": {
      "additionalProperties": false,
      "properties": {
        "automation": {
          "description": "Automation UUID or short reference.",
          "maxLength": 200,
          "minLength": 1,
          "type": "string"
        }
      },
      "required": [
        "automation"
      ],
      "type": "object"
    }
  },
  {
    "capabilityId": "automation.runs",
    "name": "rudder_automation_runs",
    "description": "List recent runs for one automation.",
    "semanticDescription": "List recent runs for one automation. Mutating: no. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: not required by this tool. Agent context: runtime env when available. Run attribution: not attached.",
    "annotations": {
      "destructiveHint": false,
      "idempotentHint": true,
      "readOnlyHint": true,
      "title": "List recent runs for one automation"
    },
    "mutating": false,
    "requiresOrgId": false,
    "requiresAgentId": false,
    "attachesRunIdWhenAvailable": false,
    "inputSchema": {
      "additionalProperties": false,
      "properties": {
        "automation": {
          "description": "Automation UUID or short reference.",
          "maxLength": 200,
          "minLength": 1,
          "type": "string"
        },
        "limit": {
          "description": "Maximum run rows.",
          "maximum": 100,
          "minimum": 1,
          "type": "number"
        }
      },
      "required": [
        "automation"
      ],
      "type": "object"
    }
  },
  {
    "capabilityId": "automation.triggers.list",
    "name": "rudder_automation_triggers_list",
    "description": "List triggers configured for one automation.",
    "semanticDescription": "List triggers configured for one automation. Mutating: no. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: not required by this tool. Agent context: runtime env when available. Run attribution: not attached.",
    "annotations": {
      "destructiveHint": false,
      "idempotentHint": true,
      "readOnlyHint": true,
      "title": "List triggers configured for one automation"
    },
    "mutating": false,
    "requiresOrgId": false,
    "requiresAgentId": false,
    "attachesRunIdWhenAvailable": false,
    "inputSchema": {
      "additionalProperties": false,
      "properties": {
        "automation": {
          "description": "Automation UUID or short reference.",
          "maxLength": 200,
          "minLength": 1,
          "type": "string"
        }
      },
      "required": [
        "automation"
      ],
      "type": "object"
    }
  },
  {
    "capabilityId": "automation.triggers.create",
    "name": "rudder_automation_triggers_create",
    "description": "Create a schedule, webhook, or API trigger through the governed automation API.",
    "semanticDescription": "Create a schedule, webhook, or API trigger through the governed automation API. Mutating: yes. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: not required by this tool. Agent context: runtime env when available. Run attribution: attached from runtime env when available.",
    "annotations": {
      "destructiveHint": false,
      "idempotentHint": false,
      "readOnlyHint": false,
      "title": "Create a schedule, webhook, or API trigger through the governed automation API"
    },
    "mutating": true,
    "requiresOrgId": false,
    "requiresAgentId": false,
    "attachesRunIdWhenAvailable": true,
    "inputSchema": {
      "additionalProperties": false,
      "properties": {
        "automation": {
          "description": "Automation UUID or short reference.",
          "maxLength": 200,
          "minLength": 1,
          "type": "string"
        },
        "cronExpression": {
          "description": "Cron expression.",
          "maxLength": 500,
          "minLength": 1,
          "type": "string"
        },
        "disabled": {
          "description": "Create the trigger disabled.",
          "type": "boolean"
        },
        "enabled": {
          "description": "Create the trigger enabled.",
          "type": "boolean"
        },
        "kind": {
          "description": "Trigger kind.",
          "maxLength": 100,
          "minLength": 1,
          "type": "string"
        },
        "label": {
          "description": "Trigger label.",
          "maxLength": 300,
          "minLength": 1,
          "type": "string"
        },
        "payload": {
          "description": "JSON payload object or JSON string.",
          "type": [
            "object",
            "string"
          ]
        },
        "replayWindowSec": {
          "description": "Webhook replay window in seconds.",
          "maxLength": 30,
          "minLength": 1,
          "type": "string"
        },
        "signingMode": {
          "description": "Webhook signing mode.",
          "maxLength": 100,
          "minLength": 1,
          "type": "string"
        },
        "timezone": {
          "description": "IANA timezone.",
          "maxLength": 200,
          "minLength": 1,
          "type": "string"
        }
      },
      "required": [
        "automation"
      ],
      "type": "object"
    }
  },
  {
    "capabilityId": "automation.triggers.update",
    "name": "rudder_automation_triggers_update",
    "description": "Update an automation trigger through the governed automation API.",
    "semanticDescription": "Update an automation trigger through the governed automation API. Mutating: yes. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: not required by this tool. Agent context: runtime env when available. Run attribution: attached from runtime env when available.",
    "annotations": {
      "destructiveHint": false,
      "idempotentHint": false,
      "readOnlyHint": false,
      "title": "Update an automation trigger through the governed automation API"
    },
    "mutating": true,
    "requiresOrgId": false,
    "requiresAgentId": false,
    "attachesRunIdWhenAvailable": true,
    "inputSchema": {
      "additionalProperties": false,
      "properties": {
        "cronExpression": {
          "description": "Cron expression.",
          "maxLength": 500,
          "minLength": 1,
          "type": "string"
        },
        "disabled": {
          "description": "Disable the trigger.",
          "type": "boolean"
        },
        "enabled": {
          "description": "Enable the trigger.",
          "type": "boolean"
        },
        "label": {
          "description": "Trigger label.",
          "maxLength": 300,
          "minLength": 1,
          "type": "string"
        },
        "payload": {
          "description": "JSON payload object or JSON string.",
          "type": [
            "object",
            "string"
          ]
        },
        "replayWindowSec": {
          "description": "Webhook replay window in seconds.",
          "maxLength": 30,
          "minLength": 1,
          "type": "string"
        },
        "signingMode": {
          "description": "Webhook signing mode.",
          "maxLength": 100,
          "minLength": 1,
          "type": "string"
        },
        "timezone": {
          "description": "IANA timezone.",
          "maxLength": 200,
          "minLength": 1,
          "type": "string"
        },
        "trigger": {
          "description": "Automation trigger UUID or short reference.",
          "maxLength": 200,
          "minLength": 1,
          "type": "string"
        }
      },
      "required": [
        "trigger"
      ],
      "type": "object"
    }
  },
  {
    "capabilityId": "automation.triggers.delete",
    "name": "rudder_automation_triggers_delete",
    "description": "Delete an automation trigger through the governed automation API.",
    "semanticDescription": "Delete an automation trigger through the governed automation API. Mutating: yes. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: not required by this tool. Agent context: runtime env when available. Run attribution: attached from runtime env when available.",
    "annotations": {
      "destructiveHint": true,
      "idempotentHint": false,
      "readOnlyHint": false,
      "title": "Delete an automation trigger through the governed automation API"
    },
    "mutating": true,
    "requiresOrgId": false,
    "requiresAgentId": false,
    "attachesRunIdWhenAvailable": true,
    "inputSchema": {
      "additionalProperties": false,
      "properties": {
        "trigger": {
          "description": "Automation trigger UUID or short reference.",
          "maxLength": 200,
          "minLength": 1,
          "type": "string"
        }
      },
      "required": [
        "trigger"
      ],
      "type": "object"
    }
  },
  {
    "capabilityId": "automation.triggers.rotate-secret",
    "name": "rudder_automation_triggers_rotate_secret",
    "description": "Rotate an automation webhook trigger secret through the governed automation API.",
    "semanticDescription": "Rotate an automation webhook trigger secret through the governed automation API. Mutating: yes. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: not required by this tool. Agent context: runtime env when available. Run attribution: attached from runtime env when available.",
    "annotations": {
      "destructiveHint": true,
      "idempotentHint": false,
      "readOnlyHint": false,
      "title": "Rotate an automation webhook trigger secret through the governed automation API"
    },
    "mutating": true,
    "requiresOrgId": false,
    "requiresAgentId": false,
    "attachesRunIdWhenAvailable": true,
    "inputSchema": {
      "additionalProperties": false,
      "properties": {
        "trigger": {
          "description": "Automation trigger UUID or short reference.",
          "maxLength": 200,
          "minLength": 1,
          "type": "string"
        }
      },
      "required": [
        "trigger"
      ],
      "type": "object"
    }
  },
  {
    "capabilityId": "automation.create",
    "name": "rudder_automation_create",
    "description": "Create an automation through the governed automation API.",
    "semanticDescription": "Create an automation through the governed automation API. Mutating: yes. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: required from runtime env. Agent context: runtime env when available. Run attribution: attached from runtime env when available.",
    "annotations": {
      "destructiveHint": false,
      "idempotentHint": false,
      "readOnlyHint": false,
      "title": "Create an automation through the governed automation API"
    },
    "mutating": true,
    "requiresOrgId": true,
    "requiresAgentId": false,
    "attachesRunIdWhenAvailable": true,
    "inputSchema": {
      "additionalProperties": false,
      "properties": {
        "assigneeAgentId": {
          "description": "Assignee agent id.",
          "maxLength": 200,
          "minLength": 1,
          "type": "string"
        },
        "catchUpPolicy": {
          "description": "Catch-up policy.",
          "maxLength": 100,
          "minLength": 1,
          "type": "string"
        },
        "concurrencyPolicy": {
          "description": "Concurrency policy.",
          "maxLength": 100,
          "minLength": 1,
          "type": "string"
        },
        "description": {
          "description": "Compatibility alias for instructions.",
          "maxLength": 500000,
          "minLength": 1,
          "type": "string"
        },
        "goalId": {
          "description": "Goal id.",
          "maxLength": 200,
          "minLength": 1,
          "type": "string"
        },
        "instructions": {
          "description": "Automation instructions.",
          "maxLength": 500000,
          "minLength": 1,
          "type": "string"
        },
        "notifyOnIssueCreated": {
          "description": "Notify when an issue is created.",
          "type": "boolean"
        },
        "outputMode": {
          "description": "Automation output mode.",
          "maxLength": 100,
          "minLength": 1,
          "type": "string"
        },
        "parentIssueId": {
          "description": "Parent issue id.",
          "maxLength": 200,
          "minLength": 1,
          "type": "string"
        },
        "payload": {
          "description": "JSON payload object or JSON string.",
          "type": [
            "object",
            "string"
          ]
        },
        "priority": {
          "description": "Issue priority.",
          "maxLength": 100,
          "minLength": 1,
          "type": "string"
        },
        "projectId": {
          "description": "Project id.",
          "maxLength": 200,
          "minLength": 1,
          "type": "string"
        },
        "status": {
          "description": "Automation status.",
          "maxLength": 100,
          "minLength": 1,
          "type": "string"
        },
        "title": {
          "description": "Automation title.",
          "maxLength": 500,
          "minLength": 1,
          "type": "string"
        }
      },
      "type": "object"
    }
  },
  {
    "capabilityId": "automation.update",
    "name": "rudder_automation_update",
    "description": "Update automation fields through the governed automation API.",
    "semanticDescription": "Update automation fields through the governed automation API. Mutating: yes. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: not required by this tool. Agent context: runtime env when available. Run attribution: attached from runtime env when available.",
    "annotations": {
      "destructiveHint": false,
      "idempotentHint": false,
      "readOnlyHint": false,
      "title": "Update automation fields through the governed automation API"
    },
    "mutating": true,
    "requiresOrgId": false,
    "requiresAgentId": false,
    "attachesRunIdWhenAvailable": true,
    "inputSchema": {
      "additionalProperties": false,
      "properties": {
        "assigneeAgentId": {
          "description": "Assignee agent id.",
          "maxLength": 200,
          "minLength": 1,
          "type": "string"
        },
        "automation": {
          "description": "Automation UUID or short reference.",
          "maxLength": 200,
          "minLength": 1,
          "type": "string"
        },
        "catchUpPolicy": {
          "description": "Catch-up policy.",
          "maxLength": 100,
          "minLength": 1,
          "type": "string"
        },
        "concurrencyPolicy": {
          "description": "Concurrency policy.",
          "maxLength": 100,
          "minLength": 1,
          "type": "string"
        },
        "description": {
          "description": "Compatibility alias for instructions.",
          "maxLength": 500000,
          "minLength": 1,
          "type": "string"
        },
        "goalId": {
          "description": "Goal id.",
          "maxLength": 200,
          "minLength": 1,
          "type": "string"
        },
        "instructions": {
          "description": "Automation instructions.",
          "maxLength": 500000,
          "minLength": 1,
          "type": "string"
        },
        "notifyOnIssueCreated": {
          "description": "Notify when an issue is created.",
          "type": "boolean"
        },
        "outputMode": {
          "description": "Automation output mode.",
          "maxLength": 100,
          "minLength": 1,
          "type": "string"
        },
        "parentIssueId": {
          "description": "Parent issue id.",
          "maxLength": 200,
          "minLength": 1,
          "type": "string"
        },
        "payload": {
          "description": "JSON payload object or JSON string.",
          "type": [
            "object",
            "string"
          ]
        },
        "priority": {
          "description": "Issue priority.",
          "maxLength": 100,
          "minLength": 1,
          "type": "string"
        },
        "projectId": {
          "description": "Project id.",
          "maxLength": 200,
          "minLength": 1,
          "type": "string"
        },
        "status": {
          "description": "Automation status.",
          "maxLength": 100,
          "minLength": 1,
          "type": "string"
        },
        "title": {
          "description": "Automation title.",
          "maxLength": 500,
          "minLength": 1,
          "type": "string"
        }
      },
      "required": [
        "automation"
      ],
      "type": "object"
    }
  },
  {
    "capabilityId": "automation.enable",
    "name": "rudder_automation_enable",
    "description": "Enable an automation by setting status to active.",
    "semanticDescription": "Enable an automation by setting status to active. Mutating: yes. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: not required by this tool. Agent context: runtime env when available. Run attribution: attached from runtime env when available.",
    "annotations": {
      "destructiveHint": false,
      "idempotentHint": false,
      "readOnlyHint": false,
      "title": "Enable an automation by setting status to active"
    },
    "mutating": true,
    "requiresOrgId": false,
    "requiresAgentId": false,
    "attachesRunIdWhenAvailable": true,
    "inputSchema": {
      "additionalProperties": false,
      "properties": {
        "automation": {
          "description": "Automation UUID or short reference.",
          "maxLength": 200,
          "minLength": 1,
          "type": "string"
        }
      },
      "required": [
        "automation"
      ],
      "type": "object"
    }
  }
] as const;
