// Generated by scripts/generate-rudder-mcp-tool-descriptors.ts. Do not edit by hand.
export const GENERATED_RUDDER_AGENT_CONTRACT_CAPABILITIES_006 = [
  {
    "api": {
      "transport": "cli-fallback"
    },
    "cli": {
      "attachesRunIdWhenAvailable": true,
      "category": "automation",
      "command": "rudder automation update <automation-id>",
      "contract": "agent-v1",
      "description": "Update automation fields through the governed automation API.",
      "id": "automation.update",
      "mutating": true,
      "requiresAgentId": false,
      "requiresOrgId": false,
      "requiresRunId": false
    },
    "id": "automation.update",
    "mcp": {
      "annotations": {
        "destructiveHint": false,
        "idempotentHint": false,
        "readOnlyHint": false,
        "title": "Update automation fields through the governed automation API"
      },
      "capabilityId": "automation.update",
      "description": "Update automation fields through the governed automation API. Mutating: yes. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: not required by this tool. Agent context: runtime env when available. Run attribution: attached from runtime env when available.",
      "inputSchema": {
        "additionalProperties": false,
        "properties": {
          "assigneeAgentId": {
            "description": "Assignee agent id.",
            "maxLength": 200,
            "minLength": 1,
            "type": "string"
          },
          "automation": {
            "description": "Automation UUID or short reference.",
            "maxLength": 200,
            "minLength": 1,
            "type": "string"
          },
          "catchUpPolicy": {
            "description": "Catch-up policy.",
            "maxLength": 100,
            "minLength": 1,
            "type": "string"
          },
          "concurrencyPolicy": {
            "description": "Concurrency policy.",
            "maxLength": 100,
            "minLength": 1,
            "type": "string"
          },
          "description": {
            "description": "Compatibility alias for instructions.",
            "maxLength": 500000,
            "minLength": 1,
            "type": "string"
          },
          "goalId": {
            "description": "Goal id.",
            "maxLength": 200,
            "minLength": 1,
            "type": "string"
          },
          "instructions": {
            "description": "Automation instructions.",
            "maxLength": 500000,
            "minLength": 1,
            "type": "string"
          },
          "notifyOnIssueCreated": {
            "description": "Notify when an issue is created.",
            "type": "boolean"
          },
          "outputMode": {
            "description": "Automation output mode.",
            "maxLength": 100,
            "minLength": 1,
            "type": "string"
          },
          "parentIssueId": {
            "description": "Parent issue id.",
            "maxLength": 200,
            "minLength": 1,
            "type": "string"
          },
          "payload": {
            "description": "JSON payload object or JSON string.",
            "type": [
              "object",
              "string"
            ]
          },
          "priority": {
            "description": "Issue priority.",
            "maxLength": 100,
            "minLength": 1,
            "type": "string"
          },
          "projectId": {
            "description": "Project id.",
            "maxLength": 200,
            "minLength": 1,
            "type": "string"
          },
          "status": {
            "description": "Automation status.",
            "maxLength": 100,
            "minLength": 1,
            "type": "string"
          },
          "title": {
            "description": "Automation title.",
            "maxLength": 500,
            "minLength": 1,
            "type": "string"
          }
        },
        "required": [
          "automation"
        ],
        "type": "object"
      },
      "name": "rudder_automation_update"
    }
  },
  {
    "api": {
      "transport": "cli-fallback"
    },
    "cli": {
      "attachesRunIdWhenAvailable": true,
      "category": "automation",
      "command": "rudder automation enable <automation-id>",
      "contract": "agent-v1",
      "description": "Enable an automation by setting status to active.",
      "id": "automation.enable",
      "mutating": true,
      "requiresAgentId": false,
      "requiresOrgId": false,
      "requiresRunId": false
    },
    "id": "automation.enable",
    "mcp": {
      "annotations": {
        "destructiveHint": false,
        "idempotentHint": false,
        "readOnlyHint": false,
        "title": "Enable an automation by setting status to active"
      },
      "capabilityId": "automation.enable",
      "description": "Enable an automation by setting status to active. Mutating: yes. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: not required by this tool. Agent context: runtime env when available. Run attribution: attached from runtime env when available.",
      "inputSchema": {
        "additionalProperties": false,
        "properties": {
          "automation": {
            "description": "Automation UUID or short reference.",
            "maxLength": 200,
            "minLength": 1,
            "type": "string"
          }
        },
        "required": [
          "automation"
        ],
        "type": "object"
      },
      "name": "rudder_automation_enable"
    }
  },
  {
    "api": {
      "transport": "cli-fallback"
    },
    "cli": {
      "attachesRunIdWhenAvailable": true,
      "category": "automation",
      "command": "rudder automation disable <automation-id>",
      "contract": "agent-v1",
      "description": "Disable an automation by setting status to paused.",
      "id": "automation.disable",
      "mutating": true,
      "requiresAgentId": false,
      "requiresOrgId": false,
      "requiresRunId": false
    },
    "id": "automation.disable",
    "mcp": {
      "annotations": {
        "destructiveHint": true,
        "idempotentHint": false,
        "readOnlyHint": false,
        "title": "Disable an automation by setting status to paused"
      },
      "capabilityId": "automation.disable",
      "description": "Disable an automation by setting status to paused. Mutating: yes. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: not required by this tool. Agent context: runtime env when available. Run attribution: attached from runtime env when available.",
      "inputSchema": {
        "additionalProperties": false,
        "properties": {
          "automation": {
            "description": "Automation UUID or short reference.",
            "maxLength": 200,
            "minLength": 1,
            "type": "string"
          }
        },
        "required": [
          "automation"
        ],
        "type": "object"
      },
      "name": "rudder_automation_disable"
    }
  },
  {
    "api": {
      "transport": "cli-fallback"
    },
    "cli": {
      "attachesRunIdWhenAvailable": true,
      "category": "automation",
      "command": "rudder automation run <automation-id>",
      "contract": "agent-v1",
      "description": "Trigger a manual automation run.",
      "id": "automation.run",
      "mutating": true,
      "requiresAgentId": false,
      "requiresOrgId": false,
      "requiresRunId": false
    },
    "id": "automation.run",
    "mcp": {
      "annotations": {
        "destructiveHint": false,
        "idempotentHint": false,
        "readOnlyHint": false,
        "title": "Trigger a manual automation run"
      },
      "capabilityId": "automation.run",
      "description": "Trigger a manual automation run. Mutating: yes. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: not required by this tool. Agent context: runtime env when available. Run attribution: attached from runtime env when available.",
      "inputSchema": {
        "additionalProperties": false,
        "properties": {
          "automation": {
            "description": "Automation UUID or short reference.",
            "maxLength": 200,
            "minLength": 1,
            "type": "string"
          },
          "idempotencyKey": {
            "description": "Idempotency key.",
            "maxLength": 500,
            "minLength": 1,
            "type": "string"
          },
          "payload": {
            "description": "JSON payload object or JSON string.",
            "type": [
              "object",
              "string"
            ]
          },
          "source": {
            "description": "Invocation source.",
            "maxLength": 500,
            "minLength": 1,
            "type": "string"
          },
          "triggerId": {
            "description": "Trigger id.",
            "maxLength": 200,
            "minLength": 1,
            "type": "string"
          }
        },
        "required": [
          "automation"
        ],
        "type": "object"
      },
      "name": "rudder_automation_run"
    }
  },
  {
    "api": {
      "transport": "cli-fallback"
    },
    "cli": {
      "attachesRunIdWhenAvailable": false,
      "category": "chat",
      "command": "rudder chat list --org-id <id>",
      "contract": "agent-v1",
      "description": "List chat conversations without dumping full message history.",
      "id": "chat.list",
      "mutating": false,
      "requiresAgentId": false,
      "requiresOrgId": true,
      "requiresRunId": false
    },
    "id": "chat.list",
    "mcp": {
      "annotations": {
        "destructiveHint": false,
        "idempotentHint": true,
        "readOnlyHint": true,
        "title": "List chat conversations without dumping full message history"
      },
      "capabilityId": "chat.list",
      "description": "List chat conversations without dumping full message history. Mutating: no. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: required from runtime env. Agent context: runtime env when available. Run attribution: not attached.",
      "inputSchema": {
        "additionalProperties": false,
        "properties": {
          "limit": {
            "description": "Maximum chat rows.",
            "maximum": 100,
            "minimum": 1,
            "type": "number"
          },
          "query": {
            "description": "Optional chat query.",
            "maxLength": 2000,
            "minLength": 1,
            "type": "string"
          },
          "status": {
            "description": "Chat status filter.",
            "maxLength": 100,
            "minLength": 1,
            "type": "string"
          }
        },
        "type": "object"
      },
      "name": "rudder_chat_list"
    }
  },
  {
    "api": {
      "transport": "cli-fallback"
    },
    "cli": {
      "attachesRunIdWhenAvailable": false,
      "category": "chat",
      "command": "rudder chat search <query> --org-id <id>",
      "contract": "agent-v1",
      "description": "Search chats with bounded snippets and optional scope filtering.",
      "id": "chat.search",
      "mutating": false,
      "requiresAgentId": false,
      "requiresOrgId": true,
      "requiresRunId": false
    },
    "id": "chat.search",
    "mcp": {
      "annotations": {
        "destructiveHint": false,
        "idempotentHint": true,
        "readOnlyHint": true,
        "title": "Search chats with bounded snippets and optional scope filtering"
      },
      "capabilityId": "chat.search",
      "description": "Search chats with bounded snippets and optional scope filtering. Mutating: no. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: required from runtime env. Agent context: runtime env when available. Run attribution: not attached.",
      "inputSchema": {
        "additionalProperties": false,
        "properties": {
          "limit": {
            "description": "Maximum matches.",
            "maximum": 100,
            "minimum": 1,
            "type": "number"
          },
          "query": {
            "description": "Non-empty chat search query.",
            "maxLength": 2000,
            "minLength": 1,
            "type": "string"
          },
          "scope": {
            "description": "Search scope.",
            "maxLength": 100,
            "minLength": 1,
            "type": "string"
          },
          "snippetChars": {
            "description": "Maximum snippet characters.",
            "maximum": 10000,
            "minimum": 100,
            "type": "number"
          },
          "status": {
            "description": "Chat status filter.",
            "maxLength": 100,
            "minLength": 1,
            "type": "string"
          }
        },
        "required": [
          "query"
        ],
        "type": "object"
      },
      "name": "rudder_chat_search"
    }
  },
  {
    "api": {
      "transport": "cli-fallback"
    },
    "cli": {
      "attachesRunIdWhenAvailable": false,
      "category": "chat",
      "command": "rudder chat get <chat-id-or-cht-ref>",
      "contract": "agent-v1",
      "description": "Read one chat conversation record.",
      "id": "chat.get",
      "mutating": false,
      "requiresAgentId": false,
      "requiresOrgId": false,
      "requiresRunId": false
    },
    "id": "chat.get",
    "mcp": {
      "annotations": {
        "destructiveHint": false,
        "idempotentHint": true,
        "readOnlyHint": true,
        "title": "Read one chat conversation record"
      },
      "capabilityId": "chat.get",
      "description": "Read one chat conversation record. Mutating: no. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: not required by this tool. Agent context: runtime env when available. Run attribution: not attached.",
      "inputSchema": {
        "additionalProperties": false,
        "properties": {
          "chat": {
            "description": "Chat conversation UUID or short reference.",
            "maxLength": 200,
            "minLength": 1,
            "type": "string"
          }
        },
        "required": [
          "chat"
        ],
        "type": "object"
      },
      "name": "rudder_chat_get"
    }
  },
  {
    "api": {
      "transport": "cli-fallback"
    },
    "cli": {
      "attachesRunIdWhenAvailable": false,
      "category": "chat",
      "command": "rudder chat messages <chat-id-or-cht-ref> [--limit <n>] [--cursor <cursor>] [--include-transcript]",
      "contract": "agent-v1",
      "description": "Read bounded chat messages with page cursors; transcript output is omitted unless requested.",
      "id": "chat.messages",
      "mutating": false,
      "requiresAgentId": false,
      "requiresOrgId": false,
      "requiresRunId": false
    },
    "id": "chat.messages",
    "mcp": {
      "annotations": {
        "destructiveHint": false,
        "idempotentHint": true,
        "readOnlyHint": true,
        "title": "Read bounded chat messages with page cursors"
      },
      "capabilityId": "chat.messages",
      "description": "Read bounded chat messages with page cursors; transcript output is omitted unless requested. Mutating: no. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: not required by this tool. Agent context: runtime env when available. Run attribution: not attached.",
      "inputSchema": {
        "additionalProperties": false,
        "properties": {
          "chat": {
            "description": "Chat conversation UUID or short reference.",
            "maxLength": 200,
            "minLength": 1,
            "type": "string"
          },
          "cursor": {
            "description": "Opaque pagination cursor.",
            "maxLength": 2000,
            "minLength": 1,
            "type": "string"
          },
          "includeOutput": {
            "description": "Compatibility alias for includeTranscript.",
            "type": "boolean"
          },
          "includeTranscript": {
            "description": "Include bounded transcript data.",
            "type": "boolean"
          },
          "limit": {
            "description": "Maximum message rows.",
            "maximum": 100,
            "minimum": 1,
            "type": "number"
          },
          "maxOutputChars": {
            "description": "Maximum output characters per row.",
            "maximum": 20000,
            "minimum": 100,
            "type": "number"
          }
        },
        "required": [
          "chat"
        ],
        "type": "object"
      },
      "name": "rudder_chat_messages"
    }
  },
  {
    "api": {
      "transport": "cli-fallback"
    },
    "cli": {
      "attachesRunIdWhenAvailable": false,
      "category": "chat",
      "command": "rudder chat transcript <chat-id-or-cht-ref> [--limit <n>] [--cursor <cursor>] [--max-output-chars <n>]",
      "contract": "agent-v1",
      "description": "Read paginated chat messages with assistant transcript entries clipped in human output.",
      "id": "chat.transcript",
      "mutating": false,
      "requiresAgentId": false,
      "requiresOrgId": false,
      "requiresRunId": false
    },
    "id": "chat.transcript",
    "mcp": {
      "annotations": {
        "destructiveHint": false,
        "idempotentHint": true,
        "readOnlyHint": true,
        "title": "Read paginated chat messages with assistant transcript entries clipped in human output"
      },
      "capabilityId": "chat.transcript",
      "description": "Read paginated chat messages with assistant transcript entries clipped in human output. Mutating: no. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: not required by this tool. Agent context: runtime env when available. Run attribution: not attached.",
      "inputSchema": {
        "additionalProperties": false,
        "properties": {
          "chat": {
            "description": "Chat conversation UUID or short reference.",
            "maxLength": 200,
            "minLength": 1,
            "type": "string"
          },
          "cursor": {
            "description": "Opaque pagination cursor.",
            "maxLength": 2000,
            "minLength": 1,
            "type": "string"
          },
          "limit": {
            "description": "Maximum transcript rows.",
            "maximum": 100,
            "minimum": 1,
            "type": "number"
          },
          "maxOutputChars": {
            "description": "Maximum output characters per row.",
            "maximum": 20000,
            "minimum": 100,
            "type": "number"
          }
        },
        "required": [
          "chat"
        ],
        "type": "object"
      },
      "name": "rudder_chat_transcript"
    }
  },
  {
    "api": {
      "transport": "cli-fallback"
    },
    "cli": {
      "attachesRunIdWhenAvailable": false,
      "category": "chat",
      "command": "rudder chat read <chat-id-or-cht-ref> [--turn-limit <n>] [--cursor <cursor>] [--include-output]",
      "contract": "agent-v1",
      "description": "Read a bounded recent-message snapshot for one chat with page cursors.",
      "id": "chat.read",
      "mutating": false,
      "requiresAgentId": false,
      "requiresOrgId": false,
      "requiresRunId": false
    },
    "id": "chat.read",
    "mcp": {
      "annotations": {
        "destructiveHint": false,
        "idempotentHint": true,
        "readOnlyHint": true,
        "title": "Read a bounded recent-message snapshot for one chat with page cursors"
      },
      "capabilityId": "chat.read",
      "description": "Read a bounded recent-message snapshot for one chat with page cursors. Mutating: no. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: not required by this tool. Agent context: runtime env when available. Run attribution: not attached.",
      "inputSchema": {
        "additionalProperties": false,
        "properties": {
          "chat": {
            "description": "Chat conversation UUID or short reference.",
            "maxLength": 200,
            "minLength": 1,
            "type": "string"
          },
          "cursor": {
            "description": "Opaque pagination cursor.",
            "maxLength": 2000,
            "minLength": 1,
            "type": "string"
          },
          "includeOutput": {
            "description": "Compatibility alias for includeTranscript.",
            "type": "boolean"
          },
          "includeTranscript": {
            "description": "Include bounded transcript data.",
            "type": "boolean"
          },
          "limit": {
            "description": "Maximum message rows.",
            "maximum": 100,
            "minimum": 1,
            "type": "number"
          },
          "maxOutputChars": {
            "description": "Maximum output characters per row.",
            "maximum": 20000,
            "minimum": 100,
            "type": "number"
          },
          "turnLimit": {
            "description": "Maximum transcript turns.",
            "maximum": 100,
            "minimum": 1,
            "type": "number"
          }
        },
        "required": [
          "chat"
        ],
        "type": "object"
      },
      "name": "rudder_chat_read"
    }
  },
  {
    "api": {
      "transport": "cli-fallback"
    },
    "cli": {
      "attachesRunIdWhenAvailable": true,
      "category": "chat",
      "command": "rudder chat create --org-id <id> --body <text>",
      "contract": "agent-v1",
      "description": "Create a chat conversation with its first message.",
      "id": "chat.create",
      "mutating": true,
      "requiresAgentId": false,
      "requiresOrgId": true,
      "requiresRunId": false
    },
    "id": "chat.create",
    "mcp": {
      "annotations": {
        "destructiveHint": false,
        "idempotentHint": false,
        "readOnlyHint": false,
        "title": "Create a chat conversation with its first message"
      },
      "capabilityId": "chat.create",
      "description": "Create a chat conversation with its first message. Mutating: yes. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: required from runtime env. Agent context: runtime env when available. Run attribution: attached from runtime env when available.",
      "inputSchema": {
        "additionalProperties": false,
        "properties": {
          "body": {
            "description": "Initial agent-authored chat message.",
            "maxLength": 500000,
            "minLength": 1,
            "type": "string"
          },
          "issueCreationMode": {
            "description": "Issue creation mode.",
            "maxLength": 100,
            "minLength": 1,
            "type": "string"
          },
          "payload": {
            "description": "JSON payload object or JSON string.",
            "type": [
              "object",
              "string"
            ]
          },
          "planMode": {
            "description": "Start the chat in plan mode.",
            "type": "boolean"
          },
          "preferredAgentId": {
            "description": "Preferred responding agent id.",
            "maxLength": 200,
            "minLength": 1,
            "type": "string"
          },
          "summary": {
            "description": "Chat summary.",
            "maxLength": 10000,
            "minLength": 1,
            "type": "string"
          },
          "title": {
            "description": "Chat title.",
            "maxLength": 500,
            "minLength": 1,
            "type": "string"
          }
        },
        "required": [
          "body"
        ],
        "type": "object"
      },
      "name": "rudder_chat_create"
    }
  },
  {
    "api": {
      "transport": "cli-fallback"
    },
    "cli": {
      "attachesRunIdWhenAvailable": true,
      "category": "chat",
      "command": "rudder chat send <chat-id-or-cht-ref> --body <text>",
      "contract": "agent-v1",
      "description": "Send an agent-authored message directly to the operator in a chat.",
      "id": "chat.send",
      "mutating": true,
      "requiresAgentId": true,
      "requiresOrgId": false,
      "requiresRunId": false
    },
    "id": "chat.send",
    "mcp": {
      "annotations": {
        "destructiveHint": false,
        "idempotentHint": false,
        "readOnlyHint": false,
        "title": "Send an agent-authored message directly to the operator in a chat"
      },
      "capabilityId": "chat.send",
      "description": "Send an agent-authored message directly to the operator in a chat. Mutating: yes. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: not required by this tool. Agent context: required from runtime env. Run attribution: attached from runtime env when available.",
      "inputSchema": {
        "additionalProperties": false,
        "properties": {
          "body": {
            "description": "Agent-authored chat message.",
            "maxLength": 500000,
            "minLength": 1,
            "type": "string"
          },
          "chat": {
            "description": "Chat conversation UUID or short reference.",
            "maxLength": 200,
            "minLength": 1,
            "type": "string"
          },
          "editUserMessageId": {
            "description": "User message id to edit.",
            "maxLength": 200,
            "minLength": 1,
            "type": "string"
          }
        },
        "required": [
          "chat",
          "body"
        ],
        "type": "object"
      },
      "name": "rudder_chat_send"
    }
  },
  {
    "api": {
      "transport": "cli-fallback"
    },
    "cli": {
      "attachesRunIdWhenAvailable": true,
      "category": "chat",
      "command": "rudder chat archive <chat-id-or-cht-ref>",
      "contract": "agent-v1",
      "description": "Archive a chat conversation without deleting it.",
      "id": "chat.archive",
      "mutating": true,
      "requiresAgentId": false,
      "requiresOrgId": false,
      "requiresRunId": false
    },
    "id": "chat.archive",
    "mcp": {
      "annotations": {
        "destructiveHint": true,
        "idempotentHint": false,
        "readOnlyHint": false,
        "title": "Archive a chat conversation without deleting it"
      },
      "capabilityId": "chat.archive",
      "description": "Archive a chat conversation without deleting it. Mutating: yes. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: not required by this tool. Agent context: runtime env when available. Run attribution: attached from runtime env when available.",
      "inputSchema": {
        "additionalProperties": false,
        "properties": {
          "chat": {
            "description": "Chat conversation UUID or short reference.",
            "maxLength": 200,
            "minLength": 1,
            "type": "string"
          }
        },
        "required": [
          "chat"
        ],
        "type": "object"
      },
      "name": "rudder_chat_archive"
    }
  },
  {
    "api": {
      "method": "GET",
      "pathTemplate": "/api/run-intelligence/orgs/{orgId}/runs",
      "transport": "direct"
    },
    "cli": {
      "attachesRunIdWhenAvailable": false,
      "category": "runs",
      "command": "rudder runs list --org-id <id> [--used-skill <skill>] [--loaded-skill <skill>] [--cursor <cursor>] [--full]",
      "contract": "agent-v1",
      "description": "List lightweight run summaries with stable pagination and filters; use --full only for legacy full-row compatibility.",
      "id": "runs.list",
      "mutating": false,
      "requiresAgentId": false,
      "requiresOrgId": true,
      "requiresRunId": false
    },
    "id": "runs.list",
    "mcp": {
      "annotations": {
        "destructiveHint": false,
        "idempotentHint": true,
        "readOnlyHint": true,
        "title": "List lightweight run summaries with stable pagination and filters"
      },
      "capabilityId": "runs.list",
      "description": "List lightweight run summaries with stable pagination and filters; use --full only for legacy full-row compatibility. Mutating: no. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: required from runtime env. Agent context: runtime env when available. Run attribution: not attached.",
      "inputSchema": {
        "additionalProperties": false,
        "properties": {
          "createdBefore": {
            "description": "Only runs created before this timestamp.",
            "maxLength": 100,
            "minLength": 1,
            "type": "string"
          },
          "cursor": {
            "description": "Opaque pagination cursor.",
            "maxLength": 2000,
            "minLength": 1,
            "type": "string"
          },
          "issueId": {
            "description": "Linked issue id filter.",
            "maxLength": 200,
            "minLength": 1,
            "type": "string"
          },
          "limit": {
            "description": "Summary page size.",
            "maximum": 100,
            "minimum": 1,
            "type": "number"
          },
          "loadedSkill": {
            "description": "Loaded skill filter.",
            "maxLength": 500,
            "minLength": 1,
            "type": "string"
          },
          "relatedAgentId": {
            "description": "Agent id filter.",
            "maxLength": 200,
            "minLength": 1,
            "type": "string"
          },
          "runIdPrefix": {
            "description": "Run id prefix filter.",
            "maxLength": 200,
            "minLength": 1,
            "type": "string"
          },
          "runtime": {
            "description": "Runtime type filter.",
            "maxLength": 100,
            "minLength": 1,
            "type": "string"
          },
          "status": {
            "description": "Run status filter.",
            "maxLength": 100,
            "minLength": 1,
            "type": "string"
          },
          "updatedAfter": {
            "description": "Only runs updated after this timestamp.",
            "maxLength": 100,
            "minLength": 1,
            "type": "string"
          },
          "usedSkill": {
            "description": "Used skill filter.",
            "maxLength": 500,
            "minLength": 1,
            "type": "string"
          }
        },
        "type": "object"
      },
      "name": "rudder_runs_list"
    }
  },
  {
    "api": {
      "transport": "cli-fallback"
    },
    "cli": {
      "attachesRunIdWhenAvailable": false,
      "category": "runs",
      "command": "rudder runs by-skill <skill> --org-id <id> [--evidence <used-or-loaded>] [--cursor <cursor>] [--full]",
      "contract": "agent-v1",
      "description": "Build a paginated skill evidence packet from lightweight run summaries; use --full only for legacy full-row compatibility.",
      "id": "runs.by-skill",
      "mutating": false,
      "requiresAgentId": false,
      "requiresOrgId": true,
      "requiresRunId": false
    },
    "id": "runs.by-skill",
    "mcp": {
      "annotations": {
        "destructiveHint": false,
        "idempotentHint": true,
        "readOnlyHint": true,
        "title": "Build a paginated skill evidence packet from lightweight run summaries"
      },
      "capabilityId": "runs.by-skill",
      "description": "Build a paginated skill evidence packet from lightweight run summaries; use --full only for legacy full-row compatibility. Mutating: no. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: required from runtime env. Agent context: runtime env when available. Run attribution: not attached.",
      "inputSchema": {
        "additionalProperties": false,
        "properties": {
          "createdBefore": {
            "description": "Only runs created before this timestamp.",
            "maxLength": 100,
            "minLength": 1,
            "type": "string"
          },
          "cursor": {
            "description": "Opaque pagination cursor.",
            "maxLength": 2000,
            "minLength": 1,
            "type": "string"
          },
          "evidence": {
            "description": "Skill evidence type.",
            "enum": [
              "used",
              "loaded"
            ],
            "maxLength": 20,
            "minLength": 1,
            "type": "string"
          },
          "issueId": {
            "description": "Linked issue id filter.",
            "maxLength": 200,
            "minLength": 1,
            "type": "string"
          },
          "limit": {
            "description": "Summary page size.",
            "maximum": 100,
            "minimum": 1,
            "type": "number"
          },
          "relatedAgentId": {
            "description": "Agent id filter.",
            "maxLength": 200,
            "minLength": 1,
            "type": "string"
          },
          "runtime": {
            "description": "Runtime type filter.",
            "maxLength": 100,
            "minLength": 1,
            "type": "string"
          },
          "skill": {
            "description": "Skill key or display name.",
            "maxLength": 500,
            "minLength": 1,
            "type": "string"
          },
          "status": {
            "description": "Run status filter.",
            "maxLength": 100,
            "minLength": 1,
            "type": "string"
          }
        },
        "required": [
          "skill"
        ],
        "type": "object"
      },
      "name": "rudder_runs_by_skill"
    }
  },
  {
    "api": {
      "method": "GET",
      "pathTemplate": "/api/run-intelligence/runs/{run}",
      "transport": "direct"
    },
    "cli": {
      "attachesRunIdWhenAvailable": false,
      "category": "runs",
      "command": "rudder runs get <run-id> [--full]",
      "contract": "agent-v1",
      "description": "Read one bounded run summary; use --full only from a direct trusted CLI for raw detail.",
      "id": "runs.get",
      "mutating": false,
      "requiresAgentId": false,
      "requiresOrgId": false,
      "requiresRunId": false
    },
    "id": "runs.get",
    "mcp": {
      "annotations": {
        "destructiveHint": false,
        "idempotentHint": true,
        "readOnlyHint": true,
        "title": "Read one bounded run summary"
      },
      "capabilityId": "runs.get",
      "description": "Read one bounded run summary; use --full only from a direct trusted CLI for raw detail. Mutating: no. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: not required by this tool. Agent context: runtime env when available. Run attribution: not attached.",
      "inputSchema": {
        "additionalProperties": false,
        "properties": {
          "run": {
            "description": "Run UUID, typed short reference (run_<prefix>), or legacy bare short prefix.",
            "maxLength": 200,
            "minLength": 1,
            "type": "string"
          }
        },
        "required": [
          "run"
        ],
        "type": "object"
      },
      "name": "rudder_runs_get"
    }
  },
  {
    "api": {
      "method": "GET",
      "pathTemplate": "/api/run-intelligence/runs/{run}/events",
      "transport": "direct"
    },
    "cli": {
      "attachesRunIdWhenAvailable": false,
      "category": "runs",
      "command": "rudder runs events <run-id> [--cursor <cursor>] [--after-seq <n>] [--limit <n>] [--full]",
      "contract": "agent-v1",
      "description": "List a bounded page of persisted run events with a lossless opaque cursor and clipped payload previews.",
      "id": "runs.events",
      "mutating": false,
      "requiresAgentId": false,
      "requiresOrgId": false,
      "requiresRunId": false
    },
    "id": "runs.events",
    "mcp": {
      "annotations": {
        "destructiveHint": false,
        "idempotentHint": true,
        "readOnlyHint": true,
        "title": "List a bounded page of persisted run events with a lossless opaque cursor and clipped payload previews"
      },
      "capabilityId": "runs.events",
      "description": "List a bounded page of persisted run events with a lossless opaque cursor and clipped payload previews. Mutating: no. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: not required by this tool. Agent context: runtime env when available. Run attribution: not attached.",
      "inputSchema": {
        "additionalProperties": false,
        "properties": {
          "afterSeq": {
            "description": "Legacy sequence-only cursor.",
            "maximum": 10000000,
            "minimum": 0,
            "type": "number"
          },
          "cursor": {
            "description": "Opaque pagination cursor.",
            "maxLength": 2000,
            "minLength": 1,
            "type": "string"
          },
          "limit": {
            "description": "Event page size.",
            "maximum": 500,
            "minimum": 1,
            "type": "number"
          },
          "maxChars": {
            "description": "Maximum preview characters per event.",
            "maximum": 20000,
            "minimum": 100,
            "type": "number"
          },
          "run": {
            "description": "Run UUID, typed short reference (run_<prefix>), or legacy bare short prefix.",
            "maxLength": 200,
            "minLength": 1,
            "type": "string"
          }
        },
        "required": [
          "run"
        ],
        "type": "object"
      },
      "name": "rudder_runs_events"
    }
  }
] as const;
