// Generated by scripts/generate-rudder-mcp-tool-descriptors.ts. Do not edit by hand.
export const GENERATED_RUDDER_AGENT_CONTRACT_CAPABILITIES_002 = [
  {
    "api": {
      "transport": "cli-fallback"
    },
    "cli": {
      "attachesRunIdWhenAvailable": false,
      "category": "library",
      "command": "rudder library file ref <path>",
      "contract": "agent-v1",
      "description": "Return the stable Markdown reference for one Library file without printing file content.",
      "id": "library.file.ref",
      "mutating": false,
      "requiresAgentId": false,
      "requiresOrgId": true,
      "requiresRunId": false
    },
    "id": "library.file.ref",
    "mcp": {
      "annotations": {
        "destructiveHint": false,
        "idempotentHint": true,
        "readOnlyHint": true,
        "title": "Return the stable Markdown reference for one Library file without printing file content"
      },
      "capabilityId": "library.file.ref",
      "description": "Return the stable Markdown reference for one Library file without printing file content. Mutating: no. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: required from runtime env. Agent context: runtime env when available. Run attribution: not attached.",
      "inputSchema": {
        "additionalProperties": false,
        "properties": {
          "path": {
            "description": "Library-relative file path.",
            "maxLength": 8192,
            "minLength": 1,
            "type": "string"
          }
        },
        "required": [
          "path"
        ],
        "type": "object"
      },
      "name": "rudder_library_file_ref"
    }
  },
  {
    "api": {
      "transport": "cli-fallback"
    },
    "cli": {
      "attachesRunIdWhenAvailable": false,
      "category": "library",
      "command": "rudder library file link <path>",
      "contract": "agent-v1",
      "description": "Compatibility alias for `rudder library file ref <path>`.",
      "id": "library.file.link",
      "mutating": false,
      "requiresAgentId": false,
      "requiresOrgId": true,
      "requiresRunId": false
    },
    "id": "library.file.link",
    "mcp": {
      "annotations": {
        "destructiveHint": false,
        "idempotentHint": true,
        "readOnlyHint": true,
        "title": "Compatibility alias for `rudder library file ref <path>`"
      },
      "capabilityId": "library.file.link",
      "description": "Compatibility alias for `rudder library file ref <path>`. Mutating: no. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: required from runtime env. Agent context: runtime env when available. Run attribution: not attached.",
      "inputSchema": {
        "additionalProperties": false,
        "properties": {
          "path": {
            "description": "Library-relative file path.",
            "maxLength": 8192,
            "minLength": 1,
            "type": "string"
          }
        },
        "required": [
          "path"
        ],
        "type": "object"
      },
      "name": "rudder_library_file_link"
    }
  },
  {
    "api": {
      "transport": "cli-fallback"
    },
    "cli": {
      "attachesRunIdWhenAvailable": true,
      "category": "library",
      "command": "rudder library file put <path> --body-file <path>",
      "contract": "agent-v1",
      "description": "Fallback create/update when local filesystem access is unavailable; JSON includes `mentionHref` and `markdownLink`.",
      "id": "library.file.put",
      "mutating": true,
      "requiresAgentId": false,
      "requiresOrgId": true,
      "requiresRunId": false
    },
    "id": "library.file.put",
    "mcp": {
      "annotations": {
        "destructiveHint": true,
        "idempotentHint": false,
        "readOnlyHint": false,
        "title": "Fallback create/update when local filesystem access is unavailable"
      },
      "capabilityId": "library.file.put",
      "description": "Fallback create/update when local filesystem access is unavailable; JSON includes `mentionHref` and `markdownLink`. Mutating: yes. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: required from runtime env. Agent context: runtime env when available. Run attribution: attached from runtime env when available.",
      "inputSchema": {
        "additionalProperties": false,
        "anyOf": [
          {
            "required": [
              "body"
            ]
          },
          {
            "required": [
              "content"
            ]
          }
        ],
        "properties": {
          "body": {
            "description": "Direct file content.",
            "maxLength": 1000000,
            "minLength": 1,
            "type": "string"
          },
          "content": {
            "description": "Compatibility alias for body.",
            "maxLength": 1000000,
            "minLength": 1,
            "type": "string"
          },
          "path": {
            "description": "Library-relative file path.",
            "maxLength": 8192,
            "minLength": 1,
            "type": "string"
          }
        },
        "required": [
          "path"
        ],
        "type": "object"
      },
      "name": "rudder_library_file_put"
    }
  },
  {
    "api": {
      "method": "POST",
      "pathTemplate": "/api/orgs/{orgId}/issues",
      "transport": "direct"
    },
    "cli": {
      "attachesRunIdWhenAvailable": true,
      "category": "issue",
      "command": "rudder issue create --org-id <id> ... [--label-id <id> ...] [--label <name> ...]",
      "contract": "agent-v1",
      "description": "Create a new issue or subtask with the generic issue surface; agent-created issues default to the creating agent when no assignee is supplied.",
      "id": "issue.create",
      "mutating": true,
      "requiresAgentId": false,
      "requiresOrgId": true,
      "requiresRunId": false
    },
    "id": "issue.create",
    "mcp": {
      "annotations": {
        "destructiveHint": false,
        "idempotentHint": false,
        "readOnlyHint": false,
        "title": "Create a new issue or subtask with the generic issue surface"
      },
      "capabilityId": "issue.create",
      "description": "Create a new issue or subtask with the generic issue surface; agent-created issues default to the creating agent when no assignee is supplied. Mutating: yes. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: required from runtime env. Agent context: runtime env when available. Run attribution: attached from runtime env when available.",
      "inputSchema": {
        "additionalProperties": false,
        "properties": {
          "assigneeAgentId": {
            "description": "Assignee agent id or reference.",
            "maxLength": 200,
            "minLength": 1,
            "type": "string"
          },
          "billingCode": {
            "description": "Billing code.",
            "maxLength": 200,
            "minLength": 1,
            "type": "string"
          },
          "description": {
            "description": "Issue description.",
            "maxLength": 500000,
            "minLength": 1,
            "type": "string"
          },
          "goalId": {
            "description": "Goal id or reference.",
            "maxLength": 200,
            "minLength": 1,
            "type": "string"
          },
          "labelIds": {
            "description": "Issue label ids.",
            "items": {
              "description": "Issue label ids.",
              "maxLength": 8192,
              "minLength": 1,
              "type": "string"
            },
            "maxItems": 100,
            "type": "array"
          },
          "parentId": {
            "description": "Parent issue id or reference.",
            "maxLength": 200,
            "minLength": 1,
            "type": "string"
          },
          "priority": {
            "description": "Issue priority.",
            "maxLength": 100,
            "minLength": 1,
            "type": "string"
          },
          "projectId": {
            "description": "Project id or reference.",
            "maxLength": 200,
            "minLength": 1,
            "type": "string"
          },
          "requestDepth": {
            "description": "Requested issue depth.",
            "maximum": 10000,
            "minimum": 0,
            "type": "number"
          },
          "status": {
            "description": "Issue status.",
            "maxLength": 100,
            "minLength": 1,
            "type": "string"
          },
          "title": {
            "description": "Issue title.",
            "maxLength": 500,
            "minLength": 1,
            "type": "string"
          }
        },
        "required": [
          "title"
        ],
        "type": "object"
      },
      "name": "rudder_issue_create"
    }
  },
  {
    "api": {
      "transport": "cli-fallback"
    },
    "cli": {
      "attachesRunIdWhenAvailable": false,
      "category": "issue",
      "command": "rudder issue labels list --org-id <id>",
      "contract": "compat",
      "description": "List organization issue labels available for issue creation.",
      "id": "issue.labels.list",
      "mutating": false,
      "requiresAgentId": false,
      "requiresOrgId": true,
      "requiresRunId": false
    },
    "id": "issue.labels.list",
    "mcp": null
  },
  {
    "api": {
      "transport": "cli-fallback"
    },
    "cli": {
      "attachesRunIdWhenAvailable": false,
      "category": "approval",
      "command": "rudder approval get <approval-id>",
      "contract": "agent-v1",
      "description": "Read one approval request.",
      "id": "approval.get",
      "mutating": false,
      "requiresAgentId": false,
      "requiresOrgId": false,
      "requiresRunId": false
    },
    "id": "approval.get",
    "mcp": {
      "annotations": {
        "destructiveHint": false,
        "idempotentHint": true,
        "readOnlyHint": true,
        "title": "Read one approval request"
      },
      "capabilityId": "approval.get",
      "description": "Read one approval request. Mutating: no. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: not required by this tool. Agent context: runtime env when available. Run attribution: not attached.",
      "inputSchema": {
        "additionalProperties": false,
        "properties": {
          "approval": {
            "description": "Approval UUID or short reference.",
            "maxLength": 200,
            "minLength": 1,
            "type": "string"
          }
        },
        "required": [
          "approval"
        ],
        "type": "object"
      },
      "name": "rudder_approval_get"
    }
  },
  {
    "api": {
      "transport": "cli-fallback"
    },
    "cli": {
      "attachesRunIdWhenAvailable": true,
      "category": "approval",
      "command": "rudder approval create --org-id <id> --type <type> --payload <json>",
      "contract": "compat",
      "description": "Create a new approval request.",
      "id": "approval.create",
      "mutating": true,
      "requiresAgentId": false,
      "requiresOrgId": true,
      "requiresRunId": false
    },
    "id": "approval.create",
    "mcp": null
  },
  {
    "api": {
      "transport": "cli-fallback"
    },
    "cli": {
      "attachesRunIdWhenAvailable": false,
      "category": "approval",
      "command": "rudder approval issues <approval-id>",
      "contract": "agent-v1",
      "description": "List the issues linked to an approval.",
      "id": "approval.issues",
      "mutating": false,
      "requiresAgentId": false,
      "requiresOrgId": false,
      "requiresRunId": false
    },
    "id": "approval.issues",
    "mcp": {
      "annotations": {
        "destructiveHint": false,
        "idempotentHint": true,
        "readOnlyHint": true,
        "title": "List the issues linked to an approval"
      },
      "capabilityId": "approval.issues",
      "description": "List the issues linked to an approval. Mutating: no. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: not required by this tool. Agent context: runtime env when available. Run attribution: not attached.",
      "inputSchema": {
        "additionalProperties": false,
        "properties": {
          "approval": {
            "description": "Approval UUID or short reference.",
            "maxLength": 200,
            "minLength": 1,
            "type": "string"
          }
        },
        "required": [
          "approval"
        ],
        "type": "object"
      },
      "name": "rudder_approval_issues"
    }
  },
  {
    "api": {
      "transport": "cli-fallback"
    },
    "cli": {
      "attachesRunIdWhenAvailable": true,
      "category": "approval",
      "command": "rudder approval comment <approval-id> --body-file <path>",
      "contract": "agent-v1",
      "description": "Add a comment to an approval.",
      "id": "approval.comment",
      "mutating": true,
      "requiresAgentId": false,
      "requiresOrgId": false,
      "requiresRunId": false
    },
    "id": "approval.comment",
    "mcp": {
      "annotations": {
        "destructiveHint": false,
        "idempotentHint": false,
        "readOnlyHint": false,
        "title": "Add a comment to an approval"
      },
      "capabilityId": "approval.comment",
      "description": "Add a comment to an approval. Mutating: yes. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: not required by this tool. Agent context: runtime env when available. Run attribution: attached from runtime env when available.",
      "inputSchema": {
        "additionalProperties": false,
        "anyOf": [
          {
            "required": [
              "body"
            ]
          },
          {
            "required": [
              "comment"
            ]
          }
        ],
        "properties": {
          "approval": {
            "description": "Approval UUID or short reference.",
            "maxLength": 200,
            "minLength": 1,
            "type": "string"
          },
          "body": {
            "description": "Direct Markdown body.",
            "maxLength": 500000,
            "minLength": 1,
            "type": "string"
          },
          "comment": {
            "description": "Direct Markdown body.",
            "maxLength": 500000,
            "minLength": 1,
            "type": "string"
          }
        },
        "required": [
          "approval"
        ],
        "type": "object"
      },
      "name": "rudder_approval_comment"
    }
  },
  {
    "api": {
      "transport": "cli-fallback"
    },
    "cli": {
      "attachesRunIdWhenAvailable": true,
      "category": "approval",
      "command": "rudder approval resubmit <approval-id> [--payload <json>]",
      "contract": "compat",
      "description": "Resubmit a revision-requested approval, optionally with updated payload.",
      "id": "approval.resubmit",
      "mutating": true,
      "requiresAgentId": false,
      "requiresOrgId": false,
      "requiresRunId": false
    },
    "id": "approval.resubmit",
    "mcp": null
  },
  {
    "api": {
      "transport": "cli-fallback"
    },
    "cli": {
      "attachesRunIdWhenAvailable": false,
      "category": "skill",
      "command": "rudder skill list --org-id <id>",
      "contract": "agent-v1",
      "description": "List organization-visible skills.",
      "id": "skill.list",
      "mutating": false,
      "requiresAgentId": false,
      "requiresOrgId": true,
      "requiresRunId": false
    },
    "id": "skill.list",
    "mcp": {
      "annotations": {
        "destructiveHint": false,
        "idempotentHint": true,
        "readOnlyHint": true,
        "title": "List organization-visible skills"
      },
      "capabilityId": "skill.list",
      "description": "List organization-visible skills. Mutating: no. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: required from runtime env. Agent context: runtime env when available. Run attribution: not attached.",
      "inputSchema": {
        "additionalProperties": false,
        "properties": {},
        "type": "object"
      },
      "name": "rudder_skill_list"
    }
  },
  {
    "api": {
      "transport": "cli-fallback"
    },
    "cli": {
      "attachesRunIdWhenAvailable": false,
      "category": "skill",
      "command": "rudder skill search <query> --org-id <id>",
      "contract": "agent-v1",
      "description": "Search organization-visible skills by name, slug, description, or source.",
      "id": "skill.search",
      "mutating": false,
      "requiresAgentId": false,
      "requiresOrgId": true,
      "requiresRunId": false
    },
    "id": "skill.search",
    "mcp": {
      "annotations": {
        "destructiveHint": false,
        "idempotentHint": true,
        "readOnlyHint": true,
        "title": "Search organization-visible skills by name, slug, description, or source"
      },
      "capabilityId": "skill.search",
      "description": "Search organization-visible skills by name, slug, description, or source. Mutating: no. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: required from runtime env. Agent context: runtime env when available. Run attribution: not attached.",
      "inputSchema": {
        "additionalProperties": false,
        "properties": {
          "query": {
            "description": "Skill name, slug, description, source, or selection key to search for.",
            "maxLength": 2000,
            "minLength": 1,
            "type": "string"
          }
        },
        "required": [
          "query"
        ],
        "type": "object"
      },
      "name": "rudder_skill_search"
    }
  },
  {
    "api": {
      "transport": "cli-fallback"
    },
    "cli": {
      "attachesRunIdWhenAvailable": false,
      "category": "skill",
      "command": "rudder skill get <skill-id> --org-id <id>",
      "contract": "agent-v1",
      "description": "Read one organization skill detail.",
      "id": "skill.get",
      "mutating": false,
      "requiresAgentId": false,
      "requiresOrgId": true,
      "requiresRunId": false
    },
    "id": "skill.get",
    "mcp": {
      "annotations": {
        "destructiveHint": false,
        "idempotentHint": true,
        "readOnlyHint": true,
        "title": "Read one organization skill detail"
      },
      "capabilityId": "skill.get",
      "description": "Read one organization skill detail. Mutating: no. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: required from runtime env. Agent context: runtime env when available. Run attribution: not attached.",
      "inputSchema": {
        "additionalProperties": false,
        "properties": {
          "skill": {
            "description": "Organization skill id.",
            "maxLength": 200,
            "minLength": 1,
            "type": "string"
          }
        },
        "required": [
          "skill"
        ],
        "type": "object"
      },
      "name": "rudder_skill_get"
    }
  },
  {
    "api": {
      "transport": "cli-fallback"
    },
    "cli": {
      "attachesRunIdWhenAvailable": false,
      "category": "skill",
      "command": "rudder skill file <skill-id> --org-id <id> [--path SKILL.md]",
      "contract": "agent-v1",
      "description": "Read one file from an organization skill package.",
      "id": "skill.file",
      "mutating": false,
      "requiresAgentId": false,
      "requiresOrgId": true,
      "requiresRunId": false
    },
    "id": "skill.file",
    "mcp": {
      "annotations": {
        "destructiveHint": false,
        "idempotentHint": true,
        "readOnlyHint": true,
        "title": "Read one file from an organization skill package"
      },
      "capabilityId": "skill.file",
      "description": "Read one file from an organization skill package. Mutating: no. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: required from runtime env. Agent context: runtime env when available. Run attribution: not attached.",
      "inputSchema": {
        "additionalProperties": false,
        "properties": {
          "path": {
            "description": "Skill package file path.",
            "maxLength": 8192,
            "minLength": 1,
            "type": "string"
          },
          "skill": {
            "description": "Organization skill id.",
            "maxLength": 200,
            "minLength": 1,
            "type": "string"
          }
        },
        "required": [
          "skill"
        ],
        "type": "object"
      },
      "name": "rudder_skill_file"
    }
  },
  {
    "api": {
      "transport": "cli-fallback"
    },
    "cli": {
      "attachesRunIdWhenAvailable": true,
      "category": "skill",
      "command": "rudder skill import --org-id <id> --source <source>",
      "contract": "agent-v1",
      "description": "Import a skill package into the organization skill library.",
      "id": "skill.import",
      "mutating": true,
      "requiresAgentId": false,
      "requiresOrgId": true,
      "requiresRunId": false
    },
    "id": "skill.import",
    "mcp": {
      "annotations": {
        "destructiveHint": false,
        "idempotentHint": false,
        "readOnlyHint": false,
        "title": "Import a skill package into the organization skill library"
      },
      "capabilityId": "skill.import",
      "description": "Import a skill package into the organization skill library. Mutating: yes. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: required from runtime env. Agent context: runtime env when available. Run attribution: attached from runtime env when available.",
      "inputSchema": {
        "additionalProperties": false,
        "properties": {
          "source": {
            "description": "Local path, URL, or repository reference.",
            "maxLength": 8192,
            "minLength": 1,
            "type": "string"
          }
        },
        "required": [
          "source"
        ],
        "type": "object"
      },
      "name": "rudder_skill_import"
    }
  },
  {
    "api": {
      "transport": "cli-fallback"
    },
    "cli": {
      "attachesRunIdWhenAvailable": true,
      "category": "skill",
      "command": "rudder skill scan-local --org-id <id> [--roots <csv>]",
      "contract": "agent-v1",
      "description": "Scan local roots for skill packages and import new ones.",
      "id": "skill.scan-local",
      "mutating": true,
      "requiresAgentId": false,
      "requiresOrgId": true,
      "requiresRunId": false
    },
    "id": "skill.scan-local",
    "mcp": {
      "annotations": {
        "destructiveHint": false,
        "idempotentHint": false,
        "readOnlyHint": false,
        "title": "Scan local roots for skill packages and import new ones"
      },
      "capabilityId": "skill.scan-local",
      "description": "Scan local roots for skill packages and import new ones. Mutating: yes. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: required from runtime env. Agent context: runtime env when available. Run attribution: attached from runtime env when available.",
      "inputSchema": {
        "additionalProperties": false,
        "properties": {
          "roots": {
            "description": "Comma-separated local roots.",
            "maxLength": 20000,
            "minLength": 1,
            "type": "string"
          }
        },
        "type": "object"
      },
      "name": "rudder_skill_scan_local"
    }
  },
  {
    "api": {
      "transport": "cli-fallback"
    },
    "cli": {
      "attachesRunIdWhenAvailable": true,
      "category": "skill",
      "command": "rudder skill scan-projects --org-id <id> [--project-ids <csv>] [--workspace-ids <csv>]",
      "contract": "agent-v1",
      "description": "Scan the org workspace and any legacy project workspace records for skill packages and import new ones.",
      "id": "skill.scan-projects",
      "mutating": true,
      "requiresAgentId": false,
      "requiresOrgId": true,
      "requiresRunId": false
    },
    "id": "skill.scan-projects",
    "mcp": {
      "annotations": {
        "destructiveHint": false,
        "idempotentHint": false,
        "readOnlyHint": false,
        "title": "Scan the org workspace and any legacy project workspace records for skill packages and import new ones"
      },
      "capabilityId": "skill.scan-projects",
      "description": "Scan the org workspace and any legacy project workspace records for skill packages and import new ones. Mutating: yes. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: required from runtime env. Agent context: runtime env when available. Run attribution: attached from runtime env when available.",
      "inputSchema": {
        "additionalProperties": false,
        "properties": {
          "projectIds": {
            "description": "Comma-separated project ids.",
            "maxLength": 20000,
            "minLength": 1,
            "type": "string"
          },
          "workspaceIds": {
            "description": "Comma-separated workspace ids.",
            "maxLength": 20000,
            "minLength": 1,
            "type": "string"
          }
        },
        "type": "object"
      },
      "name": "rudder_skill_scan_projects"
    }
  },
  {
    "api": {
      "transport": "cli-fallback"
    },
    "cli": {
      "attachesRunIdWhenAvailable": false,
      "category": "plugin",
      "command": "rudder plugin search <query> --org-id <id>",
      "contract": "agent-v1",
      "description": "Search installed, local, and discoverable Rudder plugins.",
      "id": "plugin.search",
      "mutating": false,
      "requiresAgentId": false,
      "requiresOrgId": true,
      "requiresRunId": false
    },
    "id": "plugin.search",
    "mcp": {
      "annotations": {
        "destructiveHint": false,
        "idempotentHint": true,
        "readOnlyHint": true,
        "title": "Search installed, local, and discoverable Rudder plugins"
      },
      "capabilityId": "plugin.search",
      "description": "Search installed, local, and discoverable Rudder plugins. Mutating: no. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: required from runtime env. Agent context: runtime env when available. Run attribution: not attached.",
      "inputSchema": {
        "additionalProperties": false,
        "properties": {
          "query": {
            "description": "Plugin name, description, publisher, source, or component to search for.",
            "maxLength": 2000,
            "minLength": 1,
            "type": "string"
          }
        },
        "required": [
          "query"
        ],
        "type": "object"
      },
      "name": "rudder_plugin_search"
    }
  },
  {
    "api": {
      "transport": "cli-fallback"
    },
    "cli": {
      "attachesRunIdWhenAvailable": false,
      "category": "plugin",
      "command": "rudder plugin get <plugin-id> --org-id <id>",
      "contract": "agent-v1",
      "description": "Read an installed plugin, including its components and current setup state; use this to resolve plugin:// references.",
      "id": "plugin.get",
      "mutating": false,
      "requiresAgentId": false,
      "requiresOrgId": true,
      "requiresRunId": false
    },
    "id": "plugin.get",
    "mcp": {
      "annotations": {
        "destructiveHint": false,
        "idempotentHint": true,
        "readOnlyHint": true,
        "title": "Read an installed plugin, including its components and current setup state"
      },
      "capabilityId": "plugin.get",
      "description": "Read an installed plugin, including its components and current setup state; use this to resolve plugin:// references. Mutating: no. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: required from runtime env. Agent context: runtime env when available. Run attribution: not attached.",
      "inputSchema": {
        "additionalProperties": false,
        "properties": {
          "plugin": {
            "description": "Installed plugin UUID from a plugin:// reference or plugin search result.",
            "maxLength": 200,
            "minLength": 1,
            "type": "string"
          }
        },
        "required": [
          "plugin"
        ],
        "type": "object"
      },
      "name": "rudder_plugin_get"
    }
  },
  {
    "api": {
      "method": "POST",
      "pathTemplate": "/api/browser/tabs",
      "transport": "direct"
    },
    "cli": {
      "attachesRunIdWhenAvailable": false,
      "category": "browser",
      "command": "rudder browser tabs",
      "contract": "agent-v1",
      "description": "List Browser tabs owned by the current Rudder agent run.",
      "id": "browser.tabs",
      "mutating": false,
      "requiresAgentId": true,
      "requiresOrgId": true,
      "requiresRunId": true
    },
    "id": "browser.tabs",
    "mcp": {
      "annotations": {
        "destructiveHint": false,
        "idempotentHint": true,
        "readOnlyHint": true,
        "title": "List Browser tabs owned by the current Rudder agent run"
      },
      "capabilityId": "browser.tabs",
      "description": "List Browser tabs owned by the current Rudder agent run. Mutating: no. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: required from runtime env. Agent context: required from runtime env. Run attribution: not attached.",
      "inputSchema": {
        "additionalProperties": false,
        "properties": {},
        "type": "object"
      },
      "name": "rudder_browser_tabs"
    }
  },
  {
    "api": {
      "method": "POST",
      "pathTemplate": "/api/browser/user_tabs",
      "transport": "direct"
    },
    "cli": {
      "attachesRunIdWhenAvailable": false,
      "category": "browser",
      "command": "rudder browser user-tabs",
      "contract": "agent-v1",
      "description": "List user-visible tabs currently open in Rudder's built-in Browser without taking control of them.",
      "id": "browser.user-tabs",
      "mutating": false,
      "requiresAgentId": true,
      "requiresOrgId": true,
      "requiresRunId": true
    },
    "id": "browser.user-tabs",
    "mcp": {
      "annotations": {
        "destructiveHint": false,
        "idempotentHint": true,
        "readOnlyHint": true,
        "title": "List user-visible tabs currently open in Rudder's built-in Browser without taking control of them"
      },
      "capabilityId": "browser.user-tabs",
      "description": "List user-visible tabs currently open in Rudder's built-in Browser without taking control of them. Mutating: no. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: required from runtime env. Agent context: required from runtime env. Run attribution: not attached.",
      "inputSchema": {
        "additionalProperties": false,
        "properties": {},
        "type": "object"
      },
      "name": "rudder_browser_user_tabs"
    }
  },
  {
    "api": {
      "method": "POST",
      "pathTemplate": "/api/browser/open",
      "transport": "direct"
    },
    "cli": {
      "attachesRunIdWhenAvailable": true,
      "category": "browser",
      "command": "rudder browser open <url>",
      "contract": "agent-v1",
      "description": "Open a run-owned tab in the Rudder Browser.",
      "id": "browser.open",
      "mutating": true,
      "requiresAgentId": true,
      "requiresOrgId": true,
      "requiresRunId": true
    },
    "id": "browser.open",
    "mcp": {
      "annotations": {
        "destructiveHint": false,
        "idempotentHint": false,
        "openWorldHint": true,
        "readOnlyHint": false,
        "title": "Open a run-owned tab in the Rudder Browser"
      },
      "capabilityId": "browser.open",
      "description": "Open a run-owned tab in the Rudder Browser. Mutating: yes. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: required from runtime env. Agent context: required from runtime env. Run attribution: attached from runtime env when available.",
      "inputSchema": {
        "additionalProperties": false,
        "properties": {
          "url": {
            "description": "HTTP or HTTPS URL.",
            "maxLength": 8192,
            "minLength": 1,
            "type": "string"
          }
        },
        "required": [
          "url"
        ],
        "type": "object"
      },
      "name": "rudder_browser_open"
    }
  },
  {
    "api": {
      "method": "POST",
      "pathTemplate": "/api/browser/navigate",
      "transport": "direct"
    },
    "cli": {
      "attachesRunIdWhenAvailable": true,
      "category": "browser",
      "command": "rudder browser navigate <tab-id> <url>",
      "contract": "agent-v1",
      "description": "Navigate a run-owned Rudder Browser tab.",
      "id": "browser.navigate",
      "mutating": true,
      "requiresAgentId": true,
      "requiresOrgId": true,
      "requiresRunId": true
    },
    "id": "browser.navigate",
    "mcp": {
      "annotations": {
        "destructiveHint": false,
        "idempotentHint": false,
        "openWorldHint": true,
        "readOnlyHint": false,
        "title": "Navigate a run-owned Rudder Browser tab"
      },
      "capabilityId": "browser.navigate",
      "description": "Navigate a run-owned Rudder Browser tab. Mutating: yes. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: required from runtime env. Agent context: required from runtime env. Run attribution: attached from runtime env when available.",
      "inputSchema": {
        "additionalProperties": false,
        "properties": {
          "tabId": {
            "description": "Run-owned Rudder Browser tab id.",
            "maxLength": 160,
            "minLength": 1,
            "type": "string"
          },
          "url": {
            "description": "HTTP or HTTPS URL.",
            "maxLength": 8192,
            "minLength": 1,
            "type": "string"
          }
        },
        "required": [
          "tabId",
          "url"
        ],
        "type": "object"
      },
      "name": "rudder_browser_navigate"
    }
  },
  {
    "api": {
      "method": "POST",
      "pathTemplate": "/api/browser/back",
      "transport": "direct"
    },
    "cli": {
      "attachesRunIdWhenAvailable": true,
      "category": "browser",
      "command": "rudder browser back <tab-id>",
      "contract": "agent-v1",
      "description": "Navigate a run-owned Rudder Browser tab back in history.",
      "id": "browser.back",
      "mutating": true,
      "requiresAgentId": true,
      "requiresOrgId": true,
      "requiresRunId": true
    },
    "id": "browser.back",
    "mcp": {
      "annotations": {
        "destructiveHint": false,
        "idempotentHint": false,
        "readOnlyHint": false,
        "title": "Navigate a run-owned Rudder Browser tab back in history"
      },
      "capabilityId": "browser.back",
      "description": "Navigate a run-owned Rudder Browser tab back in history. Mutating: yes. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: required from runtime env. Agent context: required from runtime env. Run attribution: attached from runtime env when available.",
      "inputSchema": {
        "additionalProperties": false,
        "properties": {
          "tabId": {
            "description": "Run-owned Rudder Browser tab id.",
            "maxLength": 160,
            "minLength": 1,
            "type": "string"
          }
        },
        "required": [
          "tabId"
        ],
        "type": "object"
      },
      "name": "rudder_browser_back"
    }
  },
  {
    "api": {
      "method": "POST",
      "pathTemplate": "/api/browser/forward",
      "transport": "direct"
    },
    "cli": {
      "attachesRunIdWhenAvailable": true,
      "category": "browser",
      "command": "rudder browser forward <tab-id>",
      "contract": "agent-v1",
      "description": "Navigate a run-owned Rudder Browser tab forward in history.",
      "id": "browser.forward",
      "mutating": true,
      "requiresAgentId": true,
      "requiresOrgId": true,
      "requiresRunId": true
    },
    "id": "browser.forward",
    "mcp": {
      "annotations": {
        "destructiveHint": false,
        "idempotentHint": false,
        "readOnlyHint": false,
        "title": "Navigate a run-owned Rudder Browser tab forward in history"
      },
      "capabilityId": "browser.forward",
      "description": "Navigate a run-owned Rudder Browser tab forward in history. Mutating: yes. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: required from runtime env. Agent context: required from runtime env. Run attribution: attached from runtime env when available.",
      "inputSchema": {
        "additionalProperties": false,
        "properties": {
          "tabId": {
            "description": "Run-owned Rudder Browser tab id.",
            "maxLength": 160,
            "minLength": 1,
            "type": "string"
          }
        },
        "required": [
          "tabId"
        ],
        "type": "object"
      },
      "name": "rudder_browser_forward"
    }
  },
  {
    "api": {
      "method": "POST",
      "pathTemplate": "/api/browser/reload",
      "transport": "direct"
    },
    "cli": {
      "attachesRunIdWhenAvailable": true,
      "category": "browser",
      "command": "rudder browser reload <tab-id>",
      "contract": "agent-v1",
      "description": "Reload a run-owned Rudder Browser tab.",
      "id": "browser.reload",
      "mutating": true,
      "requiresAgentId": true,
      "requiresOrgId": true,
      "requiresRunId": true
    },
    "id": "browser.reload",
    "mcp": {
      "annotations": {
        "destructiveHint": false,
        "idempotentHint": true,
        "readOnlyHint": false,
        "title": "Reload a run-owned Rudder Browser tab"
      },
      "capabilityId": "browser.reload",
      "description": "Reload a run-owned Rudder Browser tab. Mutating: yes. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: required from runtime env. Agent context: required from runtime env. Run attribution: attached from runtime env when available.",
      "inputSchema": {
        "additionalProperties": false,
        "properties": {
          "tabId": {
            "description": "Run-owned Rudder Browser tab id.",
            "maxLength": 160,
            "minLength": 1,
            "type": "string"
          }
        },
        "required": [
          "tabId"
        ],
        "type": "object"
      },
      "name": "rudder_browser_reload"
    }
  }
] as const;
