// Generated by scripts/generate-rudder-mcp-tool-descriptors.ts. Do not edit by hand.
export const GENERATED_RUDDER_AGENT_CONTRACT_CAPABILITIES_007 = [
  {
    "api": {
      "method": "GET",
      "pathTemplate": "/api/run-intelligence/runs/{run}/log",
      "transport": "direct"
    },
    "cli": {
      "attachesRunIdWhenAvailable": false,
      "category": "runs",
      "command": "rudder runs log <run-id> [--offset <bytes>] [--limit-bytes <n>]",
      "contract": "agent-v1",
      "description": "Read a bounded byte range of stored run log content.",
      "id": "runs.log",
      "mutating": false,
      "requiresAgentId": false,
      "requiresOrgId": false,
      "requiresRunId": false
    },
    "id": "runs.log",
    "mcp": {
      "annotations": {
        "destructiveHint": false,
        "idempotentHint": true,
        "readOnlyHint": true,
        "title": "Read a bounded byte range of stored run log content"
      },
      "capabilityId": "runs.log",
      "description": "Read a bounded byte range of stored run log content. Mutating: no. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: not required by this tool. Agent context: runtime env when available. Run attribution: not attached.",
      "inputSchema": {
        "additionalProperties": false,
        "properties": {
          "limitBytes": {
            "description": "Maximum bytes for ranged read.",
            "maximum": 1000000,
            "minimum": 1,
            "type": "number"
          },
          "maxChars": {
            "description": "Maximum displayed log characters.",
            "maximum": 100000,
            "minimum": 100,
            "type": "number"
          },
          "offset": {
            "description": "Byte offset for ranged read.",
            "maximum": 1000000000,
            "minimum": 0,
            "type": "number"
          },
          "run": {
            "description": "Run UUID, typed short reference (run_<prefix>), or legacy bare short prefix.",
            "maxLength": 200,
            "minLength": 1,
            "type": "string"
          }
        },
        "required": [
          "run"
        ],
        "type": "object"
      },
      "name": "rudder_runs_log"
    }
  },
  {
    "api": {
      "method": "GET",
      "pathTemplate": "/api/run-intelligence/runs/{run}/transcript",
      "transport": "direct"
    },
    "cli": {
      "attachesRunIdWhenAvailable": false,
      "category": "runs",
      "command": "rudder runs transcript <run-id> [--turn-limit <n>] [--cursor <cursor>] [--include-output] [--full]",
      "contract": "agent-v1",
      "description": "Read a compact server-normalized transcript; --json changes encoding only and --full is direct-CLI-only raw access.",
      "id": "runs.transcript",
      "mutating": false,
      "requiresAgentId": false,
      "requiresOrgId": false,
      "requiresRunId": false
    },
    "id": "runs.transcript",
    "mcp": {
      "annotations": {
        "destructiveHint": false,
        "idempotentHint": true,
        "readOnlyHint": true,
        "title": "Read a compact server-normalized transcript"
      },
      "capabilityId": "runs.transcript",
      "description": "Read a compact server-normalized transcript; --json changes encoding only and --full is direct-CLI-only raw access. Mutating: no. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: not required by this tool. Agent context: runtime env when available. Run attribution: not attached.",
      "inputSchema": {
        "additionalProperties": false,
        "properties": {
          "aroundError": {
            "description": "Transcript error step id.",
            "maxLength": 200,
            "minLength": 1,
            "type": "string"
          },
          "chronological": {
            "description": "Return oldest-first rows.",
            "type": "boolean"
          },
          "contextTurns": {
            "description": "Turns around the selected error.",
            "maximum": 20,
            "minimum": 1,
            "type": "number"
          },
          "cursor": {
            "description": "Opaque pagination cursor.",
            "maxLength": 2000,
            "minLength": 1,
            "type": "string"
          },
          "errorsOnly": {
            "description": "Return only error rows.",
            "type": "boolean"
          },
          "includeOutput": {
            "description": "Include clipped row output.",
            "type": "boolean"
          },
          "maxChars": {
            "description": "Maximum output characters per row.",
            "maximum": 20000,
            "minimum": 100,
            "type": "number"
          },
          "narrative": {
            "description": "Use narrative row formatting.",
            "type": "boolean"
          },
          "run": {
            "description": "Run UUID, typed short reference (run_<prefix>), or legacy bare short prefix.",
            "maxLength": 200,
            "minLength": 1,
            "type": "string"
          },
          "turnLimit": {
            "description": "Maximum turns.",
            "maximum": 100,
            "minimum": 1,
            "type": "number"
          }
        },
        "required": [
          "run"
        ],
        "type": "object"
      },
      "name": "rudder_runs_transcript"
    }
  },
  {
    "api": {
      "method": "GET",
      "pathTemplate": "/api/run-intelligence/runs/{run}/errors",
      "transport": "direct"
    },
    "cli": {
      "attachesRunIdWhenAvailable": false,
      "category": "runs",
      "command": "rudder runs errors <run-id>",
      "contract": "agent-v1",
      "description": "List failed tool calls, stderr, runtime failures, and jump-to-context commands.",
      "id": "runs.errors",
      "mutating": false,
      "requiresAgentId": false,
      "requiresOrgId": false,
      "requiresRunId": false
    },
    "id": "runs.errors",
    "mcp": {
      "annotations": {
        "destructiveHint": false,
        "idempotentHint": true,
        "readOnlyHint": true,
        "title": "List failed tool calls, stderr, runtime failures, and jump-to-context commands"
      },
      "capabilityId": "runs.errors",
      "description": "List failed tool calls, stderr, runtime failures, and jump-to-context commands. Mutating: no. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: not required by this tool. Agent context: runtime env when available. Run attribution: not attached.",
      "inputSchema": {
        "additionalProperties": false,
        "properties": {
          "cursor": {
            "description": "Opaque pagination cursor.",
            "maxLength": 2000,
            "minLength": 1,
            "type": "string"
          },
          "maxChars": {
            "description": "Maximum output characters per error.",
            "maximum": 20000,
            "minimum": 100,
            "type": "number"
          },
          "run": {
            "description": "Run UUID, typed short reference (run_<prefix>), or legacy bare short prefix.",
            "maxLength": 200,
            "minLength": 1,
            "type": "string"
          }
        },
        "required": [
          "run"
        ],
        "type": "object"
      },
      "name": "rudder_runs_errors"
    }
  },
  {
    "api": {
      "transport": "cli-fallback"
    },
    "cli": {
      "attachesRunIdWhenAvailable": true,
      "category": "runs",
      "command": "rudder runs cancel <run-id>",
      "contract": "agent-v1",
      "description": "Cancel a heartbeat run through the governed server route.",
      "id": "runs.cancel",
      "mutating": true,
      "requiresAgentId": false,
      "requiresOrgId": false,
      "requiresRunId": false
    },
    "id": "runs.cancel",
    "mcp": {
      "annotations": {
        "destructiveHint": true,
        "idempotentHint": false,
        "readOnlyHint": false,
        "title": "Cancel a heartbeat run through the governed server route"
      },
      "capabilityId": "runs.cancel",
      "description": "Cancel a heartbeat run through the governed server route. Mutating: yes. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: not required by this tool. Agent context: runtime env when available. Run attribution: attached from runtime env when available.",
      "inputSchema": {
        "additionalProperties": false,
        "properties": {
          "run": {
            "description": "Run UUID, typed short reference (run_<prefix>), or legacy bare short prefix.",
            "maxLength": 200,
            "minLength": 1,
            "type": "string"
          }
        },
        "required": [
          "run"
        ],
        "type": "object"
      },
      "name": "rudder_runs_cancel"
    }
  },
  {
    "api": {
      "transport": "cli-fallback"
    },
    "cli": {
      "attachesRunIdWhenAvailable": true,
      "category": "runs",
      "command": "rudder runs retry <run-id>",
      "contract": "agent-v1",
      "description": "Retry a failed, timed out, or cancelled run through the governed server route.",
      "id": "runs.retry",
      "mutating": true,
      "requiresAgentId": false,
      "requiresOrgId": false,
      "requiresRunId": false
    },
    "id": "runs.retry",
    "mcp": {
      "annotations": {
        "destructiveHint": false,
        "idempotentHint": false,
        "readOnlyHint": false,
        "title": "Retry a failed, timed out, or cancelled run through the governed server route"
      },
      "capabilityId": "runs.retry",
      "description": "Retry a failed, timed out, or cancelled run through the governed server route. Mutating: yes. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: not required by this tool. Agent context: runtime env when available. Run attribution: attached from runtime env when available.",
      "inputSchema": {
        "additionalProperties": false,
        "properties": {
          "run": {
            "description": "Run UUID, typed short reference (run_<prefix>), or legacy bare short prefix.",
            "maxLength": 200,
            "minLength": 1,
            "type": "string"
          }
        },
        "required": [
          "run"
        ],
        "type": "object"
      },
      "name": "rudder_runs_retry"
    }
  },
  {
    "api": {
      "method": "POST",
      "pathTemplate": "/api/agent-runs/delegation",
      "transport": "direct"
    },
    "cli": {
      "attachesRunIdWhenAvailable": true,
      "category": "runs",
      "command": "rudder runs create --task <text> --idempotency-key <key> [--target-agent-id <id>]",
      "contract": "agent-v1",
      "description": "Create an independently governed Delegation Run for the current or another same-organization Agent.",
      "id": "runs.create",
      "mutating": true,
      "requiresAgentId": true,
      "requiresOrgId": false,
      "requiresRunId": true
    },
    "id": "runs.create",
    "mcp": {
      "annotations": {
        "destructiveHint": false,
        "idempotentHint": true,
        "readOnlyHint": false,
        "title": "Create an independently governed Delegation Run"
      },
      "capabilityId": "runs.create",
      "description": "Create an independently governed Delegation Run for the current or another same-organization Agent. Mutating: yes. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: not required by this tool. Agent context: required from runtime env. Run attribution: attached from runtime env when available.",
      "inputSchema": {
        "additionalProperties": false,
        "properties": {
          "idempotencyKey": {
            "description": "Required stable key for safe replay.",
            "maxLength": 500,
            "minLength": 1,
            "type": "string"
          },
          "targetAgentId": {
            "description": "Optional same-organization target Agent id.",
            "maxLength": 200,
            "minLength": 1,
            "type": "string"
          },
          "task": {
            "description": "Delegation task to run independently.",
            "maxLength": 20000,
            "minLength": 1,
            "type": "string"
          }
        },
        "required": [
          "task",
          "idempotencyKey"
        ],
        "type": "object"
      },
      "name": "rudder_runs_create"
    }
  }
] as const;
