// Generated by scripts/generate-rudder-mcp-tool-descriptors.ts. Do not edit by hand.
export const GENERATED_RUDDER_MCP_TOOL_DESCRIPTORS_002 = [
  {
    "capabilityId": "browser.cua",
    "name": "rudder_browser_cua",
    "description": "Perform trusted coordinate mouse, scroll, drag, keyboard, and text input in a run-owned Browser tab.",
    "semanticDescription": "Perform trusted coordinate mouse, scroll, drag, keyboard, and text input in a run-owned Browser tab. Mutating: yes. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: required from runtime env. Agent context: required from runtime env. Run attribution: attached from runtime env when available.",
    "annotations": {
      "destructiveHint": false,
      "idempotentHint": false,
      "readOnlyHint": false,
      "title": "Perform trusted coordinate mouse, scroll, drag, keyboard, and text input in a run-owned Browser tab"
    },
    "mutating": true,
    "requiresOrgId": true,
    "requiresAgentId": true,
    "attachesRunIdWhenAvailable": true,
    "inputSchema": {
      "additionalProperties": false,
      "properties": {
        "action": {
          "description": "Coordinate input or inspection action.",
          "enum": [
            "click",
            "doubleClick",
            "move",
            "scroll",
            "drag",
            "keypress",
            "type",
            "elementInfo"
          ],
          "type": "string"
        },
        "button": {
          "oneOf": [
            {
              "description": "Mouse button number.",
              "maximum": 5,
              "minimum": 1,
              "type": "number"
            },
            {
              "description": "Mouse button.",
              "enum": [
                "left",
                "middle",
                "right"
              ],
              "type": "string"
            }
          ]
        },
        "keys": {
          "items": {
            "description": "Keyboard key or modifier.",
            "maxLength": 100,
            "minLength": 1,
            "type": "string"
          },
          "maxItems": 10,
          "type": "array"
        },
        "path": {
          "items": {
            "additionalProperties": false,
            "properties": {
              "x": {
                "description": "Path X coordinate.",
                "type": "number"
              },
              "y": {
                "description": "Path Y coordinate.",
                "type": "number"
              }
            },
            "required": [
              "x",
              "y"
            ],
            "type": "object"
          },
          "maxItems": 200,
          "minItems": 2,
          "type": "array"
        },
        "scrollX": {
          "description": "Horizontal scroll delta.",
          "type": "number"
        },
        "scrollY": {
          "description": "Vertical scroll delta.",
          "type": "number"
        },
        "tabId": {
          "description": "Run-owned Rudder Browser tab id.",
          "maxLength": 160,
          "minLength": 1,
          "type": "string"
        },
        "text": {
          "description": "Text to type.",
          "maxLength": 100000,
          "type": "string"
        },
        "x": {
          "description": "Viewport X coordinate.",
          "type": "number"
        },
        "y": {
          "description": "Viewport Y coordinate.",
          "type": "number"
        }
      },
      "required": [
        "tabId",
        "action"
      ],
      "type": "object"
    }
  },
  {
    "capabilityId": "browser.dom-cua",
    "name": "rudder_browser_dom_cua",
    "description": "Inspect a bounded read-only DOM snapshot with ephemeral node ids.",
    "semanticDescription": "Inspect a bounded read-only DOM snapshot with ephemeral node ids. Mutating: no. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: required from runtime env. Agent context: required from runtime env. Run attribution: attached from runtime env when available.",
    "annotations": {
      "destructiveHint": false,
      "idempotentHint": true,
      "readOnlyHint": true,
      "title": "Inspect a bounded read-only DOM snapshot with ephemeral node ids"
    },
    "mutating": false,
    "requiresOrgId": true,
    "requiresAgentId": true,
    "attachesRunIdWhenAvailable": true,
    "inputSchema": {
      "additionalProperties": false,
      "properties": {
        "action": {
          "description": "Read-only DOM snapshot action.",
          "enum": [
            "get"
          ],
          "type": "string"
        },
        "depth": {
          "description": "Maximum DOM depth.",
          "maximum": 30,
          "minimum": 1,
          "type": "number"
        },
        "maxNodes": {
          "description": "Maximum DOM nodes.",
          "maximum": 3000,
          "minimum": 1,
          "type": "number"
        },
        "tabId": {
          "description": "Run-owned Rudder Browser tab id.",
          "maxLength": 160,
          "minLength": 1,
          "type": "string"
        }
      },
      "required": [
        "tabId",
        "action"
      ],
      "type": "object"
    }
  },
  {
    "capabilityId": "browser.dialog",
    "name": "rudder_browser_dialog",
    "description": "Inspect, accept, or dismiss the active JavaScript dialog in a run-owned Browser tab.",
    "semanticDescription": "Inspect, accept, or dismiss the active JavaScript dialog in a run-owned Browser tab. Mutating: yes. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: required from runtime env. Agent context: required from runtime env. Run attribution: attached from runtime env when available.",
    "annotations": {
      "destructiveHint": false,
      "idempotentHint": false,
      "readOnlyHint": false,
      "title": "Inspect, accept, or dismiss the active JavaScript dialog in a run-owned Browser tab"
    },
    "mutating": true,
    "requiresOrgId": true,
    "requiresAgentId": true,
    "attachesRunIdWhenAvailable": true,
    "inputSchema": {
      "additionalProperties": false,
      "properties": {
        "action": {
          "description": "Dialog action.",
          "enum": [
            "get",
            "accept",
            "dismiss"
          ],
          "type": "string"
        },
        "promptText": {
          "description": "Prompt response text.",
          "maxLength": 10000,
          "type": "string"
        },
        "tabId": {
          "description": "Run-owned Rudder Browser tab id.",
          "maxLength": 160,
          "minLength": 1,
          "type": "string"
        }
      },
      "required": [
        "tabId",
        "action"
      ],
      "type": "object"
    }
  },
  {
    "capabilityId": "browser.clipboard",
    "name": "rudder_browser_clipboard",
    "description": "Read or write the isolated virtual clipboard for the current Browser run without touching the OS clipboard.",
    "semanticDescription": "Read or write the isolated virtual clipboard for the current Browser run without touching the OS clipboard. Mutating: yes. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: required from runtime env. Agent context: required from runtime env. Run attribution: attached from runtime env when available.",
    "annotations": {
      "destructiveHint": true,
      "idempotentHint": false,
      "readOnlyHint": false,
      "title": "Read or write the isolated virtual clipboard for the current Browser run without touching the OS clipboard"
    },
    "mutating": true,
    "requiresOrgId": true,
    "requiresAgentId": true,
    "attachesRunIdWhenAvailable": true,
    "inputSchema": {
      "additionalProperties": false,
      "properties": {
        "action": {
          "description": "Virtual clipboard action.",
          "enum": [
            "read",
            "readText",
            "write",
            "writeText",
            "clear"
          ],
          "type": "string"
        },
        "items": {
          "items": {
            "additionalProperties": false,
            "properties": {
              "entries": {
                "items": {
                  "additionalProperties": false,
                  "properties": {
                    "base64": {
                      "description": "Base64 clipboard payload.",
                      "maxLength": 650000,
                      "type": "string"
                    },
                    "mimeType": {
                      "description": "Clipboard MIME type.",
                      "maxLength": 200,
                      "minLength": 1,
                      "type": "string"
                    },
                    "text": {
                      "description": "Text clipboard payload.",
                      "maxLength": 500000,
                      "type": "string"
                    }
                  },
                  "required": [
                    "mimeType"
                  ],
                  "type": "object"
                },
                "maxItems": 20,
                "type": "array"
              },
              "presentationStyle": {
                "description": "Clipboard presentation style.",
                "enum": [
                  "unspecified",
                  "inline",
                  "attachment"
                ],
                "type": "string"
              }
            },
            "required": [
              "entries"
            ],
            "type": "object"
          },
          "maxItems": 20,
          "type": "array"
        },
        "text": {
          "description": "Plain clipboard text.",
          "maxLength": 500000,
          "type": "string"
        }
      },
      "required": [
        "action"
      ],
      "type": "object"
    }
  },
  {
    "capabilityId": "browser.logs",
    "name": "rudder_browser_logs",
    "description": "Read bounded console and runtime logs captured for a run-owned Browser tab.",
    "semanticDescription": "Read bounded console and runtime logs captured for a run-owned Browser tab. Mutating: yes. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: required from runtime env. Agent context: required from runtime env. Run attribution: attached from runtime env when available.",
    "annotations": {
      "destructiveHint": true,
      "idempotentHint": false,
      "readOnlyHint": false,
      "title": "Read bounded console and runtime logs captured for a run-owned Browser tab"
    },
    "mutating": true,
    "requiresOrgId": true,
    "requiresAgentId": true,
    "attachesRunIdWhenAvailable": true,
    "inputSchema": {
      "additionalProperties": false,
      "properties": {
        "clear": {
          "description": "Clear the tab log buffer after reading.",
          "type": "boolean"
        },
        "filter": {
          "description": "Case-insensitive log substring filter.",
          "maxLength": 2000,
          "type": "string"
        },
        "levels": {
          "items": {
            "description": "Log level.",
            "enum": [
              "debug",
              "info",
              "log",
              "warn",
              "error"
            ],
            "type": "string"
          },
          "maxItems": 5,
          "type": "array"
        },
        "limit": {
          "description": "Maximum log entries.",
          "maximum": 500,
          "minimum": 1,
          "type": "number"
        },
        "tabId": {
          "description": "Run-owned Rudder Browser tab id.",
          "maxLength": 160,
          "minLength": 1,
          "type": "string"
        }
      },
      "required": [
        "tabId"
      ],
      "type": "object"
    }
  },
  {
    "capabilityId": "browser.download",
    "name": "rudder_browser_download",
    "description": "Download explicit locator media without dispatching page input into a bounded run-owned artifact.",
    "semanticDescription": "Download explicit locator media without dispatching page input into a bounded run-owned artifact. Mutating: yes. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: required from runtime env. Agent context: required from runtime env. Run attribution: attached from runtime env when available.",
    "annotations": {
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": true,
      "readOnlyHint": false,
      "title": "Download explicit locator media without dispatching page input into a bounded run-owned artifact"
    },
    "mutating": true,
    "requiresOrgId": true,
    "requiresAgentId": true,
    "attachesRunIdWhenAvailable": true,
    "inputSchema": {
      "additionalProperties": false,
      "properties": {
        "locator": {
          "additionalProperties": false,
          "properties": {
            "and": {
              "additionalProperties": false,
              "properties": {
                "exact": {
                  "description": "Require an exact text or attribute match.",
                  "type": "boolean"
                },
                "name": {
                  "description": "Accessible name used with the role strategy.",
                  "maxLength": 2000,
                  "type": "string"
                },
                "strategy": {
                  "description": "Locator strategy.",
                  "enum": [
                    "css",
                    "testId",
                    "href",
                    "role",
                    "label",
                    "placeholder",
                    "text"
                  ],
                  "type": "string"
                },
                "value": {
                  "description": "Selector, role, label, placeholder, href, test id, or text value.",
                  "maxLength": 2000,
                  "minLength": 1,
                  "type": "string"
                }
              },
              "required": [
                "strategy",
                "value"
              ],
              "type": "object"
            },
            "exact": {
              "description": "Require an exact text or attribute match.",
              "type": "boolean"
            },
            "filter": {
              "additionalProperties": false,
              "properties": {
                "has": {
                  "additionalProperties": false,
                  "properties": {
                    "exact": {
                      "description": "Require an exact text or attribute match.",
                      "type": "boolean"
                    },
                    "name": {
                      "description": "Accessible name used with the role strategy.",
                      "maxLength": 2000,
                      "type": "string"
                    },
                    "strategy": {
                      "description": "Locator strategy.",
                      "enum": [
                        "css",
                        "testId",
                        "href",
                        "role",
                        "label",
                        "placeholder",
                        "text"
                      ],
                      "type": "string"
                    },
                    "value": {
                      "description": "Selector, role, label, placeholder, href, test id, or text value.",
                      "maxLength": 2000,
                      "minLength": 1,
                      "type": "string"
                    }
                  },
                  "required": [
                    "strategy",
                    "value"
                  ],
                  "type": "object"
                },
                "hasNot": {
                  "additionalProperties": false,
                  "properties": {
                    "exact": {
                      "description": "Require an exact text or attribute match.",
                      "type": "boolean"
                    },
                    "name": {
                      "description": "Accessible name used with the role strategy.",
                      "maxLength": 2000,
                      "type": "string"
                    },
                    "strategy": {
                      "description": "Locator strategy.",
                      "enum": [
                        "css",
                        "testId",
                        "href",
                        "role",
                        "label",
                        "placeholder",
                        "text"
                      ],
                      "type": "string"
                    },
                    "value": {
                      "description": "Selector, role, label, placeholder, href, test id, or text value.",
                      "maxLength": 2000,
                      "minLength": 1,
                      "type": "string"
                    }
                  },
                  "required": [
                    "strategy",
                    "value"
                  ],
                  "type": "object"
                },
                "hasNotText": {
                  "description": "Excluded descendant text.",
                  "maxLength": 2000,
                  "type": "string"
                },
                "hasText": {
                  "description": "Required descendant text.",
                  "maxLength": 2000,
                  "type": "string"
                },
                "visible": {
                  "description": "Filter by current visibility.",
                  "type": "boolean"
                }
              },
              "type": "object"
            },
            "frame": {
              "items": {
                "description": "CSS iframe selector.",
                "maxLength": 1000,
                "minLength": 1,
                "type": "string"
              },
              "maxItems": 8,
              "type": "array"
            },
            "index": {
              "description": "Zero-based locator match index.",
              "maximum": 499,
              "minimum": 0,
              "type": "number"
            },
            "name": {
              "description": "Accessible name used with the role strategy.",
              "maxLength": 2000,
              "type": "string"
            },
            "or": {
              "additionalProperties": false,
              "properties": {
                "exact": {
                  "description": "Require an exact text or attribute match.",
                  "type": "boolean"
                },
                "name": {
                  "description": "Accessible name used with the role strategy.",
                  "maxLength": 2000,
                  "type": "string"
                },
                "strategy": {
                  "description": "Locator strategy.",
                  "enum": [
                    "css",
                    "testId",
                    "href",
                    "role",
                    "label",
                    "placeholder",
                    "text"
                  ],
                  "type": "string"
                },
                "value": {
                  "description": "Selector, role, label, placeholder, href, test id, or text value.",
                  "maxLength": 2000,
                  "minLength": 1,
                  "type": "string"
                }
              },
              "required": [
                "strategy",
                "value"
              ],
              "type": "object"
            },
            "position": {
              "description": "Locator endpoint after an explicit count.",
              "enum": [
                "first",
                "last"
              ],
              "type": "string"
            },
            "scope": {
              "additionalProperties": false,
              "properties": {
                "and": {
                  "additionalProperties": false,
                  "properties": {
                    "exact": {
                      "description": "Require an exact text or attribute match.",
                      "type": "boolean"
                    },
                    "name": {
                      "description": "Accessible name used with the role strategy.",
                      "maxLength": 2000,
                      "type": "string"
                    },
                    "strategy": {
                      "description": "Locator strategy.",
                      "enum": [
                        "css",
                        "testId",
                        "href",
                        "role",
                        "label",
                        "placeholder",
                        "text"
                      ],
                      "type": "string"
                    },
                    "value": {
                      "description": "Selector, role, label, placeholder, href, test id, or text value.",
                      "maxLength": 2000,
                      "minLength": 1,
                      "type": "string"
                    }
                  },
                  "required": [
                    "strategy",
                    "value"
                  ],
                  "type": "object"
                },
                "exact": {
                  "description": "Require an exact text or attribute match.",
                  "type": "boolean"
                },
                "filter": {
                  "additionalProperties": false,
                  "properties": {
                    "has": {
                      "additionalProperties": false,
                      "properties": {
                        "exact": {
                          "description": "Require an exact text or attribute match.",
                          "type": "boolean"
                        },
                        "name": {
                          "description": "Accessible name used with the role strategy.",
                          "maxLength": 2000,
                          "type": "string"
                        },
                        "strategy": {
                          "description": "Locator strategy.",
                          "enum": [
                            "css",
                            "testId",
                            "href",
                            "role",
                            "label",
                            "placeholder",
                            "text"
                          ],
                          "type": "string"
                        },
                        "value": {
                          "description": "Selector, role, label, placeholder, href, test id, or text value.",
                          "maxLength": 2000,
                          "minLength": 1,
                          "type": "string"
                        }
                      },
                      "required": [
                        "strategy",
                        "value"
                      ],
                      "type": "object"
                    },
                    "hasNot": {
                      "additionalProperties": false,
                      "properties": {
                        "exact": {
                          "description": "Require an exact text or attribute match.",
                          "type": "boolean"
                        },
                        "name": {
                          "description": "Accessible name used with the role strategy.",
                          "maxLength": 2000,
                          "type": "string"
                        },
                        "strategy": {
                          "description": "Locator strategy.",
                          "enum": [
                            "css",
                            "testId",
                            "href",
                            "role",
                            "label",
                            "placeholder",
                            "text"
                          ],
                          "type": "string"
                        },
                        "value": {
                          "description": "Selector, role, label, placeholder, href, test id, or text value.",
                          "maxLength": 2000,
                          "minLength": 1,
                          "type": "string"
                        }
                      },
                      "required": [
                        "strategy",
                        "value"
                      ],
                      "type": "object"
                    },
                    "hasNotText": {
                      "description": "Excluded descendant text.",
                      "maxLength": 2000,
                      "type": "string"
                    },
                    "hasText": {
                      "description": "Required descendant text.",
                      "maxLength": 2000,
                      "type": "string"
                    },
                    "visible": {
                      "description": "Filter by current visibility.",
                      "type": "boolean"
                    }
                  },
                  "type": "object"
                },
                "index": {
                  "description": "Zero-based locator match index.",
                  "maximum": 499,
                  "minimum": 0,
                  "type": "number"
                },
                "name": {
                  "description": "Accessible name used with the role strategy.",
                  "maxLength": 2000,
                  "type": "string"
                },
                "or": {
                  "additionalProperties": false,
                  "properties": {
                    "exact": {
                      "description": "Require an exact text or attribute match.",
                      "type": "boolean"
                    },
                    "name": {
                      "description": "Accessible name used with the role strategy.",
                      "maxLength": 2000,
                      "type": "string"
                    },
                    "strategy": {
                      "description": "Locator strategy.",
                      "enum": [
                        "css",
                        "testId",
                        "href",
                        "role",
                        "label",
                        "placeholder",
                        "text"
                      ],
                      "type": "string"
                    },
                    "value": {
                      "description": "Selector, role, label, placeholder, href, test id, or text value.",
                      "maxLength": 2000,
                      "minLength": 1,
                      "type": "string"
                    }
                  },
                  "required": [
                    "strategy",
                    "value"
                  ],
                  "type": "object"
                },
                "position": {
                  "description": "Locator endpoint after an explicit count.",
                  "enum": [
                    "first",
                    "last"
                  ],
                  "type": "string"
                },
                "strategy": {
                  "description": "Locator strategy.",
                  "enum": [
                    "css",
                    "testId",
                    "href",
                    "role",
                    "label",
                    "placeholder",
                    "text"
                  ],
                  "type": "string"
                },
                "value": {
                  "description": "Selector, role, label, placeholder, href, test id, or text value.",
                  "maxLength": 2000,
                  "minLength": 1,
                  "type": "string"
                }
              },
              "required": [
                "strategy",
                "value"
              ],
              "type": "object"
            },
            "strategy": {
              "description": "Locator strategy.",
              "enum": [
                "css",
                "testId",
                "href",
                "role",
                "label",
                "placeholder",
                "text"
              ],
              "type": "string"
            },
            "value": {
              "description": "Selector, role, label, placeholder, href, test id, or text value.",
              "maxLength": 2000,
              "minLength": 1,
              "type": "string"
            }
          },
          "required": [
            "strategy",
            "value"
          ],
          "type": "object"
        },
        "mode": {
          "description": "Read-only media download mode.",
          "enum": [
            "media"
          ],
          "type": "string"
        },
        "tabId": {
          "description": "Run-owned Rudder Browser tab id.",
          "maxLength": 160,
          "minLength": 1,
          "type": "string"
        }
      },
      "required": [
        "tabId",
        "mode",
        "locator"
      ],
      "type": "object"
    }
  },
  {
    "capabilityId": "browser.assets",
    "name": "rudder_browser_assets",
    "description": "List page assets or bundle an explicit bounded selection into a run-owned temporary artifact.",
    "semanticDescription": "List page assets or bundle an explicit bounded selection into a run-owned temporary artifact. Mutating: yes. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: required from runtime env. Agent context: required from runtime env. Run attribution: attached from runtime env when available.",
    "annotations": {
      "destructiveHint": false,
      "idempotentHint": false,
      "readOnlyHint": false,
      "title": "List page assets or bundle an explicit bounded selection into a run-owned temporary artifact"
    },
    "mutating": true,
    "requiresOrgId": true,
    "requiresAgentId": true,
    "attachesRunIdWhenAvailable": true,
    "inputSchema": {
      "additionalProperties": false,
      "properties": {
        "action": {
          "description": "Asset action.",
          "enum": [
            "list",
            "bundle"
          ],
          "type": "string"
        },
        "assetIds": {
          "items": {
            "description": "Asset id.",
            "maxLength": 160,
            "type": "string"
          },
          "maxItems": 100,
          "minItems": 1,
          "type": "array"
        },
        "inventoryId": {
          "description": "Prior asset inventory id.",
          "maxLength": 160,
          "type": "string"
        },
        "kinds": {
          "items": {
            "description": "Asset kind.",
            "enum": [
              "font",
              "image",
              "stylesheet",
              "video"
            ],
            "type": "string"
          },
          "maxItems": 4,
          "minItems": 1,
          "type": "array"
        },
        "tabId": {
          "description": "Run-owned Rudder Browser tab id.",
          "maxLength": 160,
          "minLength": 1,
          "type": "string"
        }
      },
      "required": [
        "tabId",
        "action"
      ],
      "type": "object"
    }
  },
  {
    "capabilityId": "browser.content",
    "name": "rudder_browser_content",
    "description": "Export current page content or an eligible Google Workspace document into a bounded run-owned artifact.",
    "semanticDescription": "Export current page content or an eligible Google Workspace document into a bounded run-owned artifact. Mutating: yes. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: required from runtime env. Agent context: required from runtime env. Run attribution: attached from runtime env when available.",
    "annotations": {
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": true,
      "readOnlyHint": false,
      "title": "Export current page content or an eligible Google Workspace document into a bounded run-owned artifact"
    },
    "mutating": true,
    "requiresOrgId": true,
    "requiresAgentId": true,
    "attachesRunIdWhenAvailable": true,
    "inputSchema": {
      "additionalProperties": false,
      "properties": {
        "format": {
          "description": "Content export format.",
          "enum": [
            "text",
            "pdf",
            "md",
            "docx",
            "xlsx",
            "csv",
            "pptx"
          ],
          "type": "string"
        },
        "tabId": {
          "description": "Run-owned Rudder Browser tab id.",
          "maxLength": 160,
          "minLength": 1,
          "type": "string"
        }
      },
      "required": [
        "tabId",
        "format"
      ],
      "type": "object"
    }
  },
  {
    "capabilityId": "browser.wait",
    "name": "rudder_browser_wait",
    "description": "Wait for bounded URL, text, disappearance, or time conditions in a run-owned Browser tab.",
    "semanticDescription": "Wait for bounded URL, text, disappearance, or time conditions in a run-owned Browser tab. Mutating: no. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: required from runtime env. Agent context: required from runtime env. Run attribution: attached from runtime env when available.",
    "annotations": {
      "destructiveHint": false,
      "idempotentHint": true,
      "readOnlyHint": true,
      "title": "Wait for bounded URL, text, disappearance, or time conditions in a run-owned Browser tab"
    },
    "mutating": false,
    "requiresOrgId": true,
    "requiresAgentId": true,
    "attachesRunIdWhenAvailable": true,
    "inputSchema": {
      "additionalProperties": false,
      "properties": {
        "tabId": {
          "description": "Run-owned Rudder Browser tab id.",
          "maxLength": 160,
          "minLength": 1,
          "type": "string"
        },
        "text": {
          "description": "Text that must appear.",
          "maxLength": 10000,
          "type": "string"
        },
        "textGone": {
          "description": "Text that must disappear.",
          "maxLength": 10000,
          "type": "string"
        },
        "timeMs": {
          "description": "Fixed bounded delay in milliseconds.",
          "maximum": 30000,
          "minimum": 0,
          "type": "number"
        },
        "timeoutMs": {
          "description": "Wait timeout in milliseconds.",
          "maximum": 30000,
          "minimum": 0,
          "type": "number"
        },
        "url": {
          "description": "URL substring.",
          "maxLength": 8192,
          "type": "string"
        }
      },
      "required": [
        "tabId"
      ],
      "type": "object"
    }
  },
  {
    "capabilityId": "browser.read",
    "name": "rudder_browser_read",
    "description": "Read a structured snapshot from a run-owned Rudder Browser tab.",
    "semanticDescription": "Read a structured snapshot from a run-owned Rudder Browser tab. Mutating: no. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: required from runtime env. Agent context: required from runtime env. Run attribution: not attached.",
    "annotations": {
      "destructiveHint": false,
      "idempotentHint": true,
      "readOnlyHint": true,
      "title": "Read a structured snapshot from a run-owned Rudder Browser tab"
    },
    "mutating": false,
    "requiresOrgId": true,
    "requiresAgentId": true,
    "attachesRunIdWhenAvailable": false,
    "inputSchema": {
      "additionalProperties": false,
      "properties": {
        "tabId": {
          "description": "Run-owned Rudder Browser tab id.",
          "maxLength": 160,
          "minLength": 1,
          "type": "string"
        }
      },
      "required": [
        "tabId"
      ],
      "type": "object"
    }
  },
  {
    "capabilityId": "browser.click",
    "name": "rudder_browser_click",
    "description": "Click an element reference returned by Rudder Browser read.",
    "semanticDescription": "Click an element reference returned by Rudder Browser read. Mutating: yes. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: required from runtime env. Agent context: required from runtime env. Run attribution: attached from runtime env when available.",
    "annotations": {
      "destructiveHint": false,
      "idempotentHint": false,
      "readOnlyHint": false,
      "title": "Click an element reference returned by Rudder Browser read"
    },
    "mutating": true,
    "requiresOrgId": true,
    "requiresAgentId": true,
    "attachesRunIdWhenAvailable": true,
    "inputSchema": {
      "additionalProperties": false,
      "properties": {
        "ref": {
          "description": "Element reference returned by rudder_browser_read.",
          "maxLength": 160,
          "type": "string"
        },
        "tabId": {
          "description": "Run-owned Rudder Browser tab id.",
          "maxLength": 160,
          "minLength": 1,
          "type": "string"
        }
      },
      "required": [
        "tabId",
        "ref"
      ],
      "type": "object"
    }
  },
  {
    "capabilityId": "browser.type",
    "name": "rudder_browser_type",
    "description": "Type into an element reference in a run-owned Rudder Browser tab.",
    "semanticDescription": "Type into an element reference in a run-owned Rudder Browser tab. Mutating: yes. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: required from runtime env. Agent context: required from runtime env. Run attribution: attached from runtime env when available.",
    "annotations": {
      "destructiveHint": false,
      "idempotentHint": false,
      "readOnlyHint": false,
      "title": "Type into an element reference in a run-owned Rudder Browser tab"
    },
    "mutating": true,
    "requiresOrgId": true,
    "requiresAgentId": true,
    "attachesRunIdWhenAvailable": true,
    "inputSchema": {
      "additionalProperties": false,
      "properties": {
        "ref": {
          "description": "Element reference returned by rudder_browser_read.",
          "maxLength": 160,
          "type": "string"
        },
        "submit": {
          "description": "Submit the owning form after typing.",
          "type": "boolean"
        },
        "tabId": {
          "description": "Run-owned Rudder Browser tab id.",
          "maxLength": 160,
          "minLength": 1,
          "type": "string"
        },
        "text": {
          "description": "Text to enter.",
          "maxLength": 100000,
          "type": "string"
        }
      },
      "required": [
        "tabId",
        "ref",
        "text"
      ],
      "type": "object"
    }
  }
] as const;
