// Generated by scripts/generate-rudder-mcp-tool-descriptors.ts. Do not edit by hand.
export const GENERATED_RUDDER_AGENT_CONTRACT_CAPABILITIES_004 = [
  {
    "api": {
      "method": "POST",
      "pathTemplate": "/api/browser/download",
      "transport": "direct"
    },
    "cli": {
      "attachesRunIdWhenAvailable": true,
      "category": "browser",
      "command": "rudder browser download <tab-id> --input <json>",
      "contract": "agent-v1",
      "description": "Download explicit locator media without dispatching page input into a bounded run-owned artifact.",
      "id": "browser.download",
      "mutating": true,
      "requiresAgentId": true,
      "requiresOrgId": true,
      "requiresRunId": true
    },
    "id": "browser.download",
    "mcp": {
      "annotations": {
        "destructiveHint": false,
        "idempotentHint": false,
        "openWorldHint": true,
        "readOnlyHint": false,
        "title": "Download explicit locator media without dispatching page input into a bounded run-owned artifact"
      },
      "capabilityId": "browser.download",
      "description": "Download explicit locator media without dispatching page input into a bounded run-owned artifact. Mutating: yes. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: required from runtime env. Agent context: required from runtime env. Run attribution: attached from runtime env when available.",
      "inputSchema": {
        "additionalProperties": false,
        "properties": {
          "locator": {
            "additionalProperties": false,
            "properties": {
              "and": {
                "additionalProperties": false,
                "properties": {
                  "exact": {
                    "description": "Require an exact text or attribute match.",
                    "type": "boolean"
                  },
                  "name": {
                    "description": "Accessible name used with the role strategy.",
                    "maxLength": 2000,
                    "type": "string"
                  },
                  "strategy": {
                    "description": "Locator strategy.",
                    "enum": [
                      "css",
                      "testId",
                      "href",
                      "role",
                      "label",
                      "placeholder",
                      "text"
                    ],
                    "type": "string"
                  },
                  "value": {
                    "description": "Selector, role, label, placeholder, href, test id, or text value.",
                    "maxLength": 2000,
                    "minLength": 1,
                    "type": "string"
                  }
                },
                "required": [
                  "strategy",
                  "value"
                ],
                "type": "object"
              },
              "exact": {
                "description": "Require an exact text or attribute match.",
                "type": "boolean"
              },
              "filter": {
                "additionalProperties": false,
                "properties": {
                  "has": {
                    "additionalProperties": false,
                    "properties": {
                      "exact": {
                        "description": "Require an exact text or attribute match.",
                        "type": "boolean"
                      },
                      "name": {
                        "description": "Accessible name used with the role strategy.",
                        "maxLength": 2000,
                        "type": "string"
                      },
                      "strategy": {
                        "description": "Locator strategy.",
                        "enum": [
                          "css",
                          "testId",
                          "href",
                          "role",
                          "label",
                          "placeholder",
                          "text"
                        ],
                        "type": "string"
                      },
                      "value": {
                        "description": "Selector, role, label, placeholder, href, test id, or text value.",
                        "maxLength": 2000,
                        "minLength": 1,
                        "type": "string"
                      }
                    },
                    "required": [
                      "strategy",
                      "value"
                    ],
                    "type": "object"
                  },
                  "hasNot": {
                    "additionalProperties": false,
                    "properties": {
                      "exact": {
                        "description": "Require an exact text or attribute match.",
                        "type": "boolean"
                      },
                      "name": {
                        "description": "Accessible name used with the role strategy.",
                        "maxLength": 2000,
                        "type": "string"
                      },
                      "strategy": {
                        "description": "Locator strategy.",
                        "enum": [
                          "css",
                          "testId",
                          "href",
                          "role",
                          "label",
                          "placeholder",
                          "text"
                        ],
                        "type": "string"
                      },
                      "value": {
                        "description": "Selector, role, label, placeholder, href, test id, or text value.",
                        "maxLength": 2000,
                        "minLength": 1,
                        "type": "string"
                      }
                    },
                    "required": [
                      "strategy",
                      "value"
                    ],
                    "type": "object"
                  },
                  "hasNotText": {
                    "description": "Excluded descendant text.",
                    "maxLength": 2000,
                    "type": "string"
                  },
                  "hasText": {
                    "description": "Required descendant text.",
                    "maxLength": 2000,
                    "type": "string"
                  },
                  "visible": {
                    "description": "Filter by current visibility.",
                    "type": "boolean"
                  }
                },
                "type": "object"
              },
              "frame": {
                "items": {
                  "description": "CSS iframe selector.",
                  "maxLength": 1000,
                  "minLength": 1,
                  "type": "string"
                },
                "maxItems": 8,
                "type": "array"
              },
              "index": {
                "description": "Zero-based locator match index.",
                "maximum": 499,
                "minimum": 0,
                "type": "number"
              },
              "name": {
                "description": "Accessible name used with the role strategy.",
                "maxLength": 2000,
                "type": "string"
              },
              "or": {
                "additionalProperties": false,
                "properties": {
                  "exact": {
                    "description": "Require an exact text or attribute match.",
                    "type": "boolean"
                  },
                  "name": {
                    "description": "Accessible name used with the role strategy.",
                    "maxLength": 2000,
                    "type": "string"
                  },
                  "strategy": {
                    "description": "Locator strategy.",
                    "enum": [
                      "css",
                      "testId",
                      "href",
                      "role",
                      "label",
                      "placeholder",
                      "text"
                    ],
                    "type": "string"
                  },
                  "value": {
                    "description": "Selector, role, label, placeholder, href, test id, or text value.",
                    "maxLength": 2000,
                    "minLength": 1,
                    "type": "string"
                  }
                },
                "required": [
                  "strategy",
                  "value"
                ],
                "type": "object"
              },
              "position": {
                "description": "Locator endpoint after an explicit count.",
                "enum": [
                  "first",
                  "last"
                ],
                "type": "string"
              },
              "scope": {
                "additionalProperties": false,
                "properties": {
                  "and": {
                    "additionalProperties": false,
                    "properties": {
                      "exact": {
                        "description": "Require an exact text or attribute match.",
                        "type": "boolean"
                      },
                      "name": {
                        "description": "Accessible name used with the role strategy.",
                        "maxLength": 2000,
                        "type": "string"
                      },
                      "strategy": {
                        "description": "Locator strategy.",
                        "enum": [
                          "css",
                          "testId",
                          "href",
                          "role",
                          "label",
                          "placeholder",
                          "text"
                        ],
                        "type": "string"
                      },
                      "value": {
                        "description": "Selector, role, label, placeholder, href, test id, or text value.",
                        "maxLength": 2000,
                        "minLength": 1,
                        "type": "string"
                      }
                    },
                    "required": [
                      "strategy",
                      "value"
                    ],
                    "type": "object"
                  },
                  "exact": {
                    "description": "Require an exact text or attribute match.",
                    "type": "boolean"
                  },
                  "filter": {
                    "additionalProperties": false,
                    "properties": {
                      "has": {
                        "additionalProperties": false,
                        "properties": {
                          "exact": {
                            "description": "Require an exact text or attribute match.",
                            "type": "boolean"
                          },
                          "name": {
                            "description": "Accessible name used with the role strategy.",
                            "maxLength": 2000,
                            "type": "string"
                          },
                          "strategy": {
                            "description": "Locator strategy.",
                            "enum": [
                              "css",
                              "testId",
                              "href",
                              "role",
                              "label",
                              "placeholder",
                              "text"
                            ],
                            "type": "string"
                          },
                          "value": {
                            "description": "Selector, role, label, placeholder, href, test id, or text value.",
                            "maxLength": 2000,
                            "minLength": 1,
                            "type": "string"
                          }
                        },
                        "required": [
                          "strategy",
                          "value"
                        ],
                        "type": "object"
                      },
                      "hasNot": {
                        "additionalProperties": false,
                        "properties": {
                          "exact": {
                            "description": "Require an exact text or attribute match.",
                            "type": "boolean"
                          },
                          "name": {
                            "description": "Accessible name used with the role strategy.",
                            "maxLength": 2000,
                            "type": "string"
                          },
                          "strategy": {
                            "description": "Locator strategy.",
                            "enum": [
                              "css",
                              "testId",
                              "href",
                              "role",
                              "label",
                              "placeholder",
                              "text"
                            ],
                            "type": "string"
                          },
                          "value": {
                            "description": "Selector, role, label, placeholder, href, test id, or text value.",
                            "maxLength": 2000,
                            "minLength": 1,
                            "type": "string"
                          }
                        },
                        "required": [
                          "strategy",
                          "value"
                        ],
                        "type": "object"
                      },
                      "hasNotText": {
                        "description": "Excluded descendant text.",
                        "maxLength": 2000,
                        "type": "string"
                      },
                      "hasText": {
                        "description": "Required descendant text.",
                        "maxLength": 2000,
                        "type": "string"
                      },
                      "visible": {
                        "description": "Filter by current visibility.",
                        "type": "boolean"
                      }
                    },
                    "type": "object"
                  },
                  "index": {
                    "description": "Zero-based locator match index.",
                    "maximum": 499,
                    "minimum": 0,
                    "type": "number"
                  },
                  "name": {
                    "description": "Accessible name used with the role strategy.",
                    "maxLength": 2000,
                    "type": "string"
                  },
                  "or": {
                    "additionalProperties": false,
                    "properties": {
                      "exact": {
                        "description": "Require an exact text or attribute match.",
                        "type": "boolean"
                      },
                      "name": {
                        "description": "Accessible name used with the role strategy.",
                        "maxLength": 2000,
                        "type": "string"
                      },
                      "strategy": {
                        "description": "Locator strategy.",
                        "enum": [
                          "css",
                          "testId",
                          "href",
                          "role",
                          "label",
                          "placeholder",
                          "text"
                        ],
                        "type": "string"
                      },
                      "value": {
                        "description": "Selector, role, label, placeholder, href, test id, or text value.",
                        "maxLength": 2000,
                        "minLength": 1,
                        "type": "string"
                      }
                    },
                    "required": [
                      "strategy",
                      "value"
                    ],
                    "type": "object"
                  },
                  "position": {
                    "description": "Locator endpoint after an explicit count.",
                    "enum": [
                      "first",
                      "last"
                    ],
                    "type": "string"
                  },
                  "strategy": {
                    "description": "Locator strategy.",
                    "enum": [
                      "css",
                      "testId",
                      "href",
                      "role",
                      "label",
                      "placeholder",
                      "text"
                    ],
                    "type": "string"
                  },
                  "value": {
                    "description": "Selector, role, label, placeholder, href, test id, or text value.",
                    "maxLength": 2000,
                    "minLength": 1,
                    "type": "string"
                  }
                },
                "required": [
                  "strategy",
                  "value"
                ],
                "type": "object"
              },
              "strategy": {
                "description": "Locator strategy.",
                "enum": [
                  "css",
                  "testId",
                  "href",
                  "role",
                  "label",
                  "placeholder",
                  "text"
                ],
                "type": "string"
              },
              "value": {
                "description": "Selector, role, label, placeholder, href, test id, or text value.",
                "maxLength": 2000,
                "minLength": 1,
                "type": "string"
              }
            },
            "required": [
              "strategy",
              "value"
            ],
            "type": "object"
          },
          "mode": {
            "description": "Read-only media download mode.",
            "enum": [
              "media"
            ],
            "type": "string"
          },
          "tabId": {
            "description": "Run-owned Rudder Browser tab id.",
            "maxLength": 160,
            "minLength": 1,
            "type": "string"
          }
        },
        "required": [
          "tabId",
          "mode",
          "locator"
        ],
        "type": "object"
      },
      "name": "rudder_browser_download"
    }
  },
  {
    "api": {
      "method": "POST",
      "pathTemplate": "/api/browser/assets",
      "transport": "direct"
    },
    "cli": {
      "attachesRunIdWhenAvailable": true,
      "category": "browser",
      "command": "rudder browser assets <tab-id> --input <json>",
      "contract": "agent-v1",
      "description": "List page assets or bundle an explicit bounded selection into a run-owned temporary artifact.",
      "id": "browser.assets",
      "mutating": true,
      "requiresAgentId": true,
      "requiresOrgId": true,
      "requiresRunId": true
    },
    "id": "browser.assets",
    "mcp": {
      "annotations": {
        "destructiveHint": false,
        "idempotentHint": false,
        "readOnlyHint": false,
        "title": "List page assets or bundle an explicit bounded selection into a run-owned temporary artifact"
      },
      "capabilityId": "browser.assets",
      "description": "List page assets or bundle an explicit bounded selection into a run-owned temporary artifact. Mutating: yes. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: required from runtime env. Agent context: required from runtime env. Run attribution: attached from runtime env when available.",
      "inputSchema": {
        "additionalProperties": false,
        "properties": {
          "action": {
            "description": "Asset action.",
            "enum": [
              "list",
              "bundle"
            ],
            "type": "string"
          },
          "assetIds": {
            "items": {
              "description": "Asset id.",
              "maxLength": 160,
              "type": "string"
            },
            "maxItems": 100,
            "minItems": 1,
            "type": "array"
          },
          "inventoryId": {
            "description": "Prior asset inventory id.",
            "maxLength": 160,
            "type": "string"
          },
          "kinds": {
            "items": {
              "description": "Asset kind.",
              "enum": [
                "font",
                "image",
                "stylesheet",
                "video"
              ],
              "type": "string"
            },
            "maxItems": 4,
            "minItems": 1,
            "type": "array"
          },
          "tabId": {
            "description": "Run-owned Rudder Browser tab id.",
            "maxLength": 160,
            "minLength": 1,
            "type": "string"
          }
        },
        "required": [
          "tabId",
          "action"
        ],
        "type": "object"
      },
      "name": "rudder_browser_assets"
    }
  },
  {
    "api": {
      "method": "POST",
      "pathTemplate": "/api/browser/content",
      "transport": "direct"
    },
    "cli": {
      "attachesRunIdWhenAvailable": true,
      "category": "browser",
      "command": "rudder browser content <tab-id> --input <json>",
      "contract": "agent-v1",
      "description": "Export current page content or an eligible Google Workspace document into a bounded run-owned artifact.",
      "id": "browser.content",
      "mutating": true,
      "requiresAgentId": true,
      "requiresOrgId": true,
      "requiresRunId": true
    },
    "id": "browser.content",
    "mcp": {
      "annotations": {
        "destructiveHint": false,
        "idempotentHint": false,
        "openWorldHint": true,
        "readOnlyHint": false,
        "title": "Export current page content or an eligible Google Workspace document into a bounded run-owned artifact"
      },
      "capabilityId": "browser.content",
      "description": "Export current page content or an eligible Google Workspace document into a bounded run-owned artifact. Mutating: yes. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: required from runtime env. Agent context: required from runtime env. Run attribution: attached from runtime env when available.",
      "inputSchema": {
        "additionalProperties": false,
        "properties": {
          "format": {
            "description": "Content export format.",
            "enum": [
              "text",
              "pdf",
              "md",
              "docx",
              "xlsx",
              "csv",
              "pptx"
            ],
            "type": "string"
          },
          "tabId": {
            "description": "Run-owned Rudder Browser tab id.",
            "maxLength": 160,
            "minLength": 1,
            "type": "string"
          }
        },
        "required": [
          "tabId",
          "format"
        ],
        "type": "object"
      },
      "name": "rudder_browser_content"
    }
  },
  {
    "api": {
      "method": "POST",
      "pathTemplate": "/api/browser/wait",
      "transport": "direct"
    },
    "cli": {
      "attachesRunIdWhenAvailable": true,
      "category": "browser",
      "command": "rudder browser wait <tab-id> --input <json>",
      "contract": "agent-v1",
      "description": "Wait for bounded URL, text, disappearance, or time conditions in a run-owned Browser tab.",
      "id": "browser.wait",
      "mutating": false,
      "requiresAgentId": true,
      "requiresOrgId": true,
      "requiresRunId": true
    },
    "id": "browser.wait",
    "mcp": {
      "annotations": {
        "destructiveHint": false,
        "idempotentHint": true,
        "readOnlyHint": true,
        "title": "Wait for bounded URL, text, disappearance, or time conditions in a run-owned Browser tab"
      },
      "capabilityId": "browser.wait",
      "description": "Wait for bounded URL, text, disappearance, or time conditions in a run-owned Browser tab. Mutating: no. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: required from runtime env. Agent context: required from runtime env. Run attribution: attached from runtime env when available.",
      "inputSchema": {
        "additionalProperties": false,
        "properties": {
          "tabId": {
            "description": "Run-owned Rudder Browser tab id.",
            "maxLength": 160,
            "minLength": 1,
            "type": "string"
          },
          "text": {
            "description": "Text that must appear.",
            "maxLength": 10000,
            "type": "string"
          },
          "textGone": {
            "description": "Text that must disappear.",
            "maxLength": 10000,
            "type": "string"
          },
          "timeMs": {
            "description": "Fixed bounded delay in milliseconds.",
            "maximum": 30000,
            "minimum": 0,
            "type": "number"
          },
          "timeoutMs": {
            "description": "Wait timeout in milliseconds.",
            "maximum": 30000,
            "minimum": 0,
            "type": "number"
          },
          "url": {
            "description": "URL substring.",
            "maxLength": 8192,
            "type": "string"
          }
        },
        "required": [
          "tabId"
        ],
        "type": "object"
      },
      "name": "rudder_browser_wait"
    }
  },
  {
    "api": {
      "method": "POST",
      "pathTemplate": "/api/browser/read",
      "transport": "direct"
    },
    "cli": {
      "attachesRunIdWhenAvailable": false,
      "category": "browser",
      "command": "rudder browser read <tab-id>",
      "contract": "agent-v1",
      "description": "Read a structured snapshot from a run-owned Rudder Browser tab.",
      "id": "browser.read",
      "mutating": false,
      "requiresAgentId": true,
      "requiresOrgId": true,
      "requiresRunId": true
    },
    "id": "browser.read",
    "mcp": {
      "annotations": {
        "destructiveHint": false,
        "idempotentHint": true,
        "readOnlyHint": true,
        "title": "Read a structured snapshot from a run-owned Rudder Browser tab"
      },
      "capabilityId": "browser.read",
      "description": "Read a structured snapshot from a run-owned Rudder Browser tab. Mutating: no. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: required from runtime env. Agent context: required from runtime env. Run attribution: not attached.",
      "inputSchema": {
        "additionalProperties": false,
        "properties": {
          "tabId": {
            "description": "Run-owned Rudder Browser tab id.",
            "maxLength": 160,
            "minLength": 1,
            "type": "string"
          }
        },
        "required": [
          "tabId"
        ],
        "type": "object"
      },
      "name": "rudder_browser_read"
    }
  },
  {
    "api": {
      "method": "POST",
      "pathTemplate": "/api/browser/click",
      "transport": "direct"
    },
    "cli": {
      "attachesRunIdWhenAvailable": true,
      "category": "browser",
      "command": "rudder browser click <tab-id> <ref>",
      "contract": "agent-v1",
      "description": "Click an element reference returned by Rudder Browser read.",
      "id": "browser.click",
      "mutating": true,
      "requiresAgentId": true,
      "requiresOrgId": true,
      "requiresRunId": true
    },
    "id": "browser.click",
    "mcp": {
      "annotations": {
        "destructiveHint": false,
        "idempotentHint": false,
        "readOnlyHint": false,
        "title": "Click an element reference returned by Rudder Browser read"
      },
      "capabilityId": "browser.click",
      "description": "Click an element reference returned by Rudder Browser read. Mutating: yes. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: required from runtime env. Agent context: required from runtime env. Run attribution: attached from runtime env when available.",
      "inputSchema": {
        "additionalProperties": false,
        "properties": {
          "ref": {
            "description": "Element reference returned by rudder_browser_read.",
            "maxLength": 160,
            "type": "string"
          },
          "tabId": {
            "description": "Run-owned Rudder Browser tab id.",
            "maxLength": 160,
            "minLength": 1,
            "type": "string"
          }
        },
        "required": [
          "tabId",
          "ref"
        ],
        "type": "object"
      },
      "name": "rudder_browser_click"
    }
  },
  {
    "api": {
      "method": "POST",
      "pathTemplate": "/api/browser/type",
      "transport": "direct"
    },
    "cli": {
      "attachesRunIdWhenAvailable": true,
      "category": "browser",
      "command": "rudder browser type <tab-id> <ref> --text <text>",
      "contract": "agent-v1",
      "description": "Type into an element reference in a run-owned Rudder Browser tab.",
      "id": "browser.type",
      "mutating": true,
      "requiresAgentId": true,
      "requiresOrgId": true,
      "requiresRunId": true
    },
    "id": "browser.type",
    "mcp": {
      "annotations": {
        "destructiveHint": false,
        "idempotentHint": false,
        "readOnlyHint": false,
        "title": "Type into an element reference in a run-owned Rudder Browser tab"
      },
      "capabilityId": "browser.type",
      "description": "Type into an element reference in a run-owned Rudder Browser tab. Mutating: yes. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: required from runtime env. Agent context: required from runtime env. Run attribution: attached from runtime env when available.",
      "inputSchema": {
        "additionalProperties": false,
        "properties": {
          "ref": {
            "description": "Element reference returned by rudder_browser_read.",
            "maxLength": 160,
            "type": "string"
          },
          "submit": {
            "description": "Submit the owning form after typing.",
            "type": "boolean"
          },
          "tabId": {
            "description": "Run-owned Rudder Browser tab id.",
            "maxLength": 160,
            "minLength": 1,
            "type": "string"
          },
          "text": {
            "description": "Text to enter.",
            "maxLength": 100000,
            "type": "string"
          }
        },
        "required": [
          "tabId",
          "ref",
          "text"
        ],
        "type": "object"
      },
      "name": "rudder_browser_type"
    }
  }
] as const;
