// Generated by scripts/generate-rudder-mcp-tool-descriptors.ts. Do not edit by hand.
export const RUDDER_MCP_TOOL_DESCRIPTORS = [
  {
    "capabilityId": "agent.me",
    "name": "rudder_agent_me",
    "description": "Show the authenticated agent identity and budget.",
    "mutating": false,
    "requiresOrgId": false,
    "requiresAgentId": false,
    "attachesRunIdWhenAvailable": false
  },
  {
    "capabilityId": "agent.inbox",
    "name": "rudder_agent_inbox",
    "description": "List the compact assignee and reviewer work inbox for the authenticated agent.",
    "mutating": false,
    "requiresOrgId": false,
    "requiresAgentId": false,
    "attachesRunIdWhenAvailable": false
  },
  {
    "capabilityId": "organization.members.list",
    "name": "rudder_organization_members_list",
    "description": "List active visible human and agent members in the authenticated organization.",
    "mutating": false,
    "requiresOrgId": true,
    "requiresAgentId": false,
    "attachesRunIdWhenAvailable": false
  },
  {
    "capabilityId": "agent.capabilities",
    "name": "rudder_agent_capabilities",
    "description": "List the stable Rudder agent command contract.",
    "mutating": false,
    "requiresOrgId": false,
    "requiresAgentId": false,
    "attachesRunIdWhenAvailable": false
  },
  {
    "capabilityId": "agent.update",
    "name": "rudder_agent_update",
    "description": "Update an agent's identity fields; defaults to the authenticated agent.",
    "mutating": true,
    "requiresOrgId": false,
    "requiresAgentId": false,
    "attachesRunIdWhenAvailable": true
  },
  {
    "capabilityId": "agent.skills.create",
    "name": "rudder_agent_skills_create",
    "description": "Create an agent-private skill package under AGENT_HOME/skills.",
    "mutating": true,
    "requiresOrgId": false,
    "requiresAgentId": false,
    "attachesRunIdWhenAvailable": true
  },
  {
    "capabilityId": "agent.skills.enable",
    "name": "rudder_agent_skills_enable",
    "description": "Add skill selections to an agent without replacing existing enabled skills.",
    "mutating": true,
    "requiresOrgId": false,
    "requiresAgentId": false,
    "attachesRunIdWhenAvailable": true
  },
  {
    "capabilityId": "agent.skills.sync",
    "name": "rudder_agent_skills_sync",
    "description": "Sync the desired enabled skill set for an agent.",
    "mutating": true,
    "requiresOrgId": false,
    "requiresAgentId": false,
    "attachesRunIdWhenAvailable": true
  },
  {
    "capabilityId": "goal.list",
    "name": "rudder_goal_list",
    "description": "Discover Goals owned by the authenticated Agent; defaults to active Goals and returns current progress, next step, and attention state.",
    "mutating": false,
    "requiresOrgId": true,
    "requiresAgentId": true,
    "attachesRunIdWhenAvailable": false
  },
  {
    "capabilityId": "goal.context",
    "name": "rudder_goal_context",
    "description": "Read the owned Goal agreement and current operating context before acting: contract revision, criteria, boundaries, progress, next step, attention, proposals, and recent feedback.",
    "mutating": false,
    "requiresOrgId": false,
    "requiresAgentId": true,
    "attachesRunIdWhenAvailable": false
  },
  {
    "capabilityId": "goal.progress",
    "name": "rudder_goal_progress",
    "description": "Record evidence-backed progress for a Goal owned by the authenticated Agent and attribute it to the current Run.",
    "mutating": true,
    "requiresOrgId": false,
    "requiresAgentId": true,
    "attachesRunIdWhenAvailable": true
  },
  {
    "capabilityId": "goal.checkpoint",
    "name": "rudder_goal_checkpoint",
    "description": "Atomically persist a Goal checkpoint, optional Plan revision, continuation, checkpoint activity, and eligible automatic continuation wake.",
    "mutating": true,
    "requiresOrgId": false,
    "requiresAgentId": true,
    "attachesRunIdWhenAvailable": true
  },
  {
    "capabilityId": "goal.change.propose",
    "name": "rudder_goal_change_propose",
    "description": "Propose a reviewable change to the current Goal contract when evidence shows its outcome, criteria, boundaries, or deadlines should change.",
    "mutating": true,
    "requiresOrgId": false,
    "requiresAgentId": true,
    "attachesRunIdWhenAvailable": true
  },
  {
    "capabilityId": "goal.result.propose",
    "name": "rudder_goal_result_propose",
    "description": "Submit an evidence-backed Goal result for mandatory human acceptance without closing the Goal.",
    "mutating": true,
    "requiresOrgId": false,
    "requiresAgentId": true,
    "attachesRunIdWhenAvailable": true
  },
  {
    "capabilityId": "issue.get",
    "name": "rudder_issue_get",
    "description": "Read a full issue by UUID or identifier.",
    "mutating": false,
    "requiresOrgId": false,
    "requiresAgentId": false,
    "attachesRunIdWhenAvailable": false
  },
  {
    "capabilityId": "issue.list",
    "name": "rudder_issue_list",
    "description": "List issues with optional status, assignee, and project filters without requiring a search query.",
    "mutating": false,
    "requiresOrgId": true,
    "requiresAgentId": false,
    "attachesRunIdWhenAvailable": false
  },
  {
    "capabilityId": "issue.search",
    "name": "rudder_issue_search",
    "description": "Search issues with the server-side issue index across title, identifier, description, and comments.",
    "mutating": false,
    "requiresOrgId": true,
    "requiresAgentId": false,
    "attachesRunIdWhenAvailable": false
  },
  {
    "capabilityId": "issue.context",
    "name": "rudder_issue_context",
    "description": "Read the compact heartbeat context for an issue; wake comments may be addressed by full id or cmt_<uuid-prefix>.",
    "mutating": false,
    "requiresOrgId": false,
    "requiresAgentId": false,
    "attachesRunIdWhenAvailable": false
  },
  {
    "capabilityId": "issue.checkout",
    "name": "rudder_issue_checkout",
    "description": "Atomically checkout an issue for the current or specified agent.",
    "mutating": true,
    "requiresOrgId": false,
    "requiresAgentId": true,
    "attachesRunIdWhenAvailable": true
  },
  {
    "capabilityId": "issue.comment",
    "name": "rudder_issue_comment",
    "description": "Add a comment to an issue, optionally uploading images and appending Markdown image links.",
    "mutating": true,
    "requiresOrgId": false,
    "requiresAgentId": false,
    "attachesRunIdWhenAvailable": true
  },
  {
    "capabilityId": "issue.comments.list",
    "name": "rudder_issue_comments_list",
    "description": "List issue comments, optionally only newer comments after a full comment id or cmt_<uuid-prefix> with --after.",
    "mutating": false,
    "requiresOrgId": false,
    "requiresAgentId": false,
    "attachesRunIdWhenAvailable": false
  },
  {
    "capabilityId": "issue.comments.get",
    "name": "rudder_issue_comments_get",
    "description": "Read one issue comment by full id or cmt_<uuid-prefix> scoped to the issue.",
    "mutating": false,
    "requiresOrgId": false,
    "requiresAgentId": false,
    "attachesRunIdWhenAvailable": false
  },
  {
    "capabilityId": "issue.update",
    "name": "rudder_issue_update",
    "description": "Apply generic issue updates when workflow commands are not enough, optionally uploading images for the update comment.",
    "mutating": true,
    "requiresOrgId": false,
    "requiresAgentId": false,
    "attachesRunIdWhenAvailable": true
  },
  {
    "capabilityId": "issue.review",
    "name": "rudder_issue_review",
    "description": "Record a structured reviewer decision with a required comment.",
    "mutating": true,
    "requiresOrgId": false,
    "requiresAgentId": false,
    "attachesRunIdWhenAvailable": true
  },
  {
    "capabilityId": "issue.commit",
    "name": "rudder_issue_commit",
    "description": "Report a code commit created during issue work as structured issue activity.",
    "mutating": true,
    "requiresOrgId": false,
    "requiresAgentId": false,
    "attachesRunIdWhenAvailable": true
  },
  {
    "capabilityId": "issue.done",
    "name": "rudder_issue_done",
    "description": "Mark an issue done with a required completion comment, optionally uploading images.",
    "mutating": true,
    "requiresOrgId": false,
    "requiresAgentId": false,
    "attachesRunIdWhenAvailable": true
  },
  {
    "capabilityId": "issue.block",
    "name": "rudder_issue_block",
    "description": "Request human assistance after bounded recovery attempts; repeated matching claims are audited before the Issue becomes blocked.",
    "mutating": true,
    "requiresOrgId": false,
    "requiresAgentId": false,
    "attachesRunIdWhenAvailable": true
  },
  {
    "capabilityId": "project.list",
    "name": "rudder_project_list",
    "description": "List projects in an organization.",
    "mutating": false,
    "requiresOrgId": true,
    "requiresAgentId": false,
    "attachesRunIdWhenAvailable": false
  },
  {
    "capabilityId": "project.get",
    "name": "rudder_project_get",
    "description": "Read one project by ID or shortname.",
    "mutating": false,
    "requiresOrgId": false,
    "requiresAgentId": false,
    "attachesRunIdWhenAvailable": false
  },
  {
    "capabilityId": "project.create",
    "name": "rudder_project_create",
    "description": "Create a project in the organization.",
    "mutating": true,
    "requiresOrgId": true,
    "requiresAgentId": false,
    "attachesRunIdWhenAvailable": true
  },
  {
    "capabilityId": "project.update",
    "name": "rudder_project_update",
    "description": "Update mutable project fields such as name, description, status, goals, lead agent, target date, color, or archivedAt.",
    "mutating": true,
    "requiresOrgId": false,
    "requiresAgentId": false,
    "attachesRunIdWhenAvailable": true
  },
  {
    "capabilityId": "user.activity",
    "name": "rudder_user_activity",
    "description": "Read a user-centered activity ledger with safe excerpts and provenance across chats, issue comments, approval comments, and user actor activity.",
    "mutating": false,
    "requiresOrgId": true,
    "requiresAgentId": false,
    "attachesRunIdWhenAvailable": false
  },
  {
    "capabilityId": "library.file.list",
    "name": "rudder_library_file_list",
    "description": "List Library files and folders; file rows include `libraryEntryId` when a strong reference can be generated.",
    "mutating": false,
    "requiresOrgId": true,
    "requiresAgentId": false,
    "attachesRunIdWhenAvailable": false
  },
  {
    "capabilityId": "library.file.get",
    "name": "rudder_library_file_get",
    "description": "Fallback read when local filesystem access is unavailable; JSON includes `mentionHref` and `markdownLink`.",
    "mutating": false,
    "requiresOrgId": true,
    "requiresAgentId": false,
    "attachesRunIdWhenAvailable": false
  },
  {
    "capabilityId": "library.file.ref",
    "name": "rudder_library_file_ref",
    "description": "Return the stable Markdown reference for one Library file without printing file content.",
    "mutating": false,
    "requiresOrgId": true,
    "requiresAgentId": false,
    "attachesRunIdWhenAvailable": false
  },
  {
    "capabilityId": "library.file.link",
    "name": "rudder_library_file_link",
    "description": "Compatibility alias for `rudder library file ref <path>`.",
    "mutating": false,
    "requiresOrgId": true,
    "requiresAgentId": false,
    "attachesRunIdWhenAvailable": false
  },
  {
    "capabilityId": "library.file.put",
    "name": "rudder_library_file_put",
    "description": "Fallback create/update when local filesystem access is unavailable; JSON includes `mentionHref` and `markdownLink`.",
    "mutating": true,
    "requiresOrgId": true,
    "requiresAgentId": false,
    "attachesRunIdWhenAvailable": true
  },
  {
    "capabilityId": "issue.create",
    "name": "rudder_issue_create",
    "description": "Create a new issue or subtask with the generic issue surface; agent-created issues default to the creating agent when no assignee is supplied.",
    "mutating": true,
    "requiresOrgId": true,
    "requiresAgentId": false,
    "attachesRunIdWhenAvailable": true
  },
  {
    "capabilityId": "approval.get",
    "name": "rudder_approval_get",
    "description": "Read one approval request.",
    "mutating": false,
    "requiresOrgId": false,
    "requiresAgentId": false,
    "attachesRunIdWhenAvailable": false
  },
  {
    "capabilityId": "approval.issues",
    "name": "rudder_approval_issues",
    "description": "List the issues linked to an approval.",
    "mutating": false,
    "requiresOrgId": false,
    "requiresAgentId": false,
    "attachesRunIdWhenAvailable": false
  },
  {
    "capabilityId": "approval.comment",
    "name": "rudder_approval_comment",
    "description": "Add a comment to an approval.",
    "mutating": true,
    "requiresOrgId": false,
    "requiresAgentId": false,
    "attachesRunIdWhenAvailable": true
  },
  {
    "capabilityId": "skill.list",
    "name": "rudder_skill_list",
    "description": "List organization-visible skills.",
    "mutating": false,
    "requiresOrgId": true,
    "requiresAgentId": false,
    "attachesRunIdWhenAvailable": false
  },
  {
    "capabilityId": "skill.get",
    "name": "rudder_skill_get",
    "description": "Read one organization skill detail.",
    "mutating": false,
    "requiresOrgId": true,
    "requiresAgentId": false,
    "attachesRunIdWhenAvailable": false
  },
  {
    "capabilityId": "skill.file",
    "name": "rudder_skill_file",
    "description": "Read one file from an organization skill package.",
    "mutating": false,
    "requiresOrgId": true,
    "requiresAgentId": false,
    "attachesRunIdWhenAvailable": false
  },
  {
    "capabilityId": "skill.import",
    "name": "rudder_skill_import",
    "description": "Import a skill package into the organization skill library.",
    "mutating": true,
    "requiresOrgId": true,
    "requiresAgentId": false,
    "attachesRunIdWhenAvailable": true
  },
  {
    "capabilityId": "skill.scan-local",
    "name": "rudder_skill_scan_local",
    "description": "Scan local roots for skill packages and import new ones.",
    "mutating": true,
    "requiresOrgId": true,
    "requiresAgentId": false,
    "attachesRunIdWhenAvailable": true
  },
  {
    "capabilityId": "skill.scan-projects",
    "name": "rudder_skill_scan_projects",
    "description": "Scan the org workspace and any legacy project workspace records for skill packages and import new ones.",
    "mutating": true,
    "requiresOrgId": true,
    "requiresAgentId": false,
    "attachesRunIdWhenAvailable": true
  },
  {
    "capabilityId": "browser.tabs",
    "name": "rudder_browser_tabs",
    "description": "List Browser tabs owned by the current Rudder agent run.",
    "mutating": false,
    "requiresOrgId": true,
    "requiresAgentId": true,
    "attachesRunIdWhenAvailable": false
  },
  {
    "capabilityId": "browser.user-tabs",
    "name": "rudder_browser_user_tabs",
    "description": "List user-visible tabs currently open in Rudder's built-in Browser without taking control of them.",
    "mutating": false,
    "requiresOrgId": true,
    "requiresAgentId": true,
    "attachesRunIdWhenAvailable": false
  },
  {
    "capabilityId": "browser.open",
    "name": "rudder_browser_open",
    "description": "Open a run-owned tab in the Rudder Browser.",
    "mutating": true,
    "requiresOrgId": true,
    "requiresAgentId": true,
    "attachesRunIdWhenAvailable": true
  },
  {
    "capabilityId": "browser.navigate",
    "name": "rudder_browser_navigate",
    "description": "Navigate a run-owned Rudder Browser tab.",
    "mutating": true,
    "requiresOrgId": true,
    "requiresAgentId": true,
    "attachesRunIdWhenAvailable": true
  },
  {
    "capabilityId": "browser.back",
    "name": "rudder_browser_back",
    "description": "Navigate a run-owned Rudder Browser tab back in history.",
    "mutating": true,
    "requiresOrgId": true,
    "requiresAgentId": true,
    "attachesRunIdWhenAvailable": true
  },
  {
    "capabilityId": "browser.forward",
    "name": "rudder_browser_forward",
    "description": "Navigate a run-owned Rudder Browser tab forward in history.",
    "mutating": true,
    "requiresOrgId": true,
    "requiresAgentId": true,
    "attachesRunIdWhenAvailable": true
  },
  {
    "capabilityId": "browser.reload",
    "name": "rudder_browser_reload",
    "description": "Reload a run-owned Rudder Browser tab.",
    "mutating": true,
    "requiresOrgId": true,
    "requiresAgentId": true,
    "attachesRunIdWhenAvailable": true
  },
  {
    "capabilityId": "browser.viewport",
    "name": "rudder_browser_viewport",
    "description": "Inspect, set, or reset the responsive viewport for the current Rudder Browser run.",
    "mutating": true,
    "requiresOrgId": true,
    "requiresAgentId": true,
    "attachesRunIdWhenAvailable": true
  },
  {
    "capabilityId": "browser.visibility",
    "name": "rudder_browser_visibility",
    "description": "Inspect or change whether the current run's selected Rudder Browser tab is visible.",
    "mutating": true,
    "requiresOrgId": true,
    "requiresAgentId": true,
    "attachesRunIdWhenAvailable": true
  },
  {
    "capabilityId": "browser.snapshot",
    "name": "rudder_browser_snapshot",
    "description": "Capture a bounded DOM and accessibility-oriented snapshot, including frame structure and ephemeral node ids.",
    "mutating": false,
    "requiresOrgId": true,
    "requiresAgentId": true,
    "attachesRunIdWhenAvailable": true
  },
  {
    "capabilityId": "browser.locator",
    "name": "rudder_browser_locator",
    "description": "Perform read-only bounded Browser locator text, attribute, state, count, or wait operations.",
    "mutating": false,
    "requiresOrgId": true,
    "requiresAgentId": true,
    "attachesRunIdWhenAvailable": true
  },
  {
    "capabilityId": "browser.cua",
    "name": "rudder_browser_cua",
    "description": "Perform trusted coordinate mouse, scroll, drag, keyboard, and text input in a run-owned Browser tab.",
    "mutating": true,
    "requiresOrgId": true,
    "requiresAgentId": true,
    "attachesRunIdWhenAvailable": true
  },
  {
    "capabilityId": "browser.dom-cua",
    "name": "rudder_browser_dom_cua",
    "description": "Inspect a bounded read-only DOM snapshot with ephemeral node ids.",
    "mutating": false,
    "requiresOrgId": true,
    "requiresAgentId": true,
    "attachesRunIdWhenAvailable": true
  },
  {
    "capabilityId": "browser.dialog",
    "name": "rudder_browser_dialog",
    "description": "Inspect, accept, or dismiss the active JavaScript dialog in a run-owned Browser tab.",
    "mutating": true,
    "requiresOrgId": true,
    "requiresAgentId": true,
    "attachesRunIdWhenAvailable": true
  },
  {
    "capabilityId": "browser.clipboard",
    "name": "rudder_browser_clipboard",
    "description": "Read or write the isolated virtual clipboard for the current Browser run without touching the OS clipboard.",
    "mutating": true,
    "requiresOrgId": true,
    "requiresAgentId": true,
    "attachesRunIdWhenAvailable": true
  },
  {
    "capabilityId": "browser.logs",
    "name": "rudder_browser_logs",
    "description": "Read bounded console and runtime logs captured for a run-owned Browser tab.",
    "mutating": true,
    "requiresOrgId": true,
    "requiresAgentId": true,
    "attachesRunIdWhenAvailable": true
  },
  {
    "capabilityId": "browser.download",
    "name": "rudder_browser_download",
    "description": "Download explicit locator media without dispatching page input into a bounded run-owned artifact.",
    "mutating": true,
    "requiresOrgId": true,
    "requiresAgentId": true,
    "attachesRunIdWhenAvailable": true
  },
  {
    "capabilityId": "browser.assets",
    "name": "rudder_browser_assets",
    "description": "List page assets or bundle an explicit bounded selection into a run-owned temporary artifact.",
    "mutating": true,
    "requiresOrgId": true,
    "requiresAgentId": true,
    "attachesRunIdWhenAvailable": true
  },
  {
    "capabilityId": "browser.content",
    "name": "rudder_browser_content",
    "description": "Export current page content or an eligible Google Workspace document into a bounded run-owned artifact.",
    "mutating": true,
    "requiresOrgId": true,
    "requiresAgentId": true,
    "attachesRunIdWhenAvailable": true
  },
  {
    "capabilityId": "browser.wait",
    "name": "rudder_browser_wait",
    "description": "Wait for bounded URL, text, disappearance, or time conditions in a run-owned Browser tab.",
    "mutating": false,
    "requiresOrgId": true,
    "requiresAgentId": true,
    "attachesRunIdWhenAvailable": true
  },
  {
    "capabilityId": "browser.read",
    "name": "rudder_browser_read",
    "description": "Read a structured snapshot from a run-owned Rudder Browser tab.",
    "mutating": false,
    "requiresOrgId": true,
    "requiresAgentId": true,
    "attachesRunIdWhenAvailable": false
  },
  {
    "capabilityId": "browser.click",
    "name": "rudder_browser_click",
    "description": "Click an element reference returned by Rudder Browser read.",
    "mutating": true,
    "requiresOrgId": true,
    "requiresAgentId": true,
    "attachesRunIdWhenAvailable": true
  },
  {
    "capabilityId": "browser.type",
    "name": "rudder_browser_type",
    "description": "Type into an element reference in a run-owned Rudder Browser tab.",
    "mutating": true,
    "requiresOrgId": true,
    "requiresAgentId": true,
    "attachesRunIdWhenAvailable": true
  },
  {
    "capabilityId": "browser.screenshot",
    "name": "rudder_browser_screenshot",
    "description": "Capture a screenshot of a run-owned Rudder Browser tab.",
    "mutating": false,
    "requiresOrgId": true,
    "requiresAgentId": true,
    "attachesRunIdWhenAvailable": false
  },
  {
    "capabilityId": "browser.close",
    "name": "rudder_browser_close",
    "description": "Close a run-owned Rudder Browser tab.",
    "mutating": true,
    "requiresOrgId": true,
    "requiresAgentId": true,
    "attachesRunIdWhenAvailable": true
  },
  {
    "capabilityId": "automation.list",
    "name": "rudder_automation_list",
    "description": "List automations for an organization with compact local filters.",
    "mutating": false,
    "requiresOrgId": true,
    "requiresAgentId": false,
    "attachesRunIdWhenAvailable": false
  },
  {
    "capabilityId": "automation.get",
    "name": "rudder_automation_get",
    "description": "Read one automation detail including triggers and recent runs.",
    "mutating": false,
    "requiresOrgId": false,
    "requiresAgentId": false,
    "attachesRunIdWhenAvailable": false
  },
  {
    "capabilityId": "automation.runs",
    "name": "rudder_automation_runs",
    "description": "List recent runs for one automation.",
    "mutating": false,
    "requiresOrgId": false,
    "requiresAgentId": false,
    "attachesRunIdWhenAvailable": false
  },
  {
    "capabilityId": "automation.triggers.list",
    "name": "rudder_automation_triggers_list",
    "description": "List triggers configured for one automation.",
    "mutating": false,
    "requiresOrgId": false,
    "requiresAgentId": false,
    "attachesRunIdWhenAvailable": false
  },
  {
    "capabilityId": "automation.triggers.create",
    "name": "rudder_automation_triggers_create",
    "description": "Create a schedule, webhook, or API trigger through the governed automation API.",
    "mutating": true,
    "requiresOrgId": false,
    "requiresAgentId": false,
    "attachesRunIdWhenAvailable": true
  },
  {
    "capabilityId": "automation.triggers.update",
    "name": "rudder_automation_triggers_update",
    "description": "Update an automation trigger through the governed automation API.",
    "mutating": true,
    "requiresOrgId": false,
    "requiresAgentId": false,
    "attachesRunIdWhenAvailable": true
  },
  {
    "capabilityId": "automation.triggers.delete",
    "name": "rudder_automation_triggers_delete",
    "description": "Delete an automation trigger through the governed automation API.",
    "mutating": true,
    "requiresOrgId": false,
    "requiresAgentId": false,
    "attachesRunIdWhenAvailable": true
  },
  {
    "capabilityId": "automation.triggers.rotate-secret",
    "name": "rudder_automation_triggers_rotate_secret",
    "description": "Rotate an automation webhook trigger secret through the governed automation API.",
    "mutating": true,
    "requiresOrgId": false,
    "requiresAgentId": false,
    "attachesRunIdWhenAvailable": true
  },
  {
    "capabilityId": "automation.create",
    "name": "rudder_automation_create",
    "description": "Create an automation through the governed automation API.",
    "mutating": true,
    "requiresOrgId": true,
    "requiresAgentId": false,
    "attachesRunIdWhenAvailable": true
  },
  {
    "capabilityId": "automation.update",
    "name": "rudder_automation_update",
    "description": "Update automation fields through the governed automation API.",
    "mutating": true,
    "requiresOrgId": false,
    "requiresAgentId": false,
    "attachesRunIdWhenAvailable": true
  },
  {
    "capabilityId": "automation.enable",
    "name": "rudder_automation_enable",
    "description": "Enable an automation by setting status to active.",
    "mutating": true,
    "requiresOrgId": false,
    "requiresAgentId": false,
    "attachesRunIdWhenAvailable": true
  },
  {
    "capabilityId": "automation.disable",
    "name": "rudder_automation_disable",
    "description": "Disable an automation by setting status to paused.",
    "mutating": true,
    "requiresOrgId": false,
    "requiresAgentId": false,
    "attachesRunIdWhenAvailable": true
  },
  {
    "capabilityId": "automation.run",
    "name": "rudder_automation_run",
    "description": "Trigger a manual automation run.",
    "mutating": true,
    "requiresOrgId": false,
    "requiresAgentId": false,
    "attachesRunIdWhenAvailable": true
  },
  {
    "capabilityId": "chat.list",
    "name": "rudder_chat_list",
    "description": "List chat conversations without dumping full message history.",
    "mutating": false,
    "requiresOrgId": true,
    "requiresAgentId": false,
    "attachesRunIdWhenAvailable": false
  },
  {
    "capabilityId": "chat.search",
    "name": "rudder_chat_search",
    "description": "Search chats with bounded snippets and optional scope filtering.",
    "mutating": false,
    "requiresOrgId": true,
    "requiresAgentId": false,
    "attachesRunIdWhenAvailable": false
  },
  {
    "capabilityId": "chat.get",
    "name": "rudder_chat_get",
    "description": "Read one chat conversation record.",
    "mutating": false,
    "requiresOrgId": false,
    "requiresAgentId": false,
    "attachesRunIdWhenAvailable": false
  },
  {
    "capabilityId": "chat.messages",
    "name": "rudder_chat_messages",
    "description": "Read bounded chat messages with page cursors; transcript output is omitted unless requested.",
    "mutating": false,
    "requiresOrgId": false,
    "requiresAgentId": false,
    "attachesRunIdWhenAvailable": false
  },
  {
    "capabilityId": "chat.transcript",
    "name": "rudder_chat_transcript",
    "description": "Read paginated chat messages with assistant transcript entries clipped in human output.",
    "mutating": false,
    "requiresOrgId": false,
    "requiresAgentId": false,
    "attachesRunIdWhenAvailable": false
  },
  {
    "capabilityId": "chat.read",
    "name": "rudder_chat_read",
    "description": "Read a bounded recent-message snapshot for one chat with page cursors.",
    "mutating": false,
    "requiresOrgId": false,
    "requiresAgentId": false,
    "attachesRunIdWhenAvailable": false
  },
  {
    "capabilityId": "chat.create",
    "name": "rudder_chat_create",
    "description": "Create a chat conversation with its first message.",
    "mutating": true,
    "requiresOrgId": true,
    "requiresAgentId": false,
    "attachesRunIdWhenAvailable": true
  },
  {
    "capabilityId": "chat.send",
    "name": "rudder_chat_send",
    "description": "Send an agent-authored message directly to the operator in a chat.",
    "mutating": true,
    "requiresOrgId": false,
    "requiresAgentId": true,
    "attachesRunIdWhenAvailable": true
  },
  {
    "capabilityId": "chat.archive",
    "name": "rudder_chat_archive",
    "description": "Archive a chat conversation without deleting it.",
    "mutating": true,
    "requiresOrgId": false,
    "requiresAgentId": false,
    "attachesRunIdWhenAvailable": true
  },
  {
    "capabilityId": "runs.list",
    "name": "rudder_runs_list",
    "description": "List lightweight run summaries with stable pagination and filters; use --full only for legacy full-row compatibility.",
    "mutating": false,
    "requiresOrgId": true,
    "requiresAgentId": false,
    "attachesRunIdWhenAvailable": false
  },
  {
    "capabilityId": "runs.by-skill",
    "name": "rudder_runs_by_skill",
    "description": "Build a paginated skill evidence packet from lightweight run summaries; use --full only for legacy full-row compatibility.",
    "mutating": false,
    "requiresOrgId": true,
    "requiresAgentId": false,
    "attachesRunIdWhenAvailable": false
  },
  {
    "capabilityId": "runs.get",
    "name": "rudder_runs_get",
    "description": "Read one bounded run summary; use --full only from a direct trusted CLI for raw detail.",
    "mutating": false,
    "requiresOrgId": false,
    "requiresAgentId": false,
    "attachesRunIdWhenAvailable": false
  },
  {
    "capabilityId": "runs.events",
    "name": "rudder_runs_events",
    "description": "List a bounded page of persisted run events with a lossless opaque cursor and clipped payload previews.",
    "mutating": false,
    "requiresOrgId": false,
    "requiresAgentId": false,
    "attachesRunIdWhenAvailable": false
  },
  {
    "capabilityId": "runs.log",
    "name": "rudder_runs_log",
    "description": "Read a bounded byte range of stored run log content.",
    "mutating": false,
    "requiresOrgId": false,
    "requiresAgentId": false,
    "attachesRunIdWhenAvailable": false
  },
  {
    "capabilityId": "runs.transcript",
    "name": "rudder_runs_transcript",
    "description": "Read a compact server-normalized transcript; --json changes encoding only and --full is direct-CLI-only raw access.",
    "mutating": false,
    "requiresOrgId": false,
    "requiresAgentId": false,
    "attachesRunIdWhenAvailable": false
  },
  {
    "capabilityId": "runs.errors",
    "name": "rudder_runs_errors",
    "description": "List failed tool calls, stderr, runtime failures, and jump-to-context commands.",
    "mutating": false,
    "requiresOrgId": false,
    "requiresAgentId": false,
    "attachesRunIdWhenAvailable": false
  },
  {
    "capabilityId": "runs.cancel",
    "name": "rudder_runs_cancel",
    "description": "Cancel a heartbeat run through the governed server route.",
    "mutating": true,
    "requiresOrgId": false,
    "requiresAgentId": false,
    "attachesRunIdWhenAvailable": true
  },
  {
    "capabilityId": "runs.retry",
    "name": "rudder_runs_retry",
    "description": "Retry a failed, timed out, or cancelled run through the governed server route.",
    "mutating": true,
    "requiresOrgId": false,
    "requiresAgentId": false,
    "attachesRunIdWhenAvailable": true
  }
] as const;
export const GENERATED_RUDDER_CORE_MCP_CONTRACT_HASH = "b70b3cc3508c81a0c046f3478d6a57daf094cb58608b7a16ff648daceba12475";
export const GENERATED_RUDDER_BROWSER_MCP_CONTRACT_HASH = "640c060df9ef9ae3c649d973d123fdcfc0d1456217cbe1ec48dbba337de75923";
