// Generated by scripts/generate-rudder-mcp-tool-descriptors.ts. Do not edit by hand.
import { GENERATED_RUDDER_MCP_TOOL_DESCRIPTORS_000 } from "./contract-shards/rudder-mcp-tool-descriptors-000.js";
import { GENERATED_RUDDER_MCP_TOOL_DESCRIPTORS_001 } from "./contract-shards/rudder-mcp-tool-descriptors-001.js";
import { GENERATED_RUDDER_MCP_TOOL_DESCRIPTORS_002 } from "./contract-shards/rudder-mcp-tool-descriptors-002.js";
import { GENERATED_RUDDER_MCP_TOOL_DESCRIPTORS_003 } from "./contract-shards/rudder-mcp-tool-descriptors-003.js";
import { GENERATED_RUDDER_MCP_TOOL_DESCRIPTORS_004 } from "./contract-shards/rudder-mcp-tool-descriptors-004.js";
export const RUDDER_MCP_TOOL_DESCRIPTORS = [
  {
    "capabilityId": "agent.me",
    "name": "rudder_agent_me",
    "description": "Show the authenticated agent identity and budget.",
    "semanticDescription": "Show the authenticated agent identity and budget. Mutating: no. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: not required by this tool. Agent context: runtime env when available. Run attribution: not attached.",
    "annotations": {
      "destructiveHint": false,
      "idempotentHint": true,
      "readOnlyHint": true,
      "title": "Show the authenticated agent identity and budget"
    },
    "mutating": false,
    "requiresOrgId": false,
    "requiresAgentId": false,
    "attachesRunIdWhenAvailable": false,
    "inputSchema": {
      "additionalProperties": false,
      "properties": {},
      "type": "object"
    }
  },
  {
    "capabilityId": "agent.inbox",
    "name": "rudder_agent_inbox",
    "description": "List the compact assignee and reviewer work inbox for the authenticated agent.",
    "semanticDescription": "List the compact assignee and reviewer work inbox for the authenticated agent. Mutating: no. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: not required by this tool. Agent context: runtime env when available. Run attribution: not attached.",
    "annotations": {
      "destructiveHint": false,
      "idempotentHint": true,
      "readOnlyHint": true,
      "title": "List the compact assignee and reviewer work inbox for the authenticated agent"
    },
    "mutating": false,
    "requiresOrgId": false,
    "requiresAgentId": false,
    "attachesRunIdWhenAvailable": false,
    "inputSchema": {
      "additionalProperties": false,
      "properties": {},
      "type": "object"
    }
  },
  {
    "capabilityId": "organization.members.list",
    "name": "rudder_organization_members_list",
    "description": "List active visible human and agent members in the authenticated organization.",
    "semanticDescription": "List active visible human and agent members in the authenticated organization. Mutating: no. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: required from runtime env. Agent context: runtime env when available. Run attribution: not attached.",
    "annotations": {
      "destructiveHint": false,
      "idempotentHint": true,
      "readOnlyHint": true,
      "title": "List active visible human and agent members in the authenticated organization"
    },
    "mutating": false,
    "requiresOrgId": true,
    "requiresAgentId": false,
    "attachesRunIdWhenAvailable": false,
    "inputSchema": {
      "additionalProperties": false,
      "properties": {
        "cursor": {
          "description": "Opaque pagination cursor.",
          "maxLength": 2000,
          "minLength": 1,
          "type": "string"
        },
        "limit": {
          "description": "Page size.",
          "maximum": 100,
          "minimum": 1,
          "type": "number"
        },
        "query": {
          "description": "Optional member name filter.",
          "maxLength": 2000,
          "minLength": 1,
          "type": "string"
        },
        "type": {
          "description": "Member type filter.",
          "enum": [
            "human",
            "agent",
            "all"
          ],
          "maxLength": 10,
          "minLength": 1,
          "type": "string"
        }
      },
      "type": "object"
    }
  },
  {
    "capabilityId": "organization.brand_color.update",
    "name": "rudder_organization_brand_color_update",
    "description": "Update the authenticated organization's brand color.",
    "semanticDescription": "Update the authenticated organization's brand color. Mutating: yes. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: required from runtime env. Agent context: runtime env when available. Run attribution: attached from runtime env when available.",
    "annotations": {
      "destructiveHint": false,
      "idempotentHint": true,
      "readOnlyHint": false,
      "title": "Update the authenticated organization's brand color"
    },
    "mutating": true,
    "requiresOrgId": true,
    "requiresAgentId": false,
    "attachesRunIdWhenAvailable": true,
    "inputSchema": {
      "additionalProperties": false,
      "properties": {
        "brandColor": {
          "description": "Hex brand color, for example #123456.",
          "maxLength": 7,
          "minLength": 7,
          "type": "string"
        },
        "idempotencyKey": {
          "description": "Required stable key for safe replay.",
          "maxLength": 255,
          "minLength": 1,
          "type": "string"
        }
      },
      "required": [
        "brandColor",
        "idempotencyKey"
      ],
      "type": "object"
    }
  },
  {
    "capabilityId": "agent.capabilities",
    "name": "rudder_agent_capabilities",
    "description": "List the stable Rudder agent command contract.",
    "semanticDescription": "List the stable Rudder agent command contract. Mutating: no. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: not required by this tool. Agent context: runtime env when available. Run attribution: not attached.",
    "annotations": {
      "destructiveHint": false,
      "idempotentHint": true,
      "readOnlyHint": true,
      "title": "List the stable Rudder agent command contract"
    },
    "mutating": false,
    "requiresOrgId": false,
    "requiresAgentId": false,
    "attachesRunIdWhenAvailable": false,
    "inputSchema": {
      "additionalProperties": false,
      "properties": {},
      "type": "object"
    }
  },
  {
    "capabilityId": "agent.update",
    "name": "rudder_agent_update",
    "description": "Update an agent's identity fields; defaults to the authenticated agent.",
    "semanticDescription": "Update an agent's identity fields; defaults to the authenticated agent. Mutating: yes. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: not required by this tool. Agent context: runtime env when available. Run attribution: attached from runtime env when available.",
    "annotations": {
      "destructiveHint": false,
      "idempotentHint": false,
      "readOnlyHint": false,
      "title": "Update an agent's identity fields"
    },
    "mutating": true,
    "requiresOrgId": false,
    "requiresAgentId": false,
    "attachesRunIdWhenAvailable": true,
    "inputSchema": {
      "additionalProperties": false,
      "properties": {
        "capabilities": {
          "description": "Agent capability summary.",
          "maxLength": 100000,
          "minLength": 1,
          "type": "string"
        },
        "clearCapabilities": {
          "description": "Clear the current capability summary.",
          "type": "boolean"
        },
        "clearDescription": {
          "description": "Compatibility alias for clearCapabilities.",
          "type": "boolean"
        },
        "clearTitle": {
          "description": "Clear the current title.",
          "type": "boolean"
        },
        "description": {
          "description": "Compatibility alias for capabilities.",
          "maxLength": 100000,
          "minLength": 1,
          "type": "string"
        },
        "name": {
          "description": "Agent name.",
          "maxLength": 200,
          "minLength": 1,
          "type": "string"
        },
        "role": {
          "description": "Agent role.",
          "maxLength": 100,
          "minLength": 1,
          "type": "string"
        },
        "title": {
          "description": "Agent title.",
          "maxLength": 300,
          "minLength": 1,
          "type": "string"
        }
      },
      "type": "object"
    }
  },
  {
    "capabilityId": "agent.skills.create",
    "name": "rudder_agent_skills_create",
    "description": "Create an agent-private skill package under AGENT_HOME/skills.",
    "semanticDescription": "Create an agent-private skill package under AGENT_HOME/skills. Mutating: yes. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: not required by this tool. Agent context: runtime env when available. Run attribution: attached from runtime env when available.",
    "annotations": {
      "destructiveHint": false,
      "idempotentHint": false,
      "readOnlyHint": false,
      "title": "Create an agent-private skill package under AGENT_HOME/skills"
    },
    "mutating": true,
    "requiresOrgId": false,
    "requiresAgentId": false,
    "attachesRunIdWhenAvailable": true,
    "inputSchema": {
      "additionalProperties": false,
      "properties": {
        "body": {
          "description": "Compatibility alias for markdown.",
          "maxLength": 500000,
          "minLength": 1,
          "type": "string"
        },
        "description": {
          "description": "Skill description.",
          "maxLength": 100000,
          "minLength": 1,
          "type": "string"
        },
        "enable": {
          "description": "Enable the created skill for the runtime agent.",
          "type": "boolean"
        },
        "markdown": {
          "description": "SKILL.md content.",
          "maxLength": 500000,
          "minLength": 1,
          "type": "string"
        },
        "name": {
          "description": "Skill display name.",
          "maxLength": 200,
          "minLength": 1,
          "type": "string"
        },
        "slug": {
          "description": "Skill slug.",
          "maxLength": 200,
          "minLength": 1,
          "type": "string"
        }
      },
      "required": [
        "name"
      ],
      "type": "object"
    }
  },
  {
    "capabilityId": "agent.skills.enable",
    "name": "rudder_agent_skills_enable",
    "description": "Add skill selections to an agent without replacing existing enabled skills.",
    "semanticDescription": "Add skill selections to an agent without replacing existing enabled skills. Mutating: yes. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: not required by this tool. Agent context: runtime env when available. Run attribution: attached from runtime env when available.",
    "annotations": {
      "destructiveHint": false,
      "idempotentHint": false,
      "readOnlyHint": false,
      "title": "Add skill selections to an agent without replacing existing enabled skills"
    },
    "mutating": true,
    "requiresOrgId": false,
    "requiresAgentId": false,
    "attachesRunIdWhenAvailable": true,
    "inputSchema": {
      "additionalProperties": false,
      "properties": {
        "selectionRefs": {
          "description": "Skill selection references.",
          "items": {
            "description": "Skill selection references.",
            "maxLength": 8192,
            "minLength": 1,
            "type": "string"
          },
          "maxItems": 100,
          "type": "array"
        }
      },
      "required": [
        "selectionRefs"
      ],
      "type": "object"
    }
  },
  {
    "capabilityId": "agent.skills.sync",
    "name": "rudder_agent_skills_sync",
    "description": "Sync the desired enabled skill set for an agent.",
    "semanticDescription": "Sync the desired enabled skill set for an agent. Mutating: yes. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: not required by this tool. Agent context: runtime env when available. Run attribution: attached from runtime env when available.",
    "annotations": {
      "destructiveHint": true,
      "idempotentHint": false,
      "readOnlyHint": false,
      "title": "Sync the desired enabled skill set for an agent"
    },
    "mutating": true,
    "requiresOrgId": false,
    "requiresAgentId": false,
    "attachesRunIdWhenAvailable": true,
    "inputSchema": {
      "additionalProperties": false,
      "properties": {
        "desiredSkills": {
          "description": "Comma-separated desired skill references.",
          "maxLength": 20000,
          "minLength": 1,
          "type": "string"
        }
      },
      "required": [
        "desiredSkills"
      ],
      "type": "object"
    }
  },
  {
    "capabilityId": "goal.list",
    "name": "rudder_goal_list",
    "description": "Discover Goals owned by the authenticated Agent; defaults to active Goals and returns current progress, next step, and attention state.",
    "semanticDescription": "Discover Goals owned by the authenticated Agent; defaults to active Goals and returns current progress, next step, and attention state. Mutating: no. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: required from runtime env. Agent context: required from runtime env. Run attribution: not attached.",
    "annotations": {
      "destructiveHint": false,
      "idempotentHint": true,
      "readOnlyHint": true,
      "title": "Discover Goals owned by the authenticated Agent"
    },
    "mutating": false,
    "requiresOrgId": true,
    "requiresAgentId": true,
    "attachesRunIdWhenAvailable": false,
    "inputSchema": {
      "additionalProperties": false,
      "properties": {
        "facet": {
          "description": "Current Goal workspace facet.",
          "enum": [
            "agent_advancing",
            "needs_attention",
            "waiting_focus",
            "waiting_external",
            "ready_for_acceptance",
            "closed"
          ],
          "maxLength": 40,
          "minLength": 1,
          "type": "string"
        },
        "focus": {
          "description": "Filter by whether the Goal is the organization Focus Goal.",
          "type": "boolean"
        },
        "lifecycle": {
          "description": "Goal lifecycle filter; active is the safe default.",
          "enum": [
            "draft",
            "active",
            "closed",
            "all"
          ],
          "maxLength": 20,
          "minLength": 1,
          "type": "string"
        },
        "limit": {
          "description": "Maximum owned Goals to return.",
          "maximum": 100,
          "minimum": 1,
          "type": "number"
        }
      },
      "type": "object"
    }
  },
  {
    "capabilityId": "goal.context",
    "name": "rudder_goal_context",
    "description": "Read the owned Goal agreement and current operating context before acting: contract revision, criteria, boundaries, progress, next step, attention, proposals, and recent feedback.",
    "semanticDescription": "Read the owned Goal agreement and current operating context before acting: contract revision, criteria, boundaries, progress, next step, attention, proposals, and recent feedback. Mutating: no. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: not required by this tool. Agent context: required from runtime env. Run attribution: not attached.",
    "annotations": {
      "destructiveHint": false,
      "idempotentHint": true,
      "readOnlyHint": true,
      "title": "Read the owned Goal agreement and current operating context before acting: contract revision, criteria, boundaries, progress, next step, attention, proposals, and recent feedback"
    },
    "mutating": false,
    "requiresOrgId": false,
    "requiresAgentId": true,
    "attachesRunIdWhenAvailable": false,
    "inputSchema": {
      "additionalProperties": false,
      "properties": {
        "goal": {
          "description": "Goal UUID returned by rudder_goal_list.",
          "maxLength": 200,
          "minLength": 1,
          "type": "string"
        }
      },
      "required": [
        "goal"
      ],
      "type": "object"
    }
  },
  {
    "capabilityId": "goal.progress",
    "name": "rudder_goal_progress",
    "description": "Record evidence-backed progress for a Goal owned by the authenticated Agent and attribute it to the current Run.",
    "semanticDescription": "Record evidence-backed progress for a Goal owned by the authenticated Agent and attribute it to the current Run. Mutating: yes. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: not required by this tool. Agent context: required from runtime env. Run attribution: attached from runtime env when available.",
    "annotations": {
      "destructiveHint": false,
      "idempotentHint": false,
      "readOnlyHint": false,
      "title": "Record evidence-backed progress for a Goal owned by the authenticated Agent and attribute it to the current Run"
    },
    "mutating": true,
    "requiresOrgId": false,
    "requiresAgentId": true,
    "attachesRunIdWhenAvailable": true,
    "inputSchema": {
      "additionalProperties": false,
      "properties": {
        "activityKind": {
          "description": "Progress classification.",
          "enum": [
            "progress",
            "evidence",
            "bottleneck"
          ],
          "maxLength": 30,
          "minLength": 1,
          "type": "string"
        },
        "evidenceRefs": {
          "description": "URI-like references to artifacts, measurements, or other supporting evidence.",
          "items": {
            "description": "URI-like evidence reference.",
            "maxLength": 8192,
            "minLength": 1,
            "type": "string"
          },
          "maxItems": 100,
          "minItems": 1,
          "type": "array"
        },
        "goal": {
          "description": "Goal UUID or typed short reference (gol_<prefix>) from the current Goal Runtime Context.",
          "maxLength": 200,
          "minLength": 1,
          "type": "string"
        },
        "idempotencyKey": {
          "description": "Stable key for safe retry.",
          "maxLength": 500,
          "minLength": 1,
          "type": "string"
        },
        "summary": {
          "description": "Plain-language progress, observed change, or named blocker.",
          "maxLength": 100000,
          "minLength": 1,
          "type": "string"
        }
      },
      "required": [
        "goal",
        "summary",
        "evidenceRefs",
        "idempotencyKey"
      ],
      "type": "object"
    }
  },
  {
    "capabilityId": "goal.checkpoint",
    "name": "rudder_goal_checkpoint",
    "description": "Atomically persist a Goal checkpoint, optional Plan revision, continuation, checkpoint activity, and eligible automatic continuation wake.",
    "semanticDescription": "Atomically persist a Goal checkpoint, optional Plan revision, continuation, checkpoint activity, and eligible automatic continuation wake. Mutating: yes. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: not required by this tool. Agent context: required from runtime env. Run attribution: attached from runtime env when available.",
    "annotations": {
      "destructiveHint": false,
      "idempotentHint": false,
      "readOnlyHint": false,
      "title": "Atomically persist a Goal checkpoint, optional Plan revision, continuation, checkpoint activity, and eligible automatic continuation wake"
    },
    "mutating": true,
    "requiresOrgId": false,
    "requiresAgentId": true,
    "attachesRunIdWhenAvailable": true,
    "inputSchema": {
      "additionalProperties": false,
      "properties": {
        "continuation": {
          "additionalProperties": false,
          "properties": {
            "kind": {
              "description": "Continuation policy.",
              "enum": [
                "commitment",
                "wait",
                "decision",
                "verification"
              ],
              "maxLength": 100000,
              "minLength": 1,
              "type": "string"
            },
            "summary": {
              "description": "What should happen next or what is awaited.",
              "maxLength": 100000,
              "minLength": 1,
              "type": "string"
            },
            "wakeCondition": {
              "oneOf": [
                {
                  "minLength": 1,
                  "type": "string"
                },
                {
                  "type": "null"
                }
              ]
            }
          },
          "required": [
            "kind",
            "summary"
          ],
          "type": "object"
        },
        "evidenceRefs": {
          "description": "URI-like references to artifacts, measurements, or other supporting evidence.",
          "items": {
            "description": "URI-like evidence reference.",
            "maxLength": 8192,
            "minLength": 1,
            "type": "string"
          },
          "maxItems": 100,
          "type": "array"
        },
        "expectedPlanRevision": {
          "description": "Plan revision read before this checkpoint.",
          "maximum": 1000000000,
          "minimum": 1,
          "type": "number"
        },
        "goal": {
          "description": "Goal UUID or typed short reference (gol_<prefix>) from the current Goal Runtime Context.",
          "maxLength": 200,
          "minLength": 1,
          "type": "string"
        },
        "idempotencyKey": {
          "description": "Stable key for safe retry.",
          "maxLength": 500,
          "minLength": 1,
          "type": "string"
        },
        "plan": {
          "additionalProperties": false,
          "description": "Optional complete next Plan revision; omit when the current Plan remains valid.",
          "properties": {
            "budgetAllocations": {
              "additionalProperties": true,
              "type": "object"
            },
            "hypotheses": {
              "items": {},
              "maxItems": 1000,
              "type": "array"
            },
            "invalidationConditions": {
              "items": {},
              "maxItems": 1000,
              "type": "array"
            },
            "rejectedPaths": {
              "items": {},
              "maxItems": 1000,
              "type": "array"
            },
            "selectedPaths": {
              "items": {},
              "maxItems": 1000,
              "type": "array"
            },
            "sequencing": {
              "items": {},
              "maxItems": 1000,
              "type": "array"
            },
            "summary": {
              "description": "Plan summary.",
              "maxLength": 100000,
              "minLength": 1,
              "type": "string"
            }
          },
          "required": [
            "summary"
          ],
          "type": "object"
        },
        "summary": {
          "description": "Plain-language bounded-run checkpoint summary.",
          "maxLength": 100000,
          "minLength": 1,
          "type": "string"
        }
      },
      "required": [
        "goal",
        "summary",
        "evidenceRefs",
        "expectedPlanRevision",
        "continuation",
        "idempotencyKey"
      ],
      "type": "object"
    }
  },
  {
    "capabilityId": "goal.change.propose",
    "name": "rudder_goal_change_propose",
    "description": "Propose a reviewable change to the current Goal contract when evidence shows its outcome, criteria, boundaries, or deadlines should change.",
    "semanticDescription": "Propose a reviewable change to the current Goal contract when evidence shows its outcome, criteria, boundaries, or deadlines should change. Mutating: yes. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: not required by this tool. Agent context: required from runtime env. Run attribution: attached from runtime env when available.",
    "annotations": {
      "destructiveHint": false,
      "idempotentHint": false,
      "readOnlyHint": false,
      "title": "Propose a reviewable change to the current Goal contract when evidence shows its outcome, criteria, boundaries, or deadlines should change"
    },
    "mutating": true,
    "requiresOrgId": false,
    "requiresAgentId": true,
    "attachesRunIdWhenAvailable": true,
    "inputSchema": {
      "additionalProperties": false,
      "properties": {
        "afterContract": {
          "additionalProperties": false,
          "description": "Only the Goal contract fields that should change.",
          "minProperties": 1,
          "properties": {
            "actionDeadline": {
              "description": "Proposed ISO-8601 action deadline, or null to clear it.",
              "oneOf": [
                {
                  "format": "date-time",
                  "type": "string"
                },
                {
                  "type": "null"
                }
              ]
            },
            "autonomyEnvelope": {
              "additionalProperties": true,
              "type": "object"
            },
            "criteria": {
              "items": {
                "additionalProperties": false,
                "properties": {
                  "evaluator": {
                    "description": "Criterion evaluator.",
                    "enum": [
                      "artifact",
                      "metric",
                      "policy",
                      "human"
                    ],
                    "maxLength": 20,
                    "minLength": 1,
                    "type": "string"
                  },
                  "evidenceRequirements": {
                    "items": {
                      "description": "URI-like required evidence reference.",
                      "maxLength": 8192,
                      "minLength": 1,
                      "type": "string"
                    },
                    "maxItems": 100,
                    "type": "array"
                  },
                  "id": {
                    "description": "Stable criterion id.",
                    "maxLength": 500,
                    "minLength": 1,
                    "type": "string"
                  },
                  "label": {
                    "description": "Plain-language success criterion.",
                    "maxLength": 100000,
                    "minLength": 1,
                    "type": "string"
                  }
                },
                "required": [
                  "id",
                  "label",
                  "evaluator"
                ],
                "type": "object"
              },
              "maxItems": 100,
              "minItems": 1,
              "type": "array"
            },
            "evaluationDeadline": {
              "description": "Proposed ISO-8601 evaluation deadline, or null to clear it.",
              "oneOf": [
                {
                  "format": "date-time",
                  "type": "string"
                },
                {
                  "type": "null"
                }
              ]
            },
            "evaluationPolicy": {
              "additionalProperties": true,
              "type": "object"
            },
            "humanAuthorities": {
              "additionalProperties": true,
              "type": "object"
            },
            "objectiveMode": {
              "description": "Proposed objective mode.",
              "enum": [
                "target",
                "maximize",
                "maintain",
                "decide"
              ],
              "maxLength": 20,
              "minLength": 1,
              "type": "string"
            },
            "outcomeStatement": {
              "description": "Proposed result-oriented outcome.",
              "maxLength": 100000,
              "minLength": 1,
              "type": "string"
            }
          },
          "type": "object"
        },
        "contractRevision": {
          "description": "Current Goal contract revision.",
          "maximum": 1000000000,
          "minimum": 1,
          "type": "number"
        },
        "evidenceRefs": {
          "description": "URI-like references supporting the proposed change.",
          "items": {
            "description": "URI-like evidence reference.",
            "maxLength": 8192,
            "minLength": 1,
            "type": "string"
          },
          "maxItems": 100,
          "type": "array"
        },
        "goal": {
          "description": "Goal UUID or typed short reference (gol_<prefix>) from the current Goal Runtime Context.",
          "maxLength": 200,
          "minLength": 1,
          "type": "string"
        },
        "idempotencyKey": {
          "description": "Stable key for safe retry.",
          "maxLength": 500,
          "minLength": 1,
          "type": "string"
        },
        "rationale": {
          "description": "Why the current contract should change and what evidence invalidated it.",
          "maxLength": 100000,
          "minLength": 1,
          "type": "string"
        }
      },
      "required": [
        "goal",
        "contractRevision",
        "afterContract",
        "rationale",
        "idempotencyKey"
      ],
      "type": "object"
    }
  },
  {
    "capabilityId": "goal.result.propose",
    "name": "rudder_goal_result_propose",
    "description": "Submit an evidence-backed Goal result for mandatory human acceptance without closing the Goal.",
    "semanticDescription": "Submit an evidence-backed Goal result for mandatory human acceptance without closing the Goal. Mutating: yes. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: not required by this tool. Agent context: required from runtime env. Run attribution: attached from runtime env when available.",
    "annotations": {
      "destructiveHint": false,
      "idempotentHint": false,
      "readOnlyHint": false,
      "title": "Submit an evidence-backed Goal result for mandatory human acceptance without closing the Goal"
    },
    "mutating": true,
    "requiresOrgId": false,
    "requiresAgentId": true,
    "attachesRunIdWhenAvailable": true,
    "inputSchema": {
      "additionalProperties": false,
      "properties": {
        "contractRevision": {
          "description": "Current Goal contract revision.",
          "maximum": 1000000000,
          "minimum": 1,
          "type": "number"
        },
        "criteria": {
          "description": "Criterion outcomes for the current contract revision.",
          "items": {
            "additionalProperties": false,
            "properties": {
              "id": {
                "description": "Criterion id from the Goal Runtime Context.",
                "maxLength": 500,
                "minLength": 1,
                "type": "string"
              },
              "status": {
                "description": "Observed criterion status.",
                "enum": [
                  "met",
                  "unmet",
                  "breached",
                  "unknown"
                ],
                "maxLength": 20,
                "minLength": 1,
                "type": "string"
              }
            },
            "required": [
              "id",
              "status"
            ],
            "type": "object"
          },
          "maxItems": 100,
          "minItems": 1,
          "type": "array"
        },
        "decision": {
          "description": "Optional decision reached for decide-mode Goals.",
          "maxLength": 100000,
          "minLength": 1,
          "type": "string"
        },
        "evidenceRefs": {
          "description": "URI-like references supporting the proposed result.",
          "items": {
            "description": "URI-like evidence reference.",
            "maxLength": 8192,
            "minLength": 1,
            "type": "string"
          },
          "maxItems": 100,
          "minItems": 1,
          "type": "array"
        },
        "goal": {
          "description": "Goal UUID or typed short reference (gol_<prefix>) from the current Goal Runtime Context.",
          "maxLength": 200,
          "minLength": 1,
          "type": "string"
        },
        "idempotencyKey": {
          "description": "Stable key for safe retry.",
          "maxLength": 500,
          "minLength": 1,
          "type": "string"
        },
        "resultPayload": {
          "additionalProperties": true,
          "description": "Optional structured result details.",
          "type": "object"
        },
        "resultValue": {
          "description": "Optional measured result value.",
          "oneOf": [
            {
              "maxLength": 100000,
              "type": "string"
            },
            {
              "type": "number"
            },
            {
              "type": "boolean"
            }
          ]
        },
        "riskSummary": {
          "description": "Known risks, limitations, or remaining gaps.",
          "maxLength": 100000,
          "minLength": 1,
          "type": "string"
        }
      },
      "required": [
        "goal",
        "contractRevision",
        "criteria",
        "evidenceRefs",
        "riskSummary",
        "idempotencyKey"
      ],
      "type": "object"
    }
  },
  {
    "capabilityId": "issue.get",
    "name": "rudder_issue_get",
    "description": "Read a full issue by UUID or identifier.",
    "semanticDescription": "Read a full issue by UUID or identifier. Mutating: no. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: not required by this tool. Agent context: runtime env when available. Run attribution: not attached.",
    "annotations": {
      "destructiveHint": false,
      "idempotentHint": true,
      "readOnlyHint": true,
      "title": "Read a full issue by UUID or identifier"
    },
    "mutating": false,
    "requiresOrgId": false,
    "requiresAgentId": false,
    "attachesRunIdWhenAvailable": false,
    "inputSchema": {
      "additionalProperties": false,
      "properties": {
        "issue": {
          "description": "Issue UUID, identifier, or short reference.",
          "maxLength": 200,
          "minLength": 1,
          "type": "string"
        }
      },
      "required": [
        "issue"
      ],
      "type": "object"
    }
  },
  {
    "capabilityId": "issue.list",
    "name": "rudder_issue_list",
    "description": "List issues with optional status, assignee, and project filters without requiring a search query.",
    "semanticDescription": "List issues with optional status, assignee, and project filters without requiring a search query. Mutating: no. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: required from runtime env. Agent context: runtime env when available. Run attribution: not attached.",
    "annotations": {
      "destructiveHint": false,
      "idempotentHint": true,
      "readOnlyHint": true,
      "title": "List issues with optional status, assignee, and project filters without requiring a search query"
    },
    "mutating": false,
    "requiresOrgId": true,
    "requiresAgentId": false,
    "attachesRunIdWhenAvailable": false,
    "inputSchema": {
      "additionalProperties": false,
      "properties": {
        "assigneeAgentId": {
          "description": "Assignee agent id or reference.",
          "maxLength": 200,
          "minLength": 1,
          "type": "string"
        },
        "projectId": {
          "description": "Project id or reference.",
          "maxLength": 200,
          "minLength": 1,
          "type": "string"
        },
        "status": {
          "description": "Comma-separated issue statuses.",
          "maxLength": 500,
          "minLength": 1,
          "type": "string"
        }
      },
      "type": "object"
    }
  },
  {
    "capabilityId": "issue.search",
    "name": "rudder_issue_search",
    "description": "Search issues with the server-side issue index across title, identifier, description, and comments.",
    "semanticDescription": "Search issues with the server-side issue index across title, identifier, description, and comments. Mutating: no. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: required from runtime env. Agent context: runtime env when available. Run attribution: not attached.",
    "annotations": {
      "destructiveHint": false,
      "idempotentHint": true,
      "readOnlyHint": true,
      "title": "Search issues with the server-side issue index across title, identifier, description, and comments"
    },
    "mutating": false,
    "requiresOrgId": true,
    "requiresAgentId": false,
    "attachesRunIdWhenAvailable": false,
    "inputSchema": {
      "additionalProperties": false,
      "properties": {
        "assigneeAgentId": {
          "description": "Assignee agent id or reference.",
          "maxLength": 200,
          "minLength": 1,
          "type": "string"
        },
        "projectId": {
          "description": "Project id or reference.",
          "maxLength": 200,
          "minLength": 1,
          "type": "string"
        },
        "query": {
          "description": "Non-empty server-side issue search query.",
          "maxLength": 2000,
          "minLength": 1,
          "type": "string"
        },
        "status": {
          "description": "Comma-separated issue statuses.",
          "maxLength": 500,
          "minLength": 1,
          "type": "string"
        }
      },
      "required": [
        "query"
      ],
      "type": "object"
    }
  },
  {
    "capabilityId": "issue.context",
    "name": "rudder_issue_context",
    "description": "Read the compact heartbeat context for an issue; wake comments may be addressed by full id or cmt_<uuid-prefix>.",
    "semanticDescription": "Read the compact heartbeat context for an issue; wake comments may be addressed by full id or cmt_<uuid-prefix>. Mutating: no. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: not required by this tool. Agent context: runtime env when available. Run attribution: not attached.",
    "annotations": {
      "destructiveHint": false,
      "idempotentHint": true,
      "readOnlyHint": true,
      "title": "Read the compact heartbeat context for an issue"
    },
    "mutating": false,
    "requiresOrgId": false,
    "requiresAgentId": false,
    "attachesRunIdWhenAvailable": false,
    "inputSchema": {
      "additionalProperties": false,
      "properties": {
        "issue": {
          "description": "Issue UUID, identifier, or short reference.",
          "maxLength": 200,
          "minLength": 1,
          "type": "string"
        },
        "wakeCommentId": {
          "description": "Wake comment id or short reference.",
          "maxLength": 200,
          "minLength": 1,
          "type": "string"
        }
      },
      "required": [
        "issue"
      ],
      "type": "object"
    }
  },
  {
    "capabilityId": "issue.checkout",
    "name": "rudder_issue_checkout",
    "description": "Atomically checkout an issue for the current or specified agent.",
    "semanticDescription": "Atomically checkout an issue for the current or specified agent. Mutating: yes. Runtime identity and authorization are injected by the Rudder-managed MCP server and are not accepted as tool input. Org context: not required by this tool. Agent context: required from runtime env. Run attribution: attached from runtime env when available.",
    "annotations": {
      "destructiveHint": false,
      "idempotentHint": false,
      "readOnlyHint": false,
      "title": "Atomically checkout an issue for the current or specified agent"
    },
    "mutating": true,
    "requiresOrgId": false,
    "requiresAgentId": true,
    "attachesRunIdWhenAvailable": true,
    "inputSchema": {
      "additionalProperties": false,
      "properties": {
        "expectedStatuses": {
          "description": "Comma-separated allowed prior statuses.",
          "maxLength": 500,
          "minLength": 1,
          "type": "string"
        },
        "issue": {
          "description": "Issue UUID, identifier, or short reference.",
          "maxLength": 200,
          "minLength": 1,
          "type": "string"
        }
      },
      "required": [
        "issue"
      ],
      "type": "object"
    }
  },
  ...GENERATED_RUDDER_MCP_TOOL_DESCRIPTORS_000,
  ...GENERATED_RUDDER_MCP_TOOL_DESCRIPTORS_001,
  ...GENERATED_RUDDER_MCP_TOOL_DESCRIPTORS_002,
  ...GENERATED_RUDDER_MCP_TOOL_DESCRIPTORS_003,
  ...GENERATED_RUDDER_MCP_TOOL_DESCRIPTORS_004
] as const;
export const GENERATED_RUDDER_CORE_MCP_CONTRACT_HASH = "ab5f3638133b155f8637f5cc271ca8042ed238a420101a47ede2aaded8ca4a82";
export const GENERATED_RUDDER_BROWSER_MCP_CONTRACT_HASH = "640c060df9ef9ae3c649d973d123fdcfc0d1456217cbe1ec48dbba337de75923";
export const GENERATED_RUDDER_AGENT_CONTRACT_HASH = "40640159976a63bd4971f8a5c4b29842eb95ffa769fac290d26abf2c24418bb4";
