packages:
  - packages/*
  - packages/agent-runtimes/*
  - packages/plugins/*
  - packages/plugins/examples/*
  - server
  - ui
  - cli
  - desktop
allowBuilds:
  '@embedded-postgres/darwin-arm64': true
  electron: true
  electron-winstaller: true
  es5-ext: true
  esbuild: true
  protobufjs: true
  sharp: true
