// @vitest-environment jsdom

import type { HeartbeatRun } from "@rudderhq/shared";
import { act, type ReactNode } from "react";
import { createRoot, type Root } from "react-dom/client";
import { afterEach, describe, expect, it, vi } from "vitest";
import { RunIssueReportDialog } from "./RunIssueReportDialog";

(globalThis as typeof globalThis & { IS_REACT_ACT_ENVIRONMENT?: boolean }).IS_REACT_ACT_ENVIRONMENT = true;

vi.mock("@/components/ui/button", () => ({
  Button: ({ children, ...props }: { children: ReactNode }) => <button {...props}>{children}</button>,
}));

vi.mock("@/components/ui/dialog", () => ({
  Dialog: ({ children, open }: { children: ReactNode; open: boolean }) => open ? children : null,
  DialogContent: ({ children, className }: { children: ReactNode; className?: string }) => (
    <div role="dialog" aria-label="Report this run failure" className={className}>{children}</div>
  ),
  DialogDescription: ({ children }: { children: ReactNode }) => <p>{children}</p>,
  DialogFooter: ({ children }: { children: ReactNode }) => <div>{children}</div>,
  DialogHeader: ({ children }: { children: ReactNode }) => <div>{children}</div>,
  DialogTitle: ({ children }: { children: ReactNode }) => <h2>{children}</h2>,
}));

vi.mock("@/components/ui/dropdown-menu", () => ({
  DropdownMenu: ({ children }: { children: ReactNode }) => <div>{children}</div>,
  DropdownMenuContent: ({ children }: { children: ReactNode }) => <div role="menu">{children}</div>,
  DropdownMenuItem: ({ children, onSelect }: { children: ReactNode; onSelect?: () => void }) => (
    <button type="button" role="menuitem" onClick={() => onSelect?.()}>{children}</button>
  ),
  DropdownMenuTrigger: ({ children }: { children: ReactNode }) => children,
}));

vi.mock("@/lib/desktop-shell", () => ({
  readDesktopShell: () => null,
}));

function createRun(overrides: Partial<HeartbeatRun> = {}): HeartbeatRun {
  return {
    id: "run-1",
    orgId: "org-1",
    agentId: "agent-1",
    invocationSource: "on_demand",
    triggerDetail: "manual",
    status: "failed",
    startedAt: new Date("2026-08-05T08:00:00.000Z"),
    finishedAt: new Date("2026-08-05T08:01:00.000Z"),
    error: "The adapter failed.",
    wakeupRequestId: null,
    exitCode: 1,
    signal: null,
    usageJson: null,
    resultJson: null,
    sessionIdBefore: null,
    sessionIdAfter: null,
    sessionReuseScope: "none",
    logStore: null,
    logRef: null,
    logBytes: null,
    logSha256: null,
    logCompressed: false,
    stdoutExcerpt: Array.from({ length: 120 }, (_, index) => `stdout line ${index} ${"diagnostic output ".repeat(12)}`).join("\n"),
    stderrExcerpt: null,
    errorCode: "adapter_failed",
    externalRunId: null,
    chatConversationId: null,
    goalId: null,
    processPid: null,
    processStartedAt: null,
    retryOfRunId: null,
    processLossRetryCount: 0,
    contextSnapshot: { scene: "issue", issueId: "issue-1" },
    createdAt: new Date("2026-08-05T08:00:00.000Z"),
    updatedAt: new Date("2026-08-05T08:01:00.000Z"),
    ...overrides,
  };
}

describe("RunIssueReportDialog", () => {
  let root: Root | null = null;
  let container: HTMLDivElement | null = null;

  afterEach(() => {
    if (root) act(() => root?.unmount());
    container?.remove();
    root = null;
    container = null;
    vi.restoreAllMocks();
  });

  it("keeps long diagnostics in a bounded, scrollable textarea", async () => {
    container = document.createElement("div");
    document.body.appendChild(container);
    root = createRoot(container);

    await act(async () => {
      root?.render(
        <RunIssueReportDialog
          run={createRun()}
          version="0.7.2"
          environment="test"
          open
          onOpenChange={() => undefined}
          onAskAgent={() => undefined}
          onCreateTask={async () => undefined}
        />,
      );
    });

    const diagnostics = container.querySelector<HTMLTextAreaElement>("#run-issue-diagnostics");
    expect(diagnostics).not.toBeNull();
    expect(diagnostics?.value).toContain("Safe diagnostics generated by Rudder");
    expect(diagnostics?.value.length).toBeGreaterThan(1_000);
    expect(diagnostics?.className).toContain("field-sizing-fixed");
    expect(diagnostics?.className).toContain("scrollbar-auto-hide");
    expect(diagnostics?.className).toContain("min-h-[min(18rem,45dvh)]");
    expect(diagnostics?.className).toContain("min-w-0");
    expect(diagnostics?.className).toContain("max-h-[min(22rem,45dvh)]");
    expect(diagnostics?.className).toContain("overflow-x-hidden");
    expect(diagnostics?.className).toContain("overflow-y-auto");
    expect(diagnostics?.className).toContain("whitespace-pre-wrap");
    expect(diagnostics?.className).toContain("break-all");
    expect(diagnostics?.className).not.toContain("field-sizing-content");
  });

  it("offers explicit Debug modes and sends the generated snapshot to Chat", async () => {
    container = document.createElement("div");
    document.body.appendChild(container);
    root = createRoot(container);
    const onAskAgent = vi.fn();
    const onCreateTask = vi.fn(async () => undefined);

    await act(async () => {
      root?.render(
        <RunIssueReportDialog
          run={createRun()}
          version="0.7.2"
          environment="test"
          open
          onOpenChange={() => undefined}
          onAskAgent={onAskAgent}
          onCreateTask={onCreateTask}
        />,
      );
    });

    const diagnostics = container.querySelector<HTMLTextAreaElement>("#run-issue-diagnostics")!;
    const generatedSnapshot = diagnostics.value;
    await act(async () => {
      const valueSetter = Object.getOwnPropertyDescriptor(HTMLTextAreaElement.prototype, "value")?.set;
      valueSetter?.call(diagnostics, "Edited GitHub-only report");
      diagnostics.dispatchEvent(new Event("input", { bubbles: true }));
    });
    await act(async () => {
      Array.from(container!.querySelectorAll("button"))
        .find((button) => button.textContent?.includes("Start chat"))
        ?.click();
    });

    expect(onAskAgent).toHaveBeenCalledOnce();
    expect(onAskAgent).toHaveBeenCalledWith(generatedSnapshot);
    expect(onAskAgent).not.toHaveBeenCalledWith("Edited GitHub-only report");
    expect(onCreateTask).not.toHaveBeenCalled();
    expect(container.textContent).toContain("Create task");
    expect(container.textContent).toContain("Start chat");
  });

  it("locks task creation while pending and reports a recoverable failure", async () => {
    container = document.createElement("div");
    document.body.appendChild(container);
    root = createRoot(container);
    let rejectFirst!: (error: Error) => void;
    const firstAttempt = new Promise<void>((_resolve, reject) => {
      rejectFirst = reject;
    });
    const onCreateTask = vi.fn()
      .mockImplementationOnce(() => firstAttempt)
      .mockResolvedValueOnce(undefined);
    const onOpenChange = vi.fn();

    await act(async () => {
      root?.render(
        <RunIssueReportDialog
          run={createRun()}
          version="0.7.2"
          environment="test"
          open
          onOpenChange={onOpenChange}
          onAskAgent={() => undefined}
          onCreateTask={onCreateTask}
        />,
      );
    });

    const createTask = Array.from(container.querySelectorAll("button"))
      .find((button) => button.textContent?.includes("Create task"))!;
    await act(async () => {
      createTask.click();
      createTask.click();
    });
    expect(onCreateTask).toHaveBeenCalledOnce();
    expect(container.textContent).toContain("Creating task");

    await act(async () => rejectFirst(new Error("Task service unavailable")));
    expect(container.querySelector('[role="alert"]')?.textContent).toContain("Task service unavailable");
    expect(onOpenChange).not.toHaveBeenCalledWith(false);

    await act(async () => createTask.click());
    expect(onCreateTask).toHaveBeenCalledTimes(2);
    expect(onOpenChange).toHaveBeenCalledWith(false);
  });
});
