// @vitest-environment jsdom

import type { HeartbeatRun } from "@rudderhq/shared";
import { act, type ReactNode } from "react";
import { createRoot, type Root } from "react-dom/client";
import { afterEach, describe, expect, it, vi } from "vitest";
import { RunIssueReportDialog } from "./RunIssueReportDialog";

(globalThis as typeof globalThis & { IS_REACT_ACT_ENVIRONMENT?: boolean }).IS_REACT_ACT_ENVIRONMENT = true;

vi.mock("@/components/ui/button", () => ({
  Button: ({ children, ...props }: { children: ReactNode }) => <button {...props}>{children}</button>,
}));

vi.mock("@/components/ui/dialog", () => ({
  Dialog: ({ children, open }: { children: ReactNode; open: boolean }) => open ? children : null,
  DialogContent: ({ children, className }: { children: ReactNode; className?: string }) => (
    <div role="dialog" aria-label="Report this run failure" className={className}>{children}</div>
  ),
  DialogDescription: ({ children }: { children: ReactNode }) => <p>{children}</p>,
  DialogFooter: ({ children }: { children: ReactNode }) => <div>{children}</div>,
  DialogHeader: ({ children }: { children: ReactNode }) => <div>{children}</div>,
  DialogTitle: ({ children }: { children: ReactNode }) => <h2>{children}</h2>,
}));

vi.mock("@/lib/desktop-shell", () => ({
  readDesktopShell: () => null,
}));

function createRun(overrides: Partial<HeartbeatRun> = {}): HeartbeatRun {
  return {
    id: "run-1",
    orgId: "org-1",
    agentId: "agent-1",
    invocationSource: "on_demand",
    triggerDetail: "manual",
    status: "failed",
    startedAt: new Date("2026-08-05T08:00:00.000Z"),
    finishedAt: new Date("2026-08-05T08:01:00.000Z"),
    error: "The adapter failed.",
    wakeupRequestId: null,
    exitCode: 1,
    signal: null,
    usageJson: null,
    resultJson: null,
    sessionIdBefore: null,
    sessionIdAfter: null,
    sessionReuseScope: "none",
    logStore: null,
    logRef: null,
    logBytes: null,
    logSha256: null,
    logCompressed: false,
    stdoutExcerpt: Array.from({ length: 120 }, (_, index) => `stdout line ${index} ${"diagnostic output ".repeat(12)}`).join("\n"),
    stderrExcerpt: null,
    errorCode: "adapter_failed",
    externalRunId: null,
    chatConversationId: null,
    goalId: null,
    processPid: null,
    processStartedAt: null,
    retryOfRunId: null,
    processLossRetryCount: 0,
    contextSnapshot: { scene: "issue", issueId: "issue-1" },
    createdAt: new Date("2026-08-05T08:00:00.000Z"),
    updatedAt: new Date("2026-08-05T08:01:00.000Z"),
    ...overrides,
  };
}

describe("RunIssueReportDialog", () => {
  let root: Root | null = null;
  let container: HTMLDivElement | null = null;

  afterEach(() => {
    if (root) act(() => root?.unmount());
    container?.remove();
    root = null;
    container = null;
    vi.restoreAllMocks();
  });

  it("keeps long diagnostics in a bounded, scrollable textarea", async () => {
    container = document.createElement("div");
    document.body.appendChild(container);
    root = createRoot(container);

    await act(async () => {
      root?.render(
        <RunIssueReportDialog
          run={createRun()}
          version="0.7.2"
          environment="test"
          open
          onOpenChange={() => undefined}
        />,
      );
    });

    const diagnostics = container.querySelector<HTMLTextAreaElement>("#run-issue-diagnostics");
    expect(diagnostics).not.toBeNull();
    expect(diagnostics?.value).toContain("Safe diagnostics generated by Rudder");
    expect(diagnostics?.value.length).toBeGreaterThan(1_000);
    expect(diagnostics?.className).toContain("field-sizing-fixed");
    expect(diagnostics?.className).toContain("scrollbar-auto-hide");
    expect(diagnostics?.className).toContain("min-h-[min(18rem,45dvh)]");
    expect(diagnostics?.className).toContain("min-w-0");
    expect(diagnostics?.className).toContain("max-h-[min(22rem,45dvh)]");
    expect(diagnostics?.className).toContain("overflow-x-hidden");
    expect(diagnostics?.className).toContain("overflow-y-auto");
    expect(diagnostics?.className).toContain("whitespace-pre-wrap");
    expect(diagnostics?.className).toContain("break-all");
    expect(diagnostics?.className).not.toContain("field-sizing-content");
  });
});
