import { boolean, index, integer, jsonb, pgTable, text, timestamp, uuid } from "drizzle-orm/pg-core";

export const productAnalyticsCollectorEvents = pgTable(
  "product_analytics_collector_events",
  {
    eventId: uuid("event_id").primaryKey(),
    installationId: text("installation_id").notNull(),
    analyticsSubject: text("analytics_subject"),
    eventName: text("event_name").notNull(),
    schemaVersion: integer("schema_version").notNull(),
    occurredAt: timestamp("occurred_at", { withTimezone: true }).notNull(),
    receivedAt: timestamp("received_at", { withTimezone: true }).notNull().defaultNow(),
    effectiveAt: timestamp("effective_at", { withTimezone: true }).notNull(),
    environment: text("environment").notNull(),
    appVersion: text("app_version").notNull(),
    releaseChannel: text("release_channel").notNull(),
    deploymentMode: text("deployment_mode").notNull(),
    coarsePlatform: text("coarse_platform"),
    actorKind: text("actor_kind").notNull(),
    origin: text("origin").notNull(),
    isInternal: boolean("is_internal").notNull().default(false),
    pseudonymousInstallationId: text("pseudonymous_installation_id"),
    pseudonymousOrgId: text("pseudonymous_org_id"),
    pseudonymousWorkId: text("pseudonymous_work_id"),
    pseudonymousWorkCycleId: text("pseudonymous_work_cycle_id"),
    pseudonymousRootRunId: text("pseudonymous_root_run_id"),
    pseudonymousRunId: text("pseudonymous_run_id"),
    completionRevision: integer("completion_revision"),
    properties: jsonb("properties").$type<Record<string, string | number | boolean | null>>().notNull().default({}),
    confidence: text("confidence").notNull(),
    isBackfill: boolean("is_backfill").notNull().default(false),
    late: boolean("late").notNull().default(false),
    consentVersion: text("consent_version").notNull(),
    consentEpoch: integer("consent_epoch").notNull(),
    payloadSha256: text("payload_sha256").notNull(),
  },
  (table) => ({
    installationOccurredIdx: index("product_analytics_collector_events_installation_occurred_idx").on(table.installationId, table.occurredAt),
    eventOccurredIdx: index("product_analytics_collector_events_event_occurred_idx").on(table.eventName, table.occurredAt),
    subjectOccurredIdx: index("product_analytics_collector_events_subject_occurred_idx").on(table.analyticsSubject, table.occurredAt),
  }),
);
