import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { getAgentCliCapabilities } from "../cli/src/agent-v1-registry.js";
import {
  rudderMcpInputSchemaForCapability,
  rudderMcpSemanticToolContract,
} from "../packages/agent-runtime-utils/src/rudder-mcp-contract.js";
import { fingerprintRudderMcpToolManifest } from "../packages/agent-runtime-utils/src/rudder-mcp-fingerprint.js";

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const outputPath = path.join(
  repoRoot,
  "packages/agent-runtime-utils/src/rudder-mcp-tool-descriptors.generated.ts",
);

function toolName(capabilityId: string): string {
  return `rudder_${capabilityId.replace(/[^a-zA-Z0-9]+/g, "_").replace(/^_+|_+$/g, "")}`;
}

function render(): string {
  const descriptors = getAgentCliCapabilities()
    .filter((capability) => capability.contract === "agent-v1")
    .map((capability) => ({
      capabilityId: capability.id,
      name: toolName(capability.id),
      description: capability.description,
      mutating: capability.mutating,
      requiresOrgId: capability.requiresOrgId,
      requiresAgentId: capability.requiresAgentId,
      attachesRunIdWhenAvailable: capability.attachesRunIdWhenAvailable,
    }));
  const semanticContracts = descriptors.map((descriptor) => rudderMcpSemanticToolContract({
    ...descriptor,
    inputSchema: rudderMcpInputSchemaForCapability(descriptor.capabilityId),
  }));
  const coreContractHash = fingerprintRudderMcpToolManifest(
    semanticContracts.filter((tool) => !tool.name.startsWith("rudder_browser_")),
  );
  const browserContractHash = fingerprintRudderMcpToolManifest(
    semanticContracts.filter((tool) => tool.name.startsWith("rudder_browser_")),
  );

  return [
    "// Generated by scripts/generate-rudder-mcp-tool-descriptors.ts. Do not edit by hand.",
    `export const RUDDER_MCP_TOOL_DESCRIPTORS = ${JSON.stringify(descriptors, null, 2)} as const;`,
    `export const GENERATED_RUDDER_CORE_MCP_CONTRACT_HASH = ${JSON.stringify(coreContractHash)};`,
    `export const GENERATED_RUDDER_BROWSER_MCP_CONTRACT_HASH = ${JSON.stringify(browserContractHash)};`,
    "",
  ].join("\n");
}

const expected = render();
if (process.argv.includes("--check")) {
  const actual = await readFile(outputPath, "utf8").catch(() => "");
  if (actual !== expected) {
    throw new Error("Rudder MCP tool descriptors are stale; run pnpm mcp-contract:generate");
  }
} else {
  await writeFile(outputPath, expected, "utf8");
}
