import { spawnSync } from "node:child_process";
import {
  cpSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  readdirSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { afterEach, describe, expect, it } from "vitest";

const scriptsDir = dirname(fileURLToPath(import.meta.url));
const tempRoots = [];

function writeJson(filePath, value) {
  writeFileSync(filePath, `${JSON.stringify(value, null, 2)}\n`);
}

function readJson(filePath) {
  return JSON.parse(readFileSync(filePath, "utf8"));
}

function createPackageMapRepo() {
  const repo = mkdtempSync(join(tmpdir(), "rudder-package-map-test-"));
  tempRoots.push(repo);

  mkdirSync(join(repo, "scripts"), { recursive: true });
  mkdirSync(join(repo, "packages", "shared"), { recursive: true });
  mkdirSync(join(repo, "native"), { recursive: true });
  mkdirSync(join(repo, "native", "crates", "native-protocol"), { recursive: true });
  mkdirSync(join(repo, "desktop"), { recursive: true });
  mkdirSync(join(repo, "cli", "src"), { recursive: true });
  cpSync(join(scriptsDir, "release-package-map.mjs"), join(repo, "scripts", "release-package-map.mjs"));
  writeFileSync(
    join(repo, "native", "Cargo.toml"),
    [
      "[workspace]",
      'members = ["crates/native-protocol"]',
      "",
      "[workspace.package]",
      'version = "0.2.10"',
      'edition = "2024"',
      "publish = false",
      "",
    ].join("\n"),
  );
  writeJson(join(repo, "desktop", "package.json"), {
    name: "@rudderhq/desktop",
    version: "0.2.10",
    private: true,
  });
  writeFileSync(
    join(repo, "cli", "src", "program.ts"),
    'const program = new Command().version("0.2.10");\n',
  );
  writeFileSync(
    join(repo, "native", "crates", "native-protocol", "Cargo.toml"),
    [
      "[package]",
      'name = "rudder-native-protocol"',
      "version.workspace = true",
      "edition.workspace = true",
      "",
    ].join("\n"),
  );
  writeFileSync(
    join(repo, "native", "Cargo.lock"),
    [
      "# This file is automatically @generated by Cargo.",
      "version = 4",
      "",
      "[[package]]",
      'name = "rudder-native-protocol"',
      'version = "0.2.10"',
      "",
    ].join("\n"),
  );

  const packagePath = join(repo, "packages", "shared", "package.json");
  writeJson(packagePath, {
    name: "@rudderhq/shared",
    version: "0.2.10",
    type: "module",
    exports: {
      ".": "./src/index.ts",
    },
    publishConfig: {
      access: "public",
      exports: {
        ".": {
          types: "./dist/index.d.ts",
          import: "./dist/index.js",
        },
      },
      main: "./dist/index.js",
      types: "./dist/index.d.ts",
    },
  });

  return { repo, packagePath };
}

function addPrivateWorkspaceDependency(repo, packagePath) {
  const privatePackageDir = join(repo, "identity");
  mkdirSync(privatePackageDir, { recursive: true });
  writeJson(join(privatePackageDir, "package.json"), {
    name: "@rudderhq/identity",
    version: "0.0.0",
    private: true,
  });

  const pkg = readJson(packagePath);
  writeJson(packagePath, {
    ...pkg,
    dependencies: {
      "@rudderhq/identity": "workspace:*",
    },
  });
}

function addPublicServerDependency(repo) {
  const serverDir = join(repo, "server");
  mkdirSync(serverDir, { recursive: true });
  const serverPackagePath = join(serverDir, "package.json");
  writeJson(serverPackagePath, {
    name: "@rudderhq/server",
    version: "0.2.10",
    dependencies: {
      "@rudderhq/shared": "workspace:*",
    },
  });
  return serverPackagePath;
}

function runPackageMap(repo, args) {
  return spawnSync("node", ["scripts/release-package-map.mjs", ...args], {
    cwd: repo,
    encoding: "utf8",
  });
}

function snapshotTree(root) {
  const snapshot = {};

  function walk(relativeDir) {
    const absoluteDir = join(root, relativeDir);
    for (const entry of readdirSync(absoluteDir, { withFileTypes: true })) {
      const relativePath = join(relativeDir, entry.name);
      if (entry.isDirectory()) {
        walk(relativePath);
      } else {
        snapshot[relativePath] = readFileSync(join(root, relativePath)).toString("base64");
      }
    }
  }

  walk("");
  return snapshot;
}

afterEach(() => {
  for (const root of tempRoots.splice(0)) {
    rmSync(root, { force: true, recursive: true });
  }
});

describe("release package map", () => {
  it("rejects public packages that depend on private workspace packages", () => {
    const { repo, packagePath } = createPackageMapRepo();
    addPrivateWorkspaceDependency(repo, packagePath);

    const result = runPackageMap(repo, ["list"]);

    expect(result.status).toBe(1);
    expect(result.stderr).toContain(
      "public package @rudderhq/shared depends on private workspace package @rudderhq/identity",
    );
  });

  it("rewrites public workspace dependencies to the exact publish version", () => {
    const { repo } = createPackageMapRepo();
    const serverPackagePath = addPublicServerDependency(repo);

    const result = runPackageMap(repo, [
      "set-publish-version",
      "0.2.11-canary.2",
      "--allow-source-mutation",
    ]);
    const manifest = readJson(serverPackagePath);

    expect(result.status).toBe(0);
    expect(manifest.version).toBe("0.2.11-canary.2");
    expect(manifest.dependencies["@rudderhq/shared"]).toBe("0.2.11-canary.2");
    expect(readFileSync(join(repo, "native", "Cargo.toml"), "utf8")).toContain(
      'version = "0.2.11-canary.2"',
    );
    expect(readFileSync(join(repo, "native", "Cargo.lock"), "utf8")).toContain(
      'version = "0.2.11-canary.2"',
    );
    expect(readJson(join(repo, "desktop", "package.json")).version).toBe(
      "0.2.11-canary.2",
    );
    expect(readFileSync(join(repo, "cli", "src", "program.ts"), "utf8")).toContain(
      '.version("0.2.11-canary.2")',
    );
  });

  it("keeps the native Cargo workspace on the normal release version", () => {
    const { repo } = createPackageMapRepo();

    const result = runPackageMap(repo, ["set-version", "0.2.11"]);

    expect(result.status).toBe(0);
    expect(readFileSync(join(repo, "native", "Cargo.toml"), "utf8")).toContain(
      'version = "0.2.11"',
    );
    expect(readFileSync(join(repo, "native", "Cargo.lock"), "utf8")).toContain(
      'version = "0.2.11"',
    );
    expect(readJson(join(repo, "desktop", "package.json")).version).toBe("0.2.11");
    expect(readFileSync(join(repo, "cli", "src", "program.ts"), "utf8")).toContain(
      '.version("0.2.11")',
    );
  });

  const commands = [
    ["set-version", "0.2.11"],
    ["set-publish-version", "0.2.11-canary.2", "--allow-source-mutation"],
  ];
  const corruptions = [
    {
      name: "missing workspace package section",
      mutate(repo) {
        writeFileSync(join(repo, "native", "Cargo.toml"), '[workspace]\nmembers = ["crates/native-protocol"]\n');
      },
      error: "native Cargo workspace is missing [workspace.package]",
    },
    {
      name: "missing workspace package version",
      mutate(repo) {
        writeFileSync(join(repo, "native", "Cargo.toml"), '[workspace]\nmembers = ["crates/native-protocol"]\n\n[workspace.package]\nedition = "2024"\n');
      },
      error: "native Cargo workspace package is missing a version",
    },
    {
      name: "missing Cargo lockfile",
      mutate(repo) {
        rmSync(join(repo, "native", "Cargo.lock"));
      },
      error: "native Cargo workspace is missing Cargo.lock",
    },
    {
      name: "member manifest missing a name",
      mutate(repo) {
        writeFileSync(join(repo, "native", "crates", "native-protocol", "Cargo.toml"), '[package]\nversion.workspace = true\n');
      },
      error: "native package manifest is missing a name:",
    },
    {
      name: "member missing from Cargo lockfile",
      mutate(repo) {
        writeFileSync(join(repo, "native", "Cargo.lock"), "# empty workspace lockfile\nversion = 4\n");
      },
      error: "native Cargo.lock is missing workspace package rudder-native-protocol",
    },
  ];

  for (const command of commands) {
    for (const corruption of corruptions) {
      it(`${command[0]} leaves every release file unchanged when ${corruption.name}`, () => {
        const { repo } = createPackageMapRepo();
        corruption.mutate(repo);
        const before = snapshotTree(repo);

        const result = runPackageMap(repo, command);

        expect(result.status).toBe(1);
        expect(result.stderr).toContain(corruption.error);
        expect(snapshotTree(repo)).toEqual(before);
      });
    }
  }

  it("refuses publish manifest rewrites unless release automation opts in", () => {
    const { repo, packagePath } = createPackageMapRepo();
    const before = readFileSync(packagePath, "utf8");

    const result = runPackageMap(repo, ["set-publish-version", "0.2.11"]);

    expect(result.status).toBe(1);
    expect(result.stderr).toContain("Refusing to rewrite source package manifests");
    expect(readFileSync(packagePath, "utf8")).toBe(before);
  });

  it("rewrites publish manifests when source mutation is explicitly allowed", () => {
    const { repo, packagePath } = createPackageMapRepo();

    const result = runPackageMap(repo, ["set-publish-version", "0.2.11", "--allow-source-mutation"]);
    const manifest = readJson(packagePath);

    expect(result.status).toBe(0);
    expect(manifest.version).toBe("0.2.11");
    expect(manifest.exports["."]).toEqual({
      types: "./dist/index.d.ts",
      import: "./dist/index.js",
      default: "./dist/index.js",
    });
    expect(manifest.main).toBe("./dist/index.js");
    expect(manifest.types).toBe("./dist/index.d.ts");
  });
});
