import type { AgentCliCapability } from "./agent-v1-registry.js";

export const AGENT_CLI_CAPABILITIES: AgentCliCapability[] = [
  {
    id: "agent.me",
    command: "rudder agent me",
    category: "agent",
    description: "Show the authenticated agent identity and budget.",
    mutating: false,
    contract: "agent-v1",
    requiresOrgId: false,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: false,
  },
  {
    id: "agent.inbox",
    command: "rudder agent inbox",
    category: "agent",
    description: "List the compact assignee and reviewer work inbox for the authenticated agent.",
    mutating: false,
    contract: "agent-v1",
    requiresOrgId: false,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: false,
  },
  {
    id: "agent.capabilities",
    command: "rudder agent capabilities",
    category: "agent",
    description: "List the stable Rudder agent command contract.",
    mutating: false,
    contract: "agent-v1",
    requiresOrgId: false,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: false,
  },
  {
    id: "agent.list",
    command: "rudder agent list --org-id <id>",
    category: "agent",
    description: "List agents for an organization.",
    mutating: false,
    contract: "compat",
    requiresOrgId: true,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: false,
  },
  {
    id: "agent.get",
    command: "rudder agent get <agent-id-or-shortname-or-agt-ref>",
    category: "agent",
    description: "Read one agent by id, shortname, or agt_<uuid-prefix> short ref.",
    mutating: false,
    contract: "compat",
    requiresOrgId: false,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: false,
  },
  {
    id: "agent.update",
    command: "rudder agent update [agent-id] [--title <title>] [--description <text>]",
    category: "agent",
    description:
      "Update an agent's identity fields; defaults to the authenticated agent.",
    mutating: true,
    contract: "agent-v1",
    requiresOrgId: false,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: true,
  },
  {
    id: "agent.skills.create",
    command: "rudder agent skills create [agent-id] --name <name> [--enable]",
    category: "agent",
    description: "Create an agent-private skill package under AGENT_HOME/skills.",
    mutating: true,
    contract: "agent-v1",
    requiresOrgId: false,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: true,
  },
  {
    id: "agent.skills.enable",
    command: "rudder agent skills enable <agent-id> <selection-ref...>",
    category: "agent",
    description: "Add skill selections to an agent without replacing existing enabled skills.",
    mutating: true,
    contract: "agent-v1",
    requiresOrgId: false,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: true,
  },
  {
    id: "agent.skills.sync",
    command: "rudder agent skills sync <agent-id>",
    category: "agent",
    description: "Sync the desired enabled skill set for an agent.",
    mutating: true,
    contract: "agent-v1",
    requiresOrgId: false,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: true,
  },
  {
    id: "goal.list",
    command: "rudder goal list [--lifecycle <draft|active|closed|all>] [--focus <true|false>] [--facet <facet>] [--limit <n>]",
    category: "goal",
    description: "Discover Goals owned by the authenticated Agent; defaults to active Goals and returns current progress, next step, and attention state.",
    mutating: false,
    contract: "agent-v1",
    requiresOrgId: true,
    requiresAgentId: true,
    requiresRunId: false,
    attachesRunIdWhenAvailable: false,
  },
  {
    id: "goal.context",
    command: "rudder goal context <goal-id>",
    category: "goal",
    description: "Read the owned Goal agreement and current operating context before acting: contract revision, criteria, boundaries, progress, next step, attention, proposals, and recent feedback.",
    mutating: false,
    contract: "agent-v1",
    requiresOrgId: false,
    requiresAgentId: true,
    requiresRunId: false,
    attachesRunIdWhenAvailable: false,
  },
  {
    id: "goal.progress",
    command: "rudder goal progress <goal-id> --summary <text> --evidence-refs <json> --idempotency-key <key>",
    category: "goal",
    description: "Record evidence-backed progress for a Goal owned by the authenticated Agent and attribute it to the current Run.",
    mutating: true,
    contract: "agent-v1",
    requiresOrgId: false,
    requiresAgentId: true,
    requiresRunId: true,
    attachesRunIdWhenAvailable: true,
  },
  {
    id: "goal.checkpoint",
    command: "rudder goal checkpoint <goal-id> --summary <text> --evidence-refs <json> --expected-plan-revision <n> --continuation <json> --idempotency-key <key>",
    category: "goal",
    description: "Atomically persist a Goal checkpoint, optional Plan revision, continuation, checkpoint activity, and eligible automatic continuation wake.",
    mutating: true,
    contract: "agent-v1",
    requiresOrgId: false,
    requiresAgentId: true,
    requiresRunId: true,
    attachesRunIdWhenAvailable: true,
  },
  {
    id: "goal.change.propose",
    command: "rudder goal change propose <goal-id> --contract-revision <n> --after-contract <json> --rationale <text> --idempotency-key <key>",
    category: "goal",
    description: "Propose a reviewable change to the current Goal contract when evidence shows its outcome, criteria, boundaries, or deadlines should change.",
    mutating: true,
    contract: "agent-v1",
    requiresOrgId: false,
    requiresAgentId: true,
    requiresRunId: true,
    attachesRunIdWhenAvailable: true,
  },
  {
    id: "goal.result.propose",
    command: "rudder goal result propose <goal-id> --contract-revision <n> --criteria <json> --evidence-refs <json> --risk-summary <text> --idempotency-key <key>",
    category: "goal",
    description: "Submit an evidence-backed Goal result for mandatory human acceptance without closing the Goal.",
    mutating: true,
    contract: "agent-v1",
    requiresOrgId: false,
    requiresAgentId: true,
    requiresRunId: true,
    attachesRunIdWhenAvailable: true,
  },
  {
    id: "agent.hire",
    command: "rudder agent hire --org-id <id> --payload <json>",
    category: "agent",
    description: "Create a new hire using the canonical hire workflow.",
    mutating: true,
    contract: "compat",
    requiresOrgId: true,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: true,
  },
  {
    id: "agent.config.index",
    command: "rudder agent config index",
    category: "agent",
    description: "Read the installed agent runtime configuration index.",
    mutating: false,
    contract: "compat",
    requiresOrgId: false,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: false,
  },
  {
    id: "agent.config.doc",
    command: "rudder agent config doc <agent-runtime-type>",
    category: "agent",
    description: "Read adapter-specific configuration guidance for one runtime.",
    mutating: false,
    contract: "compat",
    requiresOrgId: false,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: false,
  },
  {
    id: "agent.config.list",
    command: "rudder agent config list --org-id <id>",
    category: "agent",
    description: "List redacted agent configuration snapshots for an organization.",
    mutating: false,
    contract: "compat",
    requiresOrgId: true,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: false,
  },
  {
    id: "agent.config.get",
    command: "rudder agent config get <agent-id-or-shortname>",
    category: "agent",
    description: "Read one redacted agent configuration snapshot by id or shortname.",
    mutating: false,
    contract: "compat",
    requiresOrgId: false,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: false,
  },
  {
    id: "agent.icons",
    command: "rudder agent icons",
    category: "agent",
    description: "List legacy named agent icons for compatibility/debugging; normal create and hire payloads should omit icon.",
    mutating: false,
    contract: "compat",
    requiresOrgId: false,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: false,
  },
  {
    id: "issue.get",
    command: "rudder issue get <issue>",
    category: "issue",
    description: "Read a full issue by UUID or identifier.",
    mutating: false,
    contract: "agent-v1",
    requiresOrgId: false,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: false,
  },
  {
    id: "issue.list",
    command: "rudder issue list --org-id <id>",
    category: "issue",
    description: "List issues with optional status, assignee, and project filters without requiring a search query.",
    mutating: false,
    contract: "agent-v1",
    requiresOrgId: true,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: false,
  },
  {
    id: "issue.search",
    command: "rudder issue search <query> [--org-id <id>]",
    category: "issue",
    description: "Search issues with the server-side issue index across title, identifier, description, and comments.",
    mutating: false,
    contract: "agent-v1",
    requiresOrgId: true,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: false,
  },
  {
    id: "issue.context",
    command: "rudder issue context <issue> [--wake-comment-id <comment-id-or-cmt-ref>]",
    category: "issue",
    description: "Read the compact heartbeat context for an issue; wake comments may be addressed by full id or cmt_<uuid-prefix>.",
    mutating: false,
    contract: "agent-v1",
    requiresOrgId: false,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: false,
  },
  {
    id: "issue.checkout",
    command: "rudder issue checkout <issue>",
    category: "issue",
    description: "Atomically checkout an issue for the current or specified agent.",
    mutating: true,
    contract: "agent-v1",
    requiresOrgId: false,
    requiresAgentId: true,
    requiresRunId: false,
    attachesRunIdWhenAvailable: true,
  },
  {
    id: "issue.comment",
    command: "rudder issue comment <issue> --body-file <path> [--image <path>]",
    category: "issue",
    description: "Add a comment to an issue, optionally uploading images and appending Markdown image links.",
    mutating: true,
    contract: "agent-v1",
    requiresOrgId: false,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: true,
  },
  {
    id: "issue.comments.list",
    command: "rudder issue comments list <issue> [--after <comment-id-or-cmt-ref>]",
    category: "issue",
    description: "List issue comments, optionally only newer comments after a full comment id or cmt_<uuid-prefix> with --after.",
    mutating: false,
    contract: "agent-v1",
    requiresOrgId: false,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: false,
  },
  {
    id: "issue.comments.get",
    command: "rudder issue comments get <issue> <comment-id-or-cmt-ref>",
    category: "issue",
    description: "Read one issue comment by full id or cmt_<uuid-prefix> scoped to the issue.",
    mutating: false,
    contract: "agent-v1",
    requiresOrgId: false,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: false,
  },
  {
    id: "issue.update",
    command: "rudder issue update <issue> ... [--comment-file <path>] [--image <path>]",
    category: "issue",
    description: "Apply generic issue updates when workflow commands are not enough, optionally uploading images for the update comment.",
    mutating: true,
    contract: "agent-v1",
    requiresOrgId: false,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: true,
  },
  {
    id: "issue.review",
    command: "rudder issue review <issue> --decision <decision> --comment-file <path>",
    category: "issue",
    description: "Record a structured reviewer decision with a required comment.",
    mutating: true,
    contract: "agent-v1",
    requiresOrgId: false,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: true,
  },
  {
    id: "issue.commit",
    command: "rudder issue commit <issue> --sha <sha> --message <subject>",
    category: "issue",
    description: "Report a code commit created during issue work as structured issue activity.",
    mutating: true,
    contract: "agent-v1",
    requiresOrgId: false,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: true,
  },
  {
    id: "issue.done",
    command: "rudder issue done <issue> --comment-file <path> [--image <path>]",
    category: "issue",
    description: "Mark an issue done with a required completion comment, optionally uploading images.",
    mutating: true,
    contract: "agent-v1",
    requiresOrgId: false,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: true,
  },
  {
    id: "issue.block",
    command: "rudder issue block <issue> --comment-file <path> [--image <path>]",
    category: "issue",
    description: "Request human assistance after bounded recovery attempts; repeated matching claims are audited before the Issue becomes blocked.",
    mutating: true,
    contract: "agent-v1",
    requiresOrgId: false,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: true,
  },
  {
    id: "project.list",
    command: "rudder project list --org-id <id>",
    category: "project",
    description: "List projects in an organization.",
    mutating: false,
    contract: "agent-v1",
    requiresOrgId: true,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: false,
  },
  {
    id: "project.get",
    command: "rudder project get <project-id-or-shortname> [--org-id <id>]",
    category: "project",
    description: "Read one project by ID or shortname.",
    mutating: false,
    contract: "agent-v1",
    requiresOrgId: false,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: false,
  },
  {
    id: "project.create",
    command: "rudder project create --org-id <id> --name <name>",
    category: "project",
    description: "Create a project in the organization.",
    mutating: true,
    contract: "agent-v1",
    requiresOrgId: true,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: true,
  },
  {
    id: "project.update",
    command: "rudder project update <project-id-or-shortname> [--org-id <id>]",
    category: "project",
    description: "Update mutable project fields such as name, description, status, goals, lead agent, target date, color, or archivedAt.",
    mutating: true,
    contract: "agent-v1",
    requiresOrgId: false,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: true,
  },
  {
    id: "user.activity",
    command: "rudder user activity --user me --since today --json",
    category: "user",
    description: "Read a user-centered activity ledger with safe excerpts and provenance across chats, issue comments, approval comments, and user actor activity.",
    mutating: false,
    contract: "agent-v1",
    requiresOrgId: true,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: false,
  },
  {
    id: "library.file.list",
    command: "rudder library file list [directory]",
    category: "library",
    description: "List Library files and folders; file rows include `libraryEntryId` when a strong reference can be generated.",
    mutating: false,
    contract: "agent-v1",
    requiresOrgId: true,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: false,
  },
  {
    id: "library.file.get",
    command: "rudder library file get <path>",
    category: "library",
    description: "Fallback read when local filesystem access is unavailable; JSON includes `mentionHref` and `markdownLink`.",
    mutating: false,
    contract: "agent-v1",
    requiresOrgId: true,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: false,
  },
  {
    id: "library.file.ref",
    command: "rudder library file ref <path>",
    category: "library",
    description: "Return the stable Markdown reference for one Library file without printing file content.",
    mutating: false,
    contract: "agent-v1",
    requiresOrgId: true,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: false,
  },
  {
    id: "library.file.link",
    command: "rudder library file link <path>",
    category: "library",
    description: "Compatibility alias for `rudder library file ref <path>`.",
    mutating: false,
    contract: "agent-v1",
    requiresOrgId: true,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: false,
  },
  {
    id: "library.file.put",
    command: "rudder library file put <path> --body-file <path>",
    category: "library",
    description: "Fallback create/update when local filesystem access is unavailable; JSON includes `mentionHref` and `markdownLink`.",
    mutating: true,
    contract: "agent-v1",
    requiresOrgId: true,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: true,
  },
  {
    id: "issue.create",
    command: "rudder issue create --org-id <id> ... [--label-id <id> ...] [--label <name> ...]",
    category: "issue",
    description: "Create a new issue or subtask with the generic issue surface; agent-created issues default to the creating agent when no assignee is supplied.",
    mutating: true,
    contract: "compat",
    requiresOrgId: true,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: true,
  },
  {
    id: "issue.labels.list",
    command: "rudder issue labels list --org-id <id>",
    category: "issue",
    description: "List organization issue labels available for issue creation.",
    mutating: false,
    contract: "compat",
    requiresOrgId: true,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: false,
  },
  {
    id: "approval.get",
    command: "rudder approval get <approval-id>",
    category: "approval",
    description: "Read one approval request.",
    mutating: false,
    contract: "agent-v1",
    requiresOrgId: false,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: false,
  },
  {
    id: "approval.create",
    command: "rudder approval create --org-id <id> --type <type> --payload <json>",
    category: "approval",
    description: "Create a new approval request.",
    mutating: true,
    contract: "compat",
    requiresOrgId: true,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: true,
  },
  {
    id: "approval.issues",
    command: "rudder approval issues <approval-id>",
    category: "approval",
    description: "List the issues linked to an approval.",
    mutating: false,
    contract: "agent-v1",
    requiresOrgId: false,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: false,
  },
  {
    id: "approval.comment",
    command: "rudder approval comment <approval-id> --body-file <path>",
    category: "approval",
    description: "Add a comment to an approval.",
    mutating: true,
    contract: "agent-v1",
    requiresOrgId: false,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: true,
  },
  {
    id: "approval.resubmit",
    command: "rudder approval resubmit <approval-id> [--payload <json>]",
    category: "approval",
    description: "Resubmit a revision-requested approval, optionally with updated payload.",
    mutating: true,
    contract: "compat",
    requiresOrgId: false,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: true,
  },
  {
    id: "skill.list",
    command: "rudder skill list --org-id <id>",
    category: "skill",
    description: "List organization-visible skills.",
    mutating: false,
    contract: "agent-v1",
    requiresOrgId: true,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: false,
  },
  {
    id: "skill.get",
    command: "rudder skill get <skill-id> --org-id <id>",
    category: "skill",
    description: "Read one organization skill detail.",
    mutating: false,
    contract: "agent-v1",
    requiresOrgId: true,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: false,
  },
  {
    id: "skill.file",
    command: "rudder skill file <skill-id> --org-id <id> [--path SKILL.md]",
    category: "skill",
    description: "Read one file from an organization skill package.",
    mutating: false,
    contract: "agent-v1",
    requiresOrgId: true,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: false,
  },
  {
    id: "skill.import",
    command: "rudder skill import --org-id <id> --source <source>",
    category: "skill",
    description: "Import a skill package into the organization skill library.",
    mutating: true,
    contract: "agent-v1",
    requiresOrgId: true,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: true,
  },
  {
    id: "skill.scan-local",
    command: "rudder skill scan-local --org-id <id> [--roots <csv>]",
    category: "skill",
    description: "Scan local roots for skill packages and import new ones.",
    mutating: true,
    contract: "agent-v1",
    requiresOrgId: true,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: true,
  },
  {
    id: "skill.scan-projects",
    command: "rudder skill scan-projects --org-id <id> [--project-ids <csv>] [--workspace-ids <csv>]",
    category: "skill",
    description:
      "Scan the org workspace and any legacy project workspace records for skill packages and import new ones.",
    mutating: true,
    contract: "agent-v1",
    requiresOrgId: true,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: true,
  },
  {
    id: "browser.tabs",
    command: "rudder browser tabs",
    category: "browser",
    description: "List Browser tabs owned by the current Rudder agent run.",
    mutating: false,
    contract: "agent-v1",
    requiresOrgId: true,
    requiresAgentId: true,
    requiresRunId: true,
    attachesRunIdWhenAvailable: false,
  },
  {
    id: "browser.user-tabs",
    command: "rudder browser user-tabs",
    category: "browser",
    description: "List user-visible tabs currently open in Rudder's built-in Browser without taking control of them.",
    mutating: false,
    contract: "agent-v1",
    requiresOrgId: true,
    requiresAgentId: true,
    requiresRunId: true,
    attachesRunIdWhenAvailable: false,
  },
  {
    id: "browser.open",
    command: "rudder browser open <url>",
    category: "browser",
    description: "Open a run-owned tab in the Rudder Browser.",
    mutating: true,
    contract: "agent-v1",
    requiresOrgId: true,
    requiresAgentId: true,
    requiresRunId: true,
    attachesRunIdWhenAvailable: true,
  },
  {
    id: "browser.navigate",
    command: "rudder browser navigate <tab-id> <url>",
    category: "browser",
    description: "Navigate a run-owned Rudder Browser tab.",
    mutating: true,
    contract: "agent-v1",
    requiresOrgId: true,
    requiresAgentId: true,
    requiresRunId: true,
    attachesRunIdWhenAvailable: true,
  },
  {
    id: "browser.back",
    command: "rudder browser back <tab-id>",
    category: "browser",
    description: "Navigate a run-owned Rudder Browser tab back in history.",
    mutating: true,
    contract: "agent-v1",
    requiresOrgId: true,
    requiresAgentId: true,
    requiresRunId: true,
    attachesRunIdWhenAvailable: true,
  },
  {
    id: "browser.forward",
    command: "rudder browser forward <tab-id>",
    category: "browser",
    description: "Navigate a run-owned Rudder Browser tab forward in history.",
    mutating: true,
    contract: "agent-v1",
    requiresOrgId: true,
    requiresAgentId: true,
    requiresRunId: true,
    attachesRunIdWhenAvailable: true,
  },
  {
    id: "browser.reload",
    command: "rudder browser reload <tab-id>",
    category: "browser",
    description: "Reload a run-owned Rudder Browser tab.",
    mutating: true,
    contract: "agent-v1",
    requiresOrgId: true,
    requiresAgentId: true,
    requiresRunId: true,
    attachesRunIdWhenAvailable: true,
  },
  {
    id: "browser.viewport",
    command: "rudder browser viewport --action <get|set|reset> [--width <px> --height <px>]",
    category: "browser",
    description: "Inspect, set, or reset the responsive viewport for the current Rudder Browser run.",
    mutating: true,
    contract: "agent-v1",
    requiresOrgId: true,
    requiresAgentId: true,
    requiresRunId: true,
    attachesRunIdWhenAvailable: true,
  },
  {
    id: "browser.visibility",
    command: "rudder browser visibility [--visible <true|false>]",
    category: "browser",
    description: "Inspect or change whether the current run's selected Rudder Browser tab is visible.",
    mutating: true,
    contract: "agent-v1",
    requiresOrgId: true,
    requiresAgentId: true,
    requiresRunId: true,
    attachesRunIdWhenAvailable: true,
  },
  {
    id: "browser.snapshot",
    command: "rudder browser snapshot <tab-id> [--input <json>]",
    category: "browser",
    description: "Capture a bounded DOM and accessibility-oriented snapshot, including frame structure and ephemeral node ids.",
    mutating: false,
    contract: "agent-v1",
    requiresOrgId: true,
    requiresAgentId: true,
    requiresRunId: true,
    attachesRunIdWhenAvailable: true,
  },
  {
    id: "browser.locator",
    command: "rudder browser locator <tab-id> --input <json>",
    category: "browser",
    description: "Perform read-only bounded Browser locator text, attribute, state, count, or wait operations.",
    mutating: false,
    contract: "agent-v1",
    requiresOrgId: true,
    requiresAgentId: true,
    requiresRunId: true,
    attachesRunIdWhenAvailable: true,
  },
  {
    id: "browser.cua",
    command: "rudder browser cua <tab-id> --input <json>",
    category: "browser",
    description: "Perform trusted coordinate mouse, scroll, drag, keyboard, and text input in a run-owned Browser tab.",
    mutating: true,
    contract: "agent-v1",
    requiresOrgId: true,
    requiresAgentId: true,
    requiresRunId: true,
    attachesRunIdWhenAvailable: true,
  },
  {
    id: "browser.dom-cua",
    command: "rudder browser dom-cua <tab-id> --input <json>",
    category: "browser",
    description: "Inspect a bounded read-only DOM snapshot with ephemeral node ids.",
    mutating: false,
    contract: "agent-v1",
    requiresOrgId: true,
    requiresAgentId: true,
    requiresRunId: true,
    attachesRunIdWhenAvailable: true,
  },
  {
    id: "browser.dialog",
    command: "rudder browser dialog <tab-id> --input <json>",
    category: "browser",
    description: "Inspect, accept, or dismiss the active JavaScript dialog in a run-owned Browser tab.",
    mutating: true,
    contract: "agent-v1",
    requiresOrgId: true,
    requiresAgentId: true,
    requiresRunId: true,
    attachesRunIdWhenAvailable: true,
  },
  {
    id: "browser.clipboard",
    command: "rudder browser clipboard --input <json>",
    category: "browser",
    description: "Read or write the isolated virtual clipboard for the current Browser run without touching the OS clipboard.",
    mutating: true,
    contract: "agent-v1",
    requiresOrgId: true,
    requiresAgentId: true,
    requiresRunId: true,
    attachesRunIdWhenAvailable: true,
  },
  {
    id: "browser.logs",
    command: "rudder browser logs <tab-id> [--input <json>]",
    category: "browser",
    description: "Read bounded console and runtime logs captured for a run-owned Browser tab.",
    mutating: true,
    contract: "agent-v1",
    requiresOrgId: true,
    requiresAgentId: true,
    requiresRunId: true,
    attachesRunIdWhenAvailable: true,
  },
  {
    id: "browser.download",
    command: "rudder browser download <tab-id> --input <json>",
    category: "browser",
    description: "Download explicit locator media without dispatching page input into a bounded run-owned artifact.",
    mutating: true,
    contract: "agent-v1",
    requiresOrgId: true,
    requiresAgentId: true,
    requiresRunId: true,
    attachesRunIdWhenAvailable: true,
  },
  {
    id: "browser.assets",
    command: "rudder browser assets <tab-id> --input <json>",
    category: "browser",
    description: "List page assets or bundle an explicit bounded selection into a run-owned temporary artifact.",
    mutating: true,
    contract: "agent-v1",
    requiresOrgId: true,
    requiresAgentId: true,
    requiresRunId: true,
    attachesRunIdWhenAvailable: true,
  },
  {
    id: "browser.content",
    command: "rudder browser content <tab-id> --input <json>",
    category: "browser",
    description: "Export current page content or an eligible Google Workspace document into a bounded run-owned artifact.",
    mutating: true,
    contract: "agent-v1",
    requiresOrgId: true,
    requiresAgentId: true,
    requiresRunId: true,
    attachesRunIdWhenAvailable: true,
  },
  {
    id: "browser.wait",
    command: "rudder browser wait <tab-id> --input <json>",
    category: "browser",
    description: "Wait for bounded URL, text, disappearance, or time conditions in a run-owned Browser tab.",
    mutating: false,
    contract: "agent-v1",
    requiresOrgId: true,
    requiresAgentId: true,
    requiresRunId: true,
    attachesRunIdWhenAvailable: true,
  },
  {
    id: "browser.read",
    command: "rudder browser read <tab-id>",
    category: "browser",
    description: "Read a structured snapshot from a run-owned Rudder Browser tab.",
    mutating: false,
    contract: "agent-v1",
    requiresOrgId: true,
    requiresAgentId: true,
    requiresRunId: true,
    attachesRunIdWhenAvailable: false,
  },
  {
    id: "browser.click",
    command: "rudder browser click <tab-id> <ref>",
    category: "browser",
    description: "Click an element reference returned by Rudder Browser read.",
    mutating: true,
    contract: "agent-v1",
    requiresOrgId: true,
    requiresAgentId: true,
    requiresRunId: true,
    attachesRunIdWhenAvailable: true,
  },
  {
    id: "browser.type",
    command: "rudder browser type <tab-id> <ref> --text <text>",
    category: "browser",
    description: "Type into an element reference in a run-owned Rudder Browser tab.",
    mutating: true,
    contract: "agent-v1",
    requiresOrgId: true,
    requiresAgentId: true,
    requiresRunId: true,
    attachesRunIdWhenAvailable: true,
  },
  {
    id: "browser.screenshot",
    command: "rudder browser screenshot <tab-id> [--input <json>]",
    category: "browser",
    description: "Capture a screenshot of a run-owned Rudder Browser tab.",
    mutating: false,
    contract: "agent-v1",
    requiresOrgId: true,
    requiresAgentId: true,
    requiresRunId: true,
    attachesRunIdWhenAvailable: false,
  },
  {
    id: "browser.close",
    command: "rudder browser close <tab-id>",
    category: "browser",
    description: "Close a run-owned Rudder Browser tab.",
    mutating: true,
    contract: "agent-v1",
    requiresOrgId: true,
    requiresAgentId: true,
    requiresRunId: true,
    attachesRunIdWhenAvailable: true,
  },
  {
    id: "automation.list",
    command: "rudder automation list --org-id <id>",
    category: "automation",
    description: "List automations for an organization with compact local filters.",
    mutating: false,
    contract: "agent-v1",
    requiresOrgId: true,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: false,
  },
  {
    id: "automation.get",
    command: "rudder automation get <automation-id>",
    category: "automation",
    description: "Read one automation detail including triggers and recent runs.",
    mutating: false,
    contract: "agent-v1",
    requiresOrgId: false,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: false,
  },
  {
    id: "automation.runs",
    command: "rudder automation runs <automation-id>",
    category: "automation",
    description: "List recent runs for one automation.",
    mutating: false,
    contract: "agent-v1",
    requiresOrgId: false,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: false,
  },
  {
    id: "automation.triggers.list",
    command: "rudder automation triggers list <automation-id>",
    category: "automation",
    description: "List triggers configured for one automation.",
    mutating: false,
    contract: "agent-v1",
    requiresOrgId: false,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: false,
  },
  {
    id: "automation.triggers.create",
    command: "rudder automation triggers create <automation-id> --kind <kind>",
    category: "automation",
    description: "Create a schedule, webhook, or API trigger through the governed automation API.",
    mutating: true,
    contract: "agent-v1",
    requiresOrgId: false,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: true,
  },
  {
    id: "automation.triggers.update",
    command: "rudder automation triggers update <trigger-id>",
    category: "automation",
    description: "Update an automation trigger through the governed automation API.",
    mutating: true,
    contract: "agent-v1",
    requiresOrgId: false,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: true,
  },
  {
    id: "automation.triggers.delete",
    command: "rudder automation triggers delete <trigger-id>",
    category: "automation",
    description: "Delete an automation trigger through the governed automation API.",
    mutating: true,
    contract: "agent-v1",
    requiresOrgId: false,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: true,
  },
  {
    id: "automation.triggers.rotate-secret",
    command: "rudder automation triggers rotate-secret <trigger-id>",
    category: "automation",
    description: "Rotate an automation webhook trigger secret through the governed automation API.",
    mutating: true,
    contract: "agent-v1",
    requiresOrgId: false,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: true,
  },
  {
    id: "automation.create",
    command: "rudder automation create --org-id <id> --title <title> --assignee-agent-id <id>",
    category: "automation",
    description: "Create an automation through the governed automation API.",
    mutating: true,
    contract: "agent-v1",
    requiresOrgId: true,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: true,
  },
  {
    id: "automation.update",
    command: "rudder automation update <automation-id>",
    category: "automation",
    description: "Update automation fields through the governed automation API.",
    mutating: true,
    contract: "agent-v1",
    requiresOrgId: false,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: true,
  },
  {
    id: "automation.enable",
    command: "rudder automation enable <automation-id>",
    category: "automation",
    description: "Enable an automation by setting status to active.",
    mutating: true,
    contract: "agent-v1",
    requiresOrgId: false,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: true,
  },
  {
    id: "automation.disable",
    command: "rudder automation disable <automation-id>",
    category: "automation",
    description: "Disable an automation by setting status to paused.",
    mutating: true,
    contract: "agent-v1",
    requiresOrgId: false,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: true,
  },
  {
    id: "automation.run",
    command: "rudder automation run <automation-id>",
    category: "automation",
    description: "Trigger a manual automation run.",
    mutating: true,
    contract: "agent-v1",
    requiresOrgId: false,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: true,
  },
  {
    id: "chat.list",
    command: "rudder chat list --org-id <id>",
    category: "chat",
    description: "List chat conversations without dumping full message history.",
    mutating: false,
    contract: "agent-v1",
    requiresOrgId: true,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: false,
  },
  {
    id: "chat.search",
    command: "rudder chat search <query> --org-id <id>",
    category: "chat",
    description: "Search chats with bounded snippets and optional scope filtering.",
    mutating: false,
    contract: "agent-v1",
    requiresOrgId: true,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: false,
  },
  {
    id: "chat.get",
    command: "rudder chat get <chat-id-or-cht-ref>",
    category: "chat",
    description: "Read one chat conversation record.",
    mutating: false,
    contract: "agent-v1",
    requiresOrgId: false,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: false,
  },
  {
    id: "chat.messages",
    command: "rudder chat messages <chat-id-or-cht-ref> [--limit <n>] [--cursor <cursor>] [--include-transcript]",
    category: "chat",
    description: "Read bounded chat messages with page cursors; transcript output is omitted unless requested.",
    mutating: false,
    contract: "agent-v1",
    requiresOrgId: false,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: false,
  },
  {
    id: "chat.transcript",
    command: "rudder chat transcript <chat-id-or-cht-ref> [--limit <n>] [--cursor <cursor>] [--max-output-chars <n>]",
    category: "chat",
    description: "Read paginated chat messages with assistant transcript entries clipped in human output.",
    mutating: false,
    contract: "agent-v1",
    requiresOrgId: false,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: false,
  },
  {
    id: "chat.read",
    command: "rudder chat read <chat-id-or-cht-ref> [--turn-limit <n>] [--cursor <cursor>] [--include-output]",
    category: "chat",
    description: "Read a bounded recent-message snapshot for one chat with page cursors.",
    mutating: false,
    contract: "agent-v1",
    requiresOrgId: false,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: false,
  },
  {
    id: "chat.create",
    command: "rudder chat create --org-id <id> --body <text>",
    category: "chat",
    description: "Create a chat conversation with its first message.",
    mutating: true,
    contract: "agent-v1",
    requiresOrgId: true,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: true,
  },
  {
    id: "chat.send",
    command: "rudder chat send <chat-id-or-cht-ref> --body <text>",
    category: "chat",
    description: "Send an agent-authored message directly to the operator in a chat.",
    mutating: true,
    contract: "agent-v1",
    requiresOrgId: false,
    requiresAgentId: true,
    requiresRunId: false,
    attachesRunIdWhenAvailable: true,
  },
  {
    id: "chat.archive",
    command: "rudder chat archive <chat-id-or-cht-ref>",
    category: "chat",
    description: "Archive a chat conversation without deleting it.",
    mutating: true,
    contract: "agent-v1",
    requiresOrgId: false,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: true,
  },
  {
    id: "runs.list",
    command: "rudder runs list --org-id <id> [--used-skill <skill>] [--loaded-skill <skill>] [--cursor <cursor>] [--full]",
    category: "runs",
    description: "List lightweight run summaries with stable pagination and filters; use --full only for legacy full-row compatibility.",
    mutating: false,
    contract: "agent-v1",
    requiresOrgId: true,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: false,
  },
  {
    id: "runs.by-skill",
    command: "rudder runs by-skill <skill> --org-id <id> [--evidence <used-or-loaded>] [--cursor <cursor>] [--full]",
    category: "runs",
    description: "Build a paginated skill evidence packet from lightweight run summaries; use --full only for legacy full-row compatibility.",
    mutating: false,
    contract: "agent-v1",
    requiresOrgId: true,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: false,
  },
  {
    id: "runs.get",
    command: "rudder runs get <run-id> [--full]",
    category: "runs",
    description: "Read one bounded run summary; use --full only from a direct trusted CLI for raw detail.",
    mutating: false,
    contract: "agent-v1",
    requiresOrgId: false,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: false,
  },
  {
    id: "runs.events",
    command: "rudder runs events <run-id> [--cursor <cursor>] [--after-seq <n>] [--limit <n>] [--full]",
    category: "runs",
    description: "List a bounded page of persisted run events with a lossless opaque cursor and clipped payload previews.",
    mutating: false,
    contract: "agent-v1",
    requiresOrgId: false,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: false,
  },
  {
    id: "runs.log",
    command: "rudder runs log <run-id> [--offset <bytes>] [--limit-bytes <n>]",
    category: "runs",
    description: "Read a bounded byte range of stored run log content.",
    mutating: false,
    contract: "agent-v1",
    requiresOrgId: false,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: false,
  },
  {
    id: "runs.transcript",
    command: "rudder runs transcript <run-id> [--turn-limit <n>] [--cursor <cursor>] [--include-output] [--full]",
    category: "runs",
    description: "Read a compact server-normalized transcript; --json changes encoding only and --full is direct-CLI-only raw access.",
    mutating: false,
    contract: "agent-v1",
    requiresOrgId: false,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: false,
  },
  {
    id: "runs.errors",
    command: "rudder runs errors <run-id>",
    category: "runs",
    description: "List failed tool calls, stderr, runtime failures, and jump-to-context commands.",
    mutating: false,
    contract: "agent-v1",
    requiresOrgId: false,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: false,
  },
  {
    id: "runs.cancel",
    command: "rudder runs cancel <run-id>",
    category: "runs",
    description: "Cancel a heartbeat run through the governed server route.",
    mutating: true,
    contract: "agent-v1",
    requiresOrgId: false,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: true,
  },
  {
    id: "runs.retry",
    command: "rudder runs retry <run-id>",
    category: "runs",
    description: "Retry a failed, timed out, or cancelled run through the governed server route.",
    mutating: true,
    contract: "agent-v1",
    requiresOrgId: false,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: true,
  },
];
