import { RUDDER_MCP_CANONICAL_TOOL_DEFINITIONS } from "@rudderhq/agent-runtime-utils";

export type AgentCliCapabilityCategory =
  | "agent"
  | "issue"
  | "project"
  | "automation"
  | "chat"
  | "runs"
  | "approval"
  | "skill"
  | "browser"
  | "user"
  | "library";
export type AgentCliCapabilityContract = "agent-v1" | "compat";

export interface AgentCliCapability {
  id: string;
  command: string;
  category: AgentCliCapabilityCategory;
  description: string;
  mutating: boolean;
  contract: AgentCliCapabilityContract;
  requiresOrgId: boolean;
  requiresAgentId: boolean;
  requiresRunId: boolean;
  attachesRunIdWhenAvailable: boolean;
}

export interface AgentCliCapabilitiesManifestEntry extends AgentCliCapability {
  agentV1: boolean;
}

export interface AgentCliCapabilitiesManifest {
  schema: "rudder.agent-capabilities/v1";
  contract: AgentCliCapabilityContract | "all";
  defaults: {
    orgIdEnvVar: "RUDDER_ORG_ID";
    agentIdEnvVar: "RUDDER_AGENT_ID";
    runIdEnvVar: "RUDDER_RUN_ID";
    jsonErrors: "stderr-error-envelope";
  };
  capabilities: AgentCliCapabilitiesManifestEntry[];
}

export interface AgentV1McpToolManifestEntry extends AgentCliCapabilitiesManifestEntry {
  capabilityId: string;
  name: string;
  inputSchema: {
    type: "object";
    additionalProperties: boolean;
    properties: Record<string, unknown>;
    required?: string[];
  };
  outputMode: "json";
}

export interface AgentV1McpToolsManifest {
  schema: "rudder.agent-mcp-tools/v1";
  contract: AgentCliCapabilityContract | "all";
  serverName: "rudder-tools";
  tools: AgentV1McpToolManifestEntry[];
}

const AGENT_CLI_CAPABILITIES: AgentCliCapability[] = [
  {
    id: "agent.me",
    command: "rudder agent me",
    category: "agent",
    description: "Show the authenticated agent identity, budget, and chain of command.",
    mutating: false,
    contract: "agent-v1",
    requiresOrgId: false,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: false,
  },
  {
    id: "agent.inbox",
    command: "rudder agent inbox",
    category: "agent",
    description: "List the compact assignee and reviewer work inbox for the authenticated agent.",
    mutating: false,
    contract: "agent-v1",
    requiresOrgId: false,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: false,
  },
  {
    id: "agent.capabilities",
    command: "rudder agent capabilities",
    category: "agent",
    description: "List the stable Rudder agent command contract.",
    mutating: false,
    contract: "agent-v1",
    requiresOrgId: false,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: false,
  },
  {
    id: "agent.list",
    command: "rudder agent list --org-id <id>",
    category: "agent",
    description: "List agents for an organization.",
    mutating: false,
    contract: "compat",
    requiresOrgId: true,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: false,
  },
  {
    id: "agent.get",
    command: "rudder agent get <agent-id-or-shortname-or-agt-ref>",
    category: "agent",
    description: "Read one agent by id, shortname, or agt_<uuid-prefix> short ref.",
    mutating: false,
    contract: "compat",
    requiresOrgId: false,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: false,
  },
  {
    id: "agent.update",
    command: "rudder agent update [agent-id] [--title <title>] [--description <text>]",
    category: "agent",
    description:
      "Update an agent's identity fields; defaults to the authenticated agent.",
    mutating: true,
    contract: "agent-v1",
    requiresOrgId: false,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: true,
  },
  {
    id: "agent.skills.create",
    command: "rudder agent skills create [agent-id] --name <name> [--enable]",
    category: "agent",
    description: "Create an agent-private skill package under AGENT_HOME/skills.",
    mutating: true,
    contract: "agent-v1",
    requiresOrgId: false,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: true,
  },
  {
    id: "agent.skills.enable",
    command: "rudder agent skills enable <agent-id> <selection-ref...>",
    category: "agent",
    description: "Add skill selections to an agent without replacing existing enabled skills.",
    mutating: true,
    contract: "agent-v1",
    requiresOrgId: false,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: true,
  },
  {
    id: "agent.skills.sync",
    command: "rudder agent skills sync <agent-id>",
    category: "agent",
    description: "Sync the desired enabled skill set for an agent.",
    mutating: true,
    contract: "agent-v1",
    requiresOrgId: false,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: true,
  },
  {
    id: "agent.hire",
    command: "rudder agent hire --org-id <id> --payload <json>",
    category: "agent",
    description: "Create a new hire using the canonical hire workflow.",
    mutating: true,
    contract: "compat",
    requiresOrgId: true,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: true,
  },
  {
    id: "agent.config.index",
    command: "rudder agent config index",
    category: "agent",
    description: "Read the installed agent runtime configuration index.",
    mutating: false,
    contract: "compat",
    requiresOrgId: false,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: false,
  },
  {
    id: "agent.config.doc",
    command: "rudder agent config doc <agent-runtime-type>",
    category: "agent",
    description: "Read adapter-specific configuration guidance for one runtime.",
    mutating: false,
    contract: "compat",
    requiresOrgId: false,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: false,
  },
  {
    id: "agent.config.list",
    command: "rudder agent config list --org-id <id>",
    category: "agent",
    description: "List redacted agent configuration snapshots for an organization.",
    mutating: false,
    contract: "compat",
    requiresOrgId: true,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: false,
  },
  {
    id: "agent.config.get",
    command: "rudder agent config get <agent-id-or-shortname>",
    category: "agent",
    description: "Read one redacted agent configuration snapshot by id or shortname.",
    mutating: false,
    contract: "compat",
    requiresOrgId: false,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: false,
  },
  {
    id: "agent.icons",
    command: "rudder agent icons",
    category: "agent",
    description: "List legacy named agent icons for compatibility/debugging; normal create and hire payloads should omit icon.",
    mutating: false,
    contract: "compat",
    requiresOrgId: false,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: false,
  },
  {
    id: "issue.get",
    command: "rudder issue get <issue>",
    category: "issue",
    description: "Read a full issue by UUID or identifier.",
    mutating: false,
    contract: "agent-v1",
    requiresOrgId: false,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: false,
  },
  {
    id: "issue.search",
    command: "rudder issue search <query> [--org-id <id>]",
    category: "issue",
    description: "Search issues with the server-side issue index across title, identifier, description, and comments.",
    mutating: false,
    contract: "agent-v1",
    requiresOrgId: true,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: false,
  },
  {
    id: "issue.context",
    command: "rudder issue context <issue> [--wake-comment-id <comment-id-or-cmt-ref>]",
    category: "issue",
    description: "Read the compact heartbeat context for an issue; wake comments may be addressed by full id or cmt_<uuid-prefix>.",
    mutating: false,
    contract: "agent-v1",
    requiresOrgId: false,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: false,
  },
  {
    id: "issue.checkout",
    command: "rudder issue checkout <issue>",
    category: "issue",
    description: "Atomically checkout an issue for the current or specified agent.",
    mutating: true,
    contract: "agent-v1",
    requiresOrgId: false,
    requiresAgentId: true,
    requiresRunId: false,
    attachesRunIdWhenAvailable: true,
  },
  {
    id: "issue.comment",
    command: "rudder issue comment <issue> --body-file <path> [--image <path>]",
    category: "issue",
    description: "Add a comment to an issue, optionally uploading images and appending Markdown image links.",
    mutating: true,
    contract: "agent-v1",
    requiresOrgId: false,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: true,
  },
  {
    id: "issue.comments.list",
    command: "rudder issue comments list <issue> [--after <comment-id-or-cmt-ref>]",
    category: "issue",
    description: "List issue comments, optionally only newer comments after a full comment id or cmt_<uuid-prefix> with --after.",
    mutating: false,
    contract: "agent-v1",
    requiresOrgId: false,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: false,
  },
  {
    id: "issue.comments.get",
    command: "rudder issue comments get <issue> <comment-id-or-cmt-ref>",
    category: "issue",
    description: "Read one issue comment by full id or cmt_<uuid-prefix> scoped to the issue.",
    mutating: false,
    contract: "agent-v1",
    requiresOrgId: false,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: false,
  },
  {
    id: "issue.update",
    command: "rudder issue update <issue> ... [--comment-file <path>] [--image <path>]",
    category: "issue",
    description: "Apply generic issue updates when workflow commands are not enough, optionally uploading images for the update comment.",
    mutating: true,
    contract: "agent-v1",
    requiresOrgId: false,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: true,
  },
  {
    id: "issue.review",
    command: "rudder issue review <issue> --decision <decision> --comment-file <path>",
    category: "issue",
    description: "Record a structured reviewer decision with a required comment.",
    mutating: true,
    contract: "agent-v1",
    requiresOrgId: false,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: true,
  },
  {
    id: "issue.commit",
    command: "rudder issue commit <issue> --sha <sha> --message <subject>",
    category: "issue",
    description: "Report a code commit created during issue work as structured issue activity.",
    mutating: true,
    contract: "agent-v1",
    requiresOrgId: false,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: true,
  },
  {
    id: "issue.done",
    command: "rudder issue done <issue> --comment-file <path> [--image <path>]",
    category: "issue",
    description: "Mark an issue done with a required completion comment, optionally uploading images.",
    mutating: true,
    contract: "agent-v1",
    requiresOrgId: false,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: true,
  },
  {
    id: "issue.block",
    command: "rudder issue block <issue> --comment-file <path> [--image <path>]",
    category: "issue",
    description: "Mark an issue blocked with a required blocker comment, optionally uploading images.",
    mutating: true,
    contract: "agent-v1",
    requiresOrgId: false,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: true,
  },
  {
    id: "project.list",
    command: "rudder project list --org-id <id>",
    category: "project",
    description: "List projects in an organization.",
    mutating: false,
    contract: "agent-v1",
    requiresOrgId: true,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: false,
  },
  {
    id: "project.get",
    command: "rudder project get <project-id-or-shortname> [--org-id <id>]",
    category: "project",
    description: "Read one project by ID or shortname.",
    mutating: false,
    contract: "agent-v1",
    requiresOrgId: false,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: false,
  },
  {
    id: "project.create",
    command: "rudder project create --org-id <id> --name <name>",
    category: "project",
    description: "Create a project in the organization.",
    mutating: true,
    contract: "agent-v1",
    requiresOrgId: true,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: true,
  },
  {
    id: "project.update",
    command: "rudder project update <project-id-or-shortname> [--org-id <id>]",
    category: "project",
    description: "Update mutable project fields such as name, description, status, goals, lead agent, target date, color, or archivedAt.",
    mutating: true,
    contract: "agent-v1",
    requiresOrgId: false,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: true,
  },
  {
    id: "user.activity",
    command: "rudder user activity --user me --since today --json",
    category: "user",
    description: "Read a user-centered activity ledger with safe excerpts and provenance across chats, issue comments, approval comments, and user actor activity.",
    mutating: false,
    contract: "agent-v1",
    requiresOrgId: true,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: false,
  },
  {
    id: "library.file.list",
    command: "rudder library file list [directory]",
    category: "library",
    description: "List Library files and folders; file rows include `libraryEntryId` when a strong reference can be generated.",
    mutating: false,
    contract: "agent-v1",
    requiresOrgId: true,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: false,
  },
  {
    id: "library.file.get",
    command: "rudder library file get <path>",
    category: "library",
    description: "Fallback read when local filesystem access is unavailable; JSON includes `mentionHref` and `markdownLink`.",
    mutating: false,
    contract: "agent-v1",
    requiresOrgId: true,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: false,
  },
  {
    id: "library.file.ref",
    command: "rudder library file ref <path>",
    category: "library",
    description: "Return the stable Markdown reference for one Library file without printing file content.",
    mutating: false,
    contract: "agent-v1",
    requiresOrgId: true,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: false,
  },
  {
    id: "library.file.link",
    command: "rudder library file link <path>",
    category: "library",
    description: "Compatibility alias for `rudder library file ref <path>`.",
    mutating: false,
    contract: "agent-v1",
    requiresOrgId: true,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: false,
  },
  {
    id: "library.file.put",
    command: "rudder library file put <path> --body-file <path>",
    category: "library",
    description: "Fallback create/update when local filesystem access is unavailable; JSON includes `mentionHref` and `markdownLink`.",
    mutating: true,
    contract: "agent-v1",
    requiresOrgId: true,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: true,
  },
  {
    id: "issue.create",
    command: "rudder issue create --org-id <id> ... [--label-id <id> ...] [--label <name> ...]",
    category: "issue",
    description: "Create a new issue or subtask with the generic issue surface; agent-created issues default to the creating agent when no assignee is supplied.",
    mutating: true,
    contract: "compat",
    requiresOrgId: true,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: true,
  },
  {
    id: "issue.labels.list",
    command: "rudder issue labels list --org-id <id>",
    category: "issue",
    description: "List organization issue labels available for issue creation.",
    mutating: false,
    contract: "compat",
    requiresOrgId: true,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: false,
  },
  {
    id: "approval.get",
    command: "rudder approval get <approval-id>",
    category: "approval",
    description: "Read one approval request.",
    mutating: false,
    contract: "agent-v1",
    requiresOrgId: false,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: false,
  },
  {
    id: "approval.create",
    command: "rudder approval create --org-id <id> --type <type> --payload <json>",
    category: "approval",
    description: "Create a new approval request.",
    mutating: true,
    contract: "compat",
    requiresOrgId: true,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: true,
  },
  {
    id: "approval.issues",
    command: "rudder approval issues <approval-id>",
    category: "approval",
    description: "List the issues linked to an approval.",
    mutating: false,
    contract: "agent-v1",
    requiresOrgId: false,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: false,
  },
  {
    id: "approval.comment",
    command: "rudder approval comment <approval-id> --body-file <path>",
    category: "approval",
    description: "Add a comment to an approval.",
    mutating: true,
    contract: "agent-v1",
    requiresOrgId: false,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: true,
  },
  {
    id: "approval.resubmit",
    command: "rudder approval resubmit <approval-id> [--payload <json>]",
    category: "approval",
    description: "Resubmit a revision-requested approval, optionally with updated payload.",
    mutating: true,
    contract: "compat",
    requiresOrgId: false,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: true,
  },
  {
    id: "skill.list",
    command: "rudder skill list --org-id <id>",
    category: "skill",
    description: "List organization-visible skills.",
    mutating: false,
    contract: "agent-v1",
    requiresOrgId: true,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: false,
  },
  {
    id: "skill.get",
    command: "rudder skill get <skill-id> --org-id <id>",
    category: "skill",
    description: "Read one organization skill detail.",
    mutating: false,
    contract: "agent-v1",
    requiresOrgId: true,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: false,
  },
  {
    id: "skill.file",
    command: "rudder skill file <skill-id> --org-id <id> [--path SKILL.md]",
    category: "skill",
    description: "Read one file from an organization skill package.",
    mutating: false,
    contract: "agent-v1",
    requiresOrgId: true,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: false,
  },
  {
    id: "skill.import",
    command: "rudder skill import --org-id <id> --source <source>",
    category: "skill",
    description: "Import a skill package into the organization skill library.",
    mutating: true,
    contract: "agent-v1",
    requiresOrgId: true,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: true,
  },
  {
    id: "skill.scan-local",
    command: "rudder skill scan-local --org-id <id> [--roots <csv>]",
    category: "skill",
    description: "Scan local roots for skill packages and import new ones.",
    mutating: true,
    contract: "agent-v1",
    requiresOrgId: true,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: true,
  },
  {
    id: "skill.scan-projects",
    command: "rudder skill scan-projects --org-id <id> [--project-ids <csv>] [--workspace-ids <csv>]",
    category: "skill",
    description:
      "Scan the org workspace and any legacy project workspace records for skill packages and import new ones.",
    mutating: true,
    contract: "agent-v1",
    requiresOrgId: true,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: true,
  },
  {
    id: "browser.tabs",
    command: "rudder browser tabs",
    category: "browser",
    description: "List Browser tabs owned by the current Rudder agent run.",
    mutating: false,
    contract: "agent-v1",
    requiresOrgId: true,
    requiresAgentId: true,
    requiresRunId: true,
    attachesRunIdWhenAvailable: false,
  },
  {
    id: "browser.open",
    command: "rudder browser open <url>",
    category: "browser",
    description: "Open a run-owned tab in the Rudder Browser.",
    mutating: true,
    contract: "agent-v1",
    requiresOrgId: true,
    requiresAgentId: true,
    requiresRunId: true,
    attachesRunIdWhenAvailable: true,
  },
  {
    id: "browser.navigate",
    command: "rudder browser navigate <tab-id> <url>",
    category: "browser",
    description: "Navigate a run-owned Rudder Browser tab.",
    mutating: true,
    contract: "agent-v1",
    requiresOrgId: true,
    requiresAgentId: true,
    requiresRunId: true,
    attachesRunIdWhenAvailable: true,
  },
  {
    id: "browser.read",
    command: "rudder browser read <tab-id>",
    category: "browser",
    description: "Read a structured snapshot from a run-owned Rudder Browser tab.",
    mutating: false,
    contract: "agent-v1",
    requiresOrgId: true,
    requiresAgentId: true,
    requiresRunId: true,
    attachesRunIdWhenAvailable: false,
  },
  {
    id: "browser.click",
    command: "rudder browser click <tab-id> <ref>",
    category: "browser",
    description: "Click an element reference returned by Rudder Browser read.",
    mutating: true,
    contract: "agent-v1",
    requiresOrgId: true,
    requiresAgentId: true,
    requiresRunId: true,
    attachesRunIdWhenAvailable: true,
  },
  {
    id: "browser.type",
    command: "rudder browser type <tab-id> <ref> --text <text>",
    category: "browser",
    description: "Type into an element reference in a run-owned Rudder Browser tab.",
    mutating: true,
    contract: "agent-v1",
    requiresOrgId: true,
    requiresAgentId: true,
    requiresRunId: true,
    attachesRunIdWhenAvailable: true,
  },
  {
    id: "browser.screenshot",
    command: "rudder browser screenshot <tab-id>",
    category: "browser",
    description: "Capture a screenshot of a run-owned Rudder Browser tab.",
    mutating: false,
    contract: "agent-v1",
    requiresOrgId: true,
    requiresAgentId: true,
    requiresRunId: true,
    attachesRunIdWhenAvailable: false,
  },
  {
    id: "browser.close",
    command: "rudder browser close <tab-id>",
    category: "browser",
    description: "Close a run-owned Rudder Browser tab.",
    mutating: true,
    contract: "agent-v1",
    requiresOrgId: true,
    requiresAgentId: true,
    requiresRunId: true,
    attachesRunIdWhenAvailable: true,
  },
  {
    id: "automation.list",
    command: "rudder automation list --org-id <id>",
    category: "automation",
    description: "List automations for an organization with compact local filters.",
    mutating: false,
    contract: "agent-v1",
    requiresOrgId: true,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: false,
  },
  {
    id: "automation.get",
    command: "rudder automation get <automation-id>",
    category: "automation",
    description: "Read one automation detail including triggers and recent runs.",
    mutating: false,
    contract: "agent-v1",
    requiresOrgId: false,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: false,
  },
  {
    id: "automation.runs",
    command: "rudder automation runs <automation-id>",
    category: "automation",
    description: "List recent runs for one automation.",
    mutating: false,
    contract: "agent-v1",
    requiresOrgId: false,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: false,
  },
  {
    id: "automation.triggers.list",
    command: "rudder automation triggers list <automation-id>",
    category: "automation",
    description: "List triggers configured for one automation.",
    mutating: false,
    contract: "agent-v1",
    requiresOrgId: false,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: false,
  },
  {
    id: "automation.triggers.create",
    command: "rudder automation triggers create <automation-id> --kind <kind>",
    category: "automation",
    description: "Create a schedule, webhook, or API trigger through the governed automation API.",
    mutating: true,
    contract: "agent-v1",
    requiresOrgId: false,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: true,
  },
  {
    id: "automation.triggers.update",
    command: "rudder automation triggers update <trigger-id>",
    category: "automation",
    description: "Update an automation trigger through the governed automation API.",
    mutating: true,
    contract: "agent-v1",
    requiresOrgId: false,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: true,
  },
  {
    id: "automation.triggers.delete",
    command: "rudder automation triggers delete <trigger-id>",
    category: "automation",
    description: "Delete an automation trigger through the governed automation API.",
    mutating: true,
    contract: "agent-v1",
    requiresOrgId: false,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: true,
  },
  {
    id: "automation.triggers.rotate-secret",
    command: "rudder automation triggers rotate-secret <trigger-id>",
    category: "automation",
    description: "Rotate an automation webhook trigger secret through the governed automation API.",
    mutating: true,
    contract: "agent-v1",
    requiresOrgId: false,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: true,
  },
  {
    id: "automation.create",
    command: "rudder automation create --org-id <id> --title <title> --assignee-agent-id <id>",
    category: "automation",
    description: "Create an automation through the governed automation API.",
    mutating: true,
    contract: "agent-v1",
    requiresOrgId: true,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: true,
  },
  {
    id: "automation.update",
    command: "rudder automation update <automation-id>",
    category: "automation",
    description: "Update automation fields through the governed automation API.",
    mutating: true,
    contract: "agent-v1",
    requiresOrgId: false,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: true,
  },
  {
    id: "automation.enable",
    command: "rudder automation enable <automation-id>",
    category: "automation",
    description: "Enable an automation by setting status to active.",
    mutating: true,
    contract: "agent-v1",
    requiresOrgId: false,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: true,
  },
  {
    id: "automation.disable",
    command: "rudder automation disable <automation-id>",
    category: "automation",
    description: "Disable an automation by setting status to paused.",
    mutating: true,
    contract: "agent-v1",
    requiresOrgId: false,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: true,
  },
  {
    id: "automation.run",
    command: "rudder automation run <automation-id>",
    category: "automation",
    description: "Trigger a manual automation run.",
    mutating: true,
    contract: "agent-v1",
    requiresOrgId: false,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: true,
  },
  {
    id: "chat.list",
    command: "rudder chat list --org-id <id>",
    category: "chat",
    description: "List chat conversations without dumping full message history.",
    mutating: false,
    contract: "agent-v1",
    requiresOrgId: true,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: false,
  },
  {
    id: "chat.search",
    command: "rudder chat search <query> --org-id <id>",
    category: "chat",
    description: "Search chats with bounded snippets and optional scope filtering.",
    mutating: false,
    contract: "agent-v1",
    requiresOrgId: true,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: false,
  },
  {
    id: "chat.get",
    command: "rudder chat get <chat-id>",
    category: "chat",
    description: "Read one chat conversation record.",
    mutating: false,
    contract: "agent-v1",
    requiresOrgId: false,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: false,
  },
  {
    id: "chat.messages",
    command: "rudder chat messages <chat-id> [--limit <n>] [--cursor <cursor>] [--include-transcript]",
    category: "chat",
    description: "Read bounded chat messages with page cursors; transcript output is omitted unless requested.",
    mutating: false,
    contract: "agent-v1",
    requiresOrgId: false,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: false,
  },
  {
    id: "chat.transcript",
    command: "rudder chat transcript <chat-id> [--limit <n>] [--cursor <cursor>] [--max-output-chars <n>]",
    category: "chat",
    description: "Read paginated chat messages with assistant transcript entries clipped in human output.",
    mutating: false,
    contract: "agent-v1",
    requiresOrgId: false,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: false,
  },
  {
    id: "chat.read",
    command: "rudder chat read <chat-id> [--turn-limit <n>] [--cursor <cursor>] [--include-output]",
    category: "chat",
    description: "Read a bounded recent-message snapshot for one chat with page cursors.",
    mutating: false,
    contract: "agent-v1",
    requiresOrgId: false,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: false,
  },
  {
    id: "chat.create",
    command: "rudder chat create --org-id <id> --body <text>",
    category: "chat",
    description: "Create a chat conversation with its first message.",
    mutating: true,
    contract: "agent-v1",
    requiresOrgId: true,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: true,
  },
  {
    id: "chat.send",
    command: "rudder chat send <chat-id> --body <text>",
    category: "chat",
    description: "Send an agent-authored message directly to the operator in a chat.",
    mutating: true,
    contract: "agent-v1",
    requiresOrgId: false,
    requiresAgentId: true,
    requiresRunId: false,
    attachesRunIdWhenAvailable: true,
  },
  {
    id: "chat.archive",
    command: "rudder chat archive <chat-id>",
    category: "chat",
    description: "Archive a chat conversation without deleting it.",
    mutating: true,
    contract: "agent-v1",
    requiresOrgId: false,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: true,
  },
  {
    id: "runs.list",
    command: "rudder runs list --org-id <id> [--used-skill <skill>] [--loaded-skill <skill>] [--cursor <cursor>] [--full]",
    category: "runs",
    description: "List lightweight run summaries with stable pagination and filters; use --full only for legacy full-row compatibility.",
    mutating: false,
    contract: "agent-v1",
    requiresOrgId: true,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: false,
  },
  {
    id: "runs.by-skill",
    command: "rudder runs by-skill <skill> --org-id <id> [--evidence <used-or-loaded>] [--cursor <cursor>] [--full]",
    category: "runs",
    description: "Build a paginated skill evidence packet from lightweight run summaries; use --full only for legacy full-row compatibility.",
    mutating: false,
    contract: "agent-v1",
    requiresOrgId: true,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: false,
  },
  {
    id: "runs.get",
    command: "rudder runs get <run-id> [--full]",
    category: "runs",
    description: "Read one bounded run summary; use --full only from a direct trusted CLI for raw detail.",
    mutating: false,
    contract: "agent-v1",
    requiresOrgId: false,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: false,
  },
  {
    id: "runs.events",
    command: "rudder runs events <run-id> [--cursor <cursor>] [--after-seq <n>] [--limit <n>] [--full]",
    category: "runs",
    description: "List a bounded page of persisted run events with a lossless opaque cursor and clipped payload previews.",
    mutating: false,
    contract: "agent-v1",
    requiresOrgId: false,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: false,
  },
  {
    id: "runs.log",
    command: "rudder runs log <run-id> [--offset <bytes>] [--limit-bytes <n>]",
    category: "runs",
    description: "Read a bounded byte range of stored run log content.",
    mutating: false,
    contract: "agent-v1",
    requiresOrgId: false,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: false,
  },
  {
    id: "runs.transcript",
    command: "rudder runs transcript <run-id> [--turn-limit <n>] [--cursor <cursor>] [--include-output] [--full]",
    category: "runs",
    description: "Read a compact server-normalized transcript; --json changes encoding only and --full is direct-CLI-only raw access.",
    mutating: false,
    contract: "agent-v1",
    requiresOrgId: false,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: false,
  },
  {
    id: "runs.errors",
    command: "rudder runs errors <run-id>",
    category: "runs",
    description: "List failed tool calls, stderr, runtime failures, and jump-to-context commands.",
    mutating: false,
    contract: "agent-v1",
    requiresOrgId: false,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: false,
  },
  {
    id: "runs.cancel",
    command: "rudder runs cancel <run-id>",
    category: "runs",
    description: "Cancel a heartbeat run through the governed server route.",
    mutating: true,
    contract: "agent-v1",
    requiresOrgId: false,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: true,
  },
  {
    id: "runs.retry",
    command: "rudder runs retry <run-id>",
    category: "runs",
    description: "Retry a failed, timed out, or cancelled run through the governed server route.",
    mutating: true,
    contract: "agent-v1",
    requiresOrgId: false,
    requiresAgentId: false,
    requiresRunId: false,
    attachesRunIdWhenAvailable: true,
  },
];

const CATEGORY_TITLES: Record<AgentCliCapabilityCategory, string> = {
  agent: "Agent",
  issue: "Issue",
  project: "Project",
  automation: "Automation",
  chat: "Chat",
  runs: "Runs",
  approval: "Approval",
  skill: "Skill",
  browser: "Browser",
  user: "User",
  library: "Library",
};

export function getAgentCliCapabilities(): AgentCliCapability[] {
  return AGENT_CLI_CAPABILITIES.map((entry) => ({ ...entry }));
}

export function getAgentCliCapabilityById(id: string): AgentCliCapability {
  const entry = AGENT_CLI_CAPABILITIES.find((capability) => capability.id === id);
  if (!entry) {
    throw new Error(`Unknown agent CLI capability: ${id}`);
  }
  return entry;
}

export function buildAgentCliCapabilitiesManifest(
  contract: AgentCliCapabilityContract | "all" = "agent-v1",
): AgentCliCapabilitiesManifest {
  const capabilities = AGENT_CLI_CAPABILITIES
    .filter((entry) => contract === "all" || entry.contract === contract)
    .map((entry) => ({
      ...entry,
      agentV1: entry.contract === "agent-v1",
    }));

  return {
    schema: "rudder.agent-capabilities/v1",
    contract,
    defaults: {
      orgIdEnvVar: "RUDDER_ORG_ID",
      agentIdEnvVar: "RUDDER_AGENT_ID",
      runIdEnvVar: "RUDDER_RUN_ID",
      jsonErrors: "stderr-error-envelope",
    },
    capabilities,
  };
}

export function agentCliCapabilityIdToMcpToolName(id: string): string {
  return `rudder_${id.replace(/[^a-zA-Z0-9]+/g, "_").replace(/^_+|_+$/g, "")}`;
}

export function buildAgentV1McpToolsManifest(
  contract: AgentCliCapabilityContract | "all" = "agent-v1",
  options: { browserEnabled?: boolean } = {},
): AgentV1McpToolsManifest {
  const capabilities = buildAgentCliCapabilitiesManifest(contract).capabilities
    .filter((entry) => options.browserEnabled !== false || entry.category !== "browser");

  const semanticContractByCapability = new Map<string, (typeof RUDDER_MCP_CANONICAL_TOOL_DEFINITIONS)[number]>(
    RUDDER_MCP_CANONICAL_TOOL_DEFINITIONS.map((tool) => [tool.capabilityId, tool]),
  );

  return {
    schema: "rudder.agent-mcp-tools/v1",
    contract,
    serverName: "rudder-tools",
    tools: capabilities.map((entry) => {
      const semanticContract = semanticContractByCapability.get(entry.id);
      if (!semanticContract) {
        throw new Error(`Missing canonical Rudder MCP contract for capability: ${entry.id}`);
      }
      return {
        ...entry,
        description: semanticContract.description,
        capabilityId: entry.id,
        name: semanticContract.name,
        inputSchema: semanticContract.inputSchema,
        outputMode: "json" as const,
      };
    }),
  };
}

export function renderAgentCliReferenceMarkdown(): string {
  const manifest = buildAgentCliCapabilitiesManifest("agent-v1");
  const mcpManifest = buildAgentV1McpToolsManifest("agent-v1");
  const mcpByCapability = new Map(mcpManifest.tools.map((tool) => [tool.capabilityId, tool]));
  const lines: string[] = [
    "# Rudder Agent CLI Reference",
    "",
    "Stable typed-tool and CLI fallback catalog for the bundled `rudder-docs`",
    "package. Prefer first-party Rudder MCP tools when the runtime exposes them; use",
    "these CLI commands as fallback when MCP is unavailable or a Rudder MCP tool",
    "returns a transport or configuration error.",
    "",
    "## Section Map",
    "",
    "- [Operating policy owners](#operating-policy-owners)",
    "- [Defaults](#defaults)",
    "- [JSON output contract](#json-output-contract)",
    "- [Agent V1 commands](#agent-v1-commands)",
    "- [Issue command I/O and shapes](#issue-command-io-and-shapes)",
    "- [Renderable Library CLI output](#renderable-library-cli-output)",
    "- [Reviewer decision command shapes](#reviewer-decision-command-shapes)",
    "- [Compatibility commands](#compatibility-commands)",
    "",
    "## Operating Policy Owners",
    "",
    "Keep this file focused on commands and CLI-specific I/O. Consult the exact",
    "operating-practices guide for operating behavior:",
    "",
    "- [Interface and Chat/issue scope](operating-practices.md#interface-and-scope)",
    "- [Ownership, checkout, and wake scope](operating-practices.md#ownership-checkout-and-wake-scope)",
    "- [Comments, mentions, and evidence](operating-practices.md#comments-mentions-and-evidence)",
    "- [Review and close-out](operating-practices.md#review-and-close-out)",
    "- [Durable Library artifacts](operating-practices.md#durable-library-artifacts)",
    "- [Git identity and attribution](operating-practices.md#git-identity-and-attribution)",
    "",
    "## Defaults",
    "",
    "- First-party MCP tools use the stable `rudder_<capability_id>` naming convention, for example `rudder_issue_checkout` for `issue.checkout`.",
    "- All commands support `--json`.",
    "- CLI output renders IDs as short IDs by default; `rudder runs ...` commands accept short run IDs. Add `--full-ids` only when a debugging or compatibility workflow needs raw UUIDs.",
    "- `--org-id` defaults to `RUDDER_ORG_ID` when relevant.",
    "- `--run-id` defaults to `RUDDER_RUN_ID` and is attached to mutating requests when available.",
    "- `issue checkout` defaults `--agent-id` from `RUDDER_AGENT_ID`.",
    "",
    "## JSON Output Contract",
    "",
    "`rudder ... --json` commands must write valid JSON to stdout on success. ID fields in CLI JSON use short display IDs by default; pass `--full-ids` to preserve raw UUIDs. Short run IDs returned by CLI output can be passed back into `rudder runs get`, `events`, `log`, `transcript`, `errors`, `cancel`, and `retry`. If a command cannot produce the requested JSON, it must exit nonzero and write a diagnostic error to stderr. An exit-0 command with empty stdout is a CLI/runtime defect, not a valid empty result.",
    "",
    "## Agent V1 Commands",
    "",
    "| MCP Tool | CLI Fallback | Description | Mutating | Org | Agent | Run ID |",
    "| --- | --- | --- | --- | --- | --- | --- |",
  ];

  for (const capability of manifest.capabilities) {
    const tool = mcpByCapability.get(capability.id);
    lines.push(
      `| \`${tool?.name ?? agentCliCapabilityIdToMcpToolName(capability.id)}\` | \`${capability.command}\` | ${capability.description} | ${capability.mutating ? "yes" : "no"} | ${
        capability.requiresOrgId ? "required" : "no"
      } | ${capability.requiresAgentId ? "required" : "no"} | ${
        capability.requiresRunId ? "required" : capability.attachesRunIdWhenAvailable ? "attached when available" : "no"
      } |`,
    );
  }

  lines.push(
    "",
    "## Issue Command I/O And Shapes",
    "",
    "Operating rules live in [ownership, checkout, and wake scope](operating-practices.md#ownership-checkout-and-wake-scope), [comments and evidence](operating-practices.md#comments-mentions-and-evidence), and [review and close-out](operating-practices.md#review-and-close-out). The CLI close-out shapes are:",
    "",
    "- progress: `rudder issue comment <issue> --body-file <path> [--image <path>]`",
    "- done: `rudder issue done <issue> --comment-file <path> [--image <path>]`",
    "- blocked: `rudder issue block <issue> --comment-file <path> [--image <path>]`",
    "",
    "Issue comment and close-out commands accept comment bodies only from files or stdin. For multiline Markdown, command names, code spans, code blocks, test summaries, or screenshot evidence, pass `--body-file <path>` or `--comment-file <path>`, or pass `-` to read the body from stdin.",
    "",
    "Issue comment responses include `shortRef` when available. `rudder issue comments get <issue> <comment-id-or-cmt-ref>` accepts a full comment UUID or `cmt_<uuid-prefix>`, and `rudder issue comments list <issue> --after <comment-id-or-cmt-ref>` accepts the same forms for the pagination anchor. Use the full UUID when a short ref is ambiguous within the issue.",
    "",
    "`--image` may be repeated. The CLI uploads each local PNG/JPEG/WebP/GIF as an issue attachment and appends Markdown image links to the comment text before sending it.",
    "",
    "## Renderable Library CLI Output",
    "",
    "File placement and handoff policy lives in [Durable Library artifacts](operating-practices.md#durable-library-artifacts). Request a renderable reference with `rudder library file ref <library-relative-path> --json`.",
    "",
    "The relevant JSON fields are:",
    "",
    "- `libraryEntryId`: stable identity for the Library file.",
    "- `mentionHref`: raw renderable target, optionally with a Rudder-generated path hint.",
    "- `markdownLink`: complete Markdown link for the renderer.",
    "",
    "The `ref` argument is Library-relative, not an absolute filesystem path. CLI fallback shapes are `rudder library file get <library-relative-path> --json` and `rudder library file put <library-relative-path> --body-file <path> --json`. `rudder library file link <library-relative-path> --json` remains a compatibility alias for `ref`.",
    "",
    "## Reviewer Decision Command Shapes",
    "",
    "Reviewer policy lives in [Review and close-out](operating-practices.md#review-and-close-out). Supported decision command shapes are:",
    "",
    "- `rudder issue review <issue> --decision approve --comment-file <path>`",
    "- `rudder issue review <issue> --decision request_changes --comment-file <path>`",
    "- `rudder issue review <issue> --decision needs_followup --comment-file <path>`",
    "- `rudder issue review <issue> --decision blocked --comment-file <path>`",
  );

  lines.push("", "## Compatibility Commands", "");
  for (const capability of AGENT_CLI_CAPABILITIES.filter((entry) => entry.contract === "compat")) {
    lines.push(`- \`${capability.command}\` — ${capability.description}`);
  }

  return lines.join("\n") + "\n";
}

export function formatAgentCliCapabilitiesHumanReadable(
  capabilities: AgentCliCapability[] = getAgentCliCapabilities(),
): string {
  const lines: string[] = [];

  for (const category of Object.keys(CATEGORY_TITLES) as AgentCliCapabilityCategory[]) {
    const entries = capabilities.filter((capability) => capability.category === category);
    if (entries.length === 0) continue;
    lines.push(`${CATEGORY_TITLES[category]} commands:`);
    for (const entry of entries) {
      const tags = [
        entry.contract,
        entry.mutating ? "mutating" : "read-only",
        entry.requiresOrgId ? "org" : null,
        entry.requiresAgentId ? "agent" : null,
        entry.attachesRunIdWhenAvailable ? "run-id" : null,
      ].filter(Boolean);
      lines.push(`- ${entry.command} — ${entry.description} [${tags.join(", ")}]`);
    }
    lines.push("");
  }

  return lines.join("\n").trimEnd();
}
